// @ts-nocheck
import {
  DOMAIN_ID,
  DOMAIN_MEMORY_ADOPTION_STATE,
  DOMAIN_MEMORY_PROOF_CONTRACT_STATE,
  DOMAIN_MEMORY_RUNTIME_WRITEBACK_STATE,
  DOMAIN_OWNER,
  FAMILY_MEMORY_FORBIDDEN_OPL_AUTHORITY,
  FAMILY_MEMORY_STAGE_APPLICABILITY,
  ref,
} from './constants.js';

export function buildDomainMemoryDescriptorLocator() {
  const writebackProposalGenerator = {
    generator_id: 'rca.visual_pattern_memory.writeback_proposal_generator.v1',
    surface_kind: 'visual_pattern_memory_writeback_proposal_generator',
    generator_model: 'locator_only_candidate_projection',
    source_refs: [
      'visual_director_review_ref',
      'screenshot_review_ref',
      'export_closeout_ref',
      'product_entry_session_ref',
      'human_doc_ref',
    ],
    proposal_contract: {
      proposal_id_prefix: 'rca-memory-proposal:visual-pattern:',
      required_fields: [
        'proposal_id',
        'seed_fixture_ref',
        'source_review_ref',
        'stage_scope',
        'deliverable_family',
        'candidate_memory_ref',
        'provenance_refs',
        'recommended_decision',
      ],
      forbidden_fields: [
        'memory_content_body',
        'slide_or_page_content',
        'visual_verdict',
        'export_verdict',
        'review_verdict',
        'canonical_artifact_blob',
      ],
    },
    repository_boundary: {
      repo_tracks_generator_contract: true,
      repo_tracks_proposal_instances: false,
      repo_tracks_memory_entries: false,
      repo_tracks_receipt_instances: false,
      repo_tracks_visual_or_export_artifacts: false,
    },
  };
  const acceptRejectCommand = {
    command_id: 'rca.visual_pattern_memory.accept_reject.v1',
    surface_kind: 'visual_pattern_memory_accept_reject_command',
    owner: DOMAIN_OWNER,
    command_model: 'rca_domain_memory_decision_locator_only',
    allowed_decisions: [
      'accepted',
      'rejected',
    ],
    required_fields: [
      'proposal_id',
      'decision',
      'decision_owner',
      'source_review_ref',
      'candidate_memory_ref',
    ],
    output_refs: [
      'memory_locator_ref',
      'writeback_receipt_ref',
      'operator_receipt_projection_ref',
    ],
    side_effect_boundary: {
      writes_domain_memory_outside_repo: true,
      writes_repo_memory_entry: false,
      writes_repo_receipt_instance: false,
      writes_visual_truth: false,
      writes_review_export_verdict: false,
      writes_canonical_artifact_blob: false,
    },
  };
  const operatorReceiptProjection = {
    projection_id: 'rca.visual_pattern_memory.operator_receipt_projection.v1',
    surface_kind: 'visual_pattern_memory_operator_receipt_projection',
    projection_model: 'operator_visible_locator_status_only',
    source_refs: [
      'writeback_receipt_ref',
      'candidate_memory_ref',
      'product_entry_session_ref',
      'review_closeout_ref',
    ],
    visible_fields: [
      'receipt_id',
      'proposal_id',
      'writeback_status',
      'memory_locator_ref',
      'source_review_ref',
      'operator_message_ref',
    ],
    forbidden_projection_fields: [
      'memory_content_body',
      'visual_verdict',
      'export_verdict',
      'review_verdict',
      'artifact_blob',
    ],
    opl_consumption_policy: {
      opl_can_surface_projection: true,
      opl_can_store_projection_ref: true,
      opl_can_store_memory_content: false,
      opl_can_issue_decision: false,
      opl_can_write_receipt_instance: false,
    },
  };
  const migrationPlan = {
    plan_id: 'rca.visual_pattern_memory.migration_plan.v1',
    state: DOMAIN_MEMORY_ADOPTION_STATE,
    descriptor_proof_contract_state: DOMAIN_MEMORY_PROOF_CONTRACT_STATE,
    runtime_writeback_state: DOMAIN_MEMORY_RUNTIME_WRITEBACK_STATE,
    source_surfaces: [
      'workspace_runtime_root',
      'product_entry_session',
      'visual_director_review',
      'screenshot_review',
      'export_closeout',
      'human_doc_reference',
    ],
    target_surface: 'domain_owned_visual_pattern_memory',
    migration_steps: [
      'discover_candidate_lessons',
      'extract_reusable_pattern_card_candidate',
      'record_seed_fixture_locator_ref',
      'generate_writeback_proposal_locator',
      'domain_review_accept_or_reject',
      'publish_memory_locator_ref',
      'emit_writeback_receipt_ref',
      'project_operator_receipt_status',
    ],
    acceptance_gates: [
      'source_ref_resolves_to_rca_owned_runtime_or_repo_reference',
      'candidate_excludes_current_deliverable_content',
      'candidate_excludes_review_export_verdict',
      'candidate_excludes_canonical_artifact_blob',
      'proposal_is_locator_only',
      'decision_is_rca_owned_accept_or_reject',
      'accepted_memory_has_rca_owner',
      'consumed_memory_refs_are_locator_only',
      'writeback_receipt_is_locator_only',
      'operator_receipt_projection_is_locator_only',
      'opl_hosted_attempt_carries_refs_not_memory_body',
    ],
    repository_boundary: {
      repo_tracks_migration_plan: true,
      repo_tracks_seed_locator_contract: true,
      repo_tracks_memory_entries: false,
      repo_tracks_receipt_instances: false,
      repo_tracks_visual_or_export_artifacts: false,
      visual_truth_changed: false,
      route_truth_changed: false,
    },
  };
  const seedFixtureLocator = {
    fixture_id: 'rca.visual_pattern_memory.seed_fixture_locator.v1',
    fixture_model: 'locator_only_no_memory_content',
    source_root_model: 'workspace_runtime_or_repo_reference',
    accepted_seed_ref_prefixes: [
      'rca-memory-seed:visual-pattern:',
      'workspace-runtime-ref:visual-pattern-seed:',
    ],
    required_locator_fields: [
      'seed_id',
      'source_review_ref',
      'stage_scope',
      'deliverable_family',
      'reusable_lesson_ref',
      'provenance_refs',
      'migration_status',
    ],
    allowed_migration_status_values: [
      'candidate',
      'accepted_for_memory_writeback',
      'rejected_for_memory_writeback',
      'superseded',
    ],
    forbidden_seed_fields: [
      'memory_content_body',
      'slide_or_page_content',
      'visual_verdict',
      'export_verdict',
      'canonical_artifact_blob',
    ],
  };
  const writebackReceiptLocator = {
    locator_id: 'rca.visual_pattern_memory.writeback_receipt_locator.v1',
    receipt_contract_id: 'rca.visual_pattern_memory.writeback_receipt_refs.v1',
    receipt_model: 'locator_only_no_receipt_instance',
    runtime_writeback_state: DOMAIN_MEMORY_RUNTIME_WRITEBACK_STATE,
    source_root_model: 'workspace_runtime_or_domain_memory_reference',
    locator_fields: [
      'receipt_id',
      'proposal_id',
      'source_review_ref',
      'candidate_memory_ref',
      'writeback_status',
      'memory_locator_ref',
      'operator_receipt_projection_ref',
      'owner',
      'created_at',
    ],
    accepted_status_values: [
      'candidate',
      'accepted',
      'rejected',
      'superseded',
    ],
    repo_tracks_receipt_instances: false,
  };
  return {
    surface_kind: 'domain_memory_descriptor_locator',
    status: DOMAIN_MEMORY_ADOPTION_STATE,
    descriptor_id: 'rca.visual_pattern_memory.descriptor.v1',
    locator_id: 'rca.visual_pattern_memory.locator.v1',
    domain_id: DOMAIN_ID,
    owner: DOMAIN_OWNER,
    memory_family: 'visual_pattern_memory',
    memory_model: 'natural_language_pattern_cards',
    descriptor_model: 'repo_tracked_descriptor_refs_only',
    locator_model: 'rca_owned_memory_ref_locator',
    policy_ref: {
      ref_kind: 'human_doc',
      ref: 'human_doc:visual_pattern_memory_policy',
      label: 'Visual Pattern Memory Policy',
    },
    human_doc_ref: {
      ref_kind: 'human_doc',
      ref: 'human_doc:domain_memory_descriptor_locator',
      label: 'RCA domain memory descriptor and locator',
    },
    allowed_memory_card_shape: {
      required_fields: [
        'memory_id',
        'memory_family',
        'owner',
        'stage_scope',
        'deliverable_family',
        'provenance_refs',
        'content_ref',
      ],
      allowed_stage_scopes: [
        'source_readiness',
        'story_architecture',
        'visual_authorship',
        'review_overlay',
        'delivery_packaging',
      ],
      allowed_provenance_ref_kinds: [
        'visual_director_review_ref',
        'screenshot_review_ref',
        'export_closeout_ref',
        'human_doc_ref',
      ],
    },
    memory_locator: {
      ref_kind: 'rca_memory_ref',
      lookup_scope: 'rca_runtime_or_repo_memory_surfaces',
      accepted_ref_prefixes: [
        'rca-memory:visual-pattern:',
        'human_doc:visual_pattern_memory:',
      ],
      content_owner: DOMAIN_OWNER,
      content_storage_authority: DOMAIN_OWNER,
      opl_consumable_fields: [
        'memory_id',
        'stage_scope',
        'deliverable_family',
        'provenance_refs',
        'content_ref',
        'writeback_receipt_ref',
      ],
    },
    migration_plan: migrationPlan,
    writeback_proposal_generator: writebackProposalGenerator,
    accept_reject_command: acceptRejectCommand,
    seed_fixture_locator: seedFixtureLocator,
    writeback_receipt_locator: writebackReceiptLocator,
    operator_receipt_projection: operatorReceiptProjection,
    writeback_receipt_contract: {
      receipt_contract_id: 'rca.visual_pattern_memory.writeback_receipt_refs.v1',
      allowed_receipt_fields: [
        'receipt_id',
        'proposal_id',
        'source_review_ref',
        'candidate_memory_ref',
        'writeback_status',
        'memory_locator_ref',
        'operator_receipt_projection_ref',
        'owner',
        'created_at',
      ],
      forbidden_receipt_fields: [
        'memory_content_body',
        'visual_verdict',
        'export_verdict',
        'review_verdict',
        'canonical_artifact_blob',
      ],
    },
    authority_boundary: {
      memory_content_owner: DOMAIN_OWNER,
      route_truth_owner: DOMAIN_OWNER,
      review_export_verdict_owner: DOMAIN_OWNER,
      artifact_authority_owner: DOMAIN_OWNER,
      opl_role: 'locator_ref_receipt_consumer_only',
      opl_can_hold_memory_content: false,
      opl_can_choose_visual_route: false,
      opl_can_accept_or_reject_memory_writeback: false,
      opl_can_issue_review_or_export_verdict: false,
      opl_can_mutate_canonical_artifacts: false,
    },
  };
}

export function buildFamilyDomainMemoryDescriptor({
  domainMemoryDescriptorLocator = buildDomainMemoryDescriptorLocator(),
  freshnessSource = 'product_entry_manifest_build',
} = {}) {
  return {
    surface_kind: 'family_domain_memory_ref',
    version: 'family-domain-memory-ref.v1',
    memory_ref_id: 'rca_visual_pattern_memory',
    target_domain_id: DOMAIN_ID,
    owner: DOMAIN_OWNER,
    memory_family: domainMemoryDescriptorLocator.memory_family,
    memory_pack_ref: ref(
      '/domain_memory_descriptor_locator',
      'domain_owned_memory_pack_descriptor',
      'RCA visual pattern memory descriptor locator',
    ),
    stage_applicability: FAMILY_MEMORY_STAGE_APPLICABILITY,
    retrieval_contract_ref: ref(
      '/domain_memory_descriptor_locator/memory_locator',
      'locator_only_retrieval_contract',
      'RCA visual pattern memory locator',
    ),
    writeback_contract_ref: ref(
      '/domain_memory_descriptor_locator/writeback_proposal_generator',
      'domain_owned_writeback_proposal_contract',
      'RCA visual pattern memory writeback proposal generator',
    ),
    receipt_contract_ref: ref(
      '/domain_memory_descriptor_locator/writeback_receipt_contract',
      'locator_only_writeback_receipt_contract',
      'RCA visual pattern memory writeback receipt refs',
    ),
    recall_projection_ref: ref(
      '/domain_memory_descriptor_locator/operator_receipt_projection',
      'operator_recall_receipt_projection',
      'RCA visual pattern memory operator receipt projection',
    ),
    migration_plan_ref: ref(
      '/domain_memory_descriptor_locator/migration_plan',
      'domain_owned_migration_plan',
      'RCA visual pattern memory migration plan',
    ),
    seed_corpus_ref: ref(
      '/domain_memory_descriptor_locator/seed_fixture_locator',
      'domain_owned_seed_locator',
      'RCA visual pattern memory seed fixture locator',
    ),
    writeback_receipt_locator_ref: ref(
      '/domain_memory_descriptor_locator/writeback_receipt_locator',
      'domain_owned_writeback_receipt_locator',
      'RCA visual pattern memory writeback receipt locator',
    ),
    provenance_refs: [
      ref('/domain_memory_descriptor_locator/policy_ref', 'policy', 'Visual Pattern Memory Policy'),
      ref('/domain_memory_descriptor_locator/human_doc_ref', 'descriptor_reference', 'RCA domain memory descriptor and locator'),
      ref('/controlled_visual_stage_attempt', 'controlled_stage_attempt_proof', 'RCA controlled visual stage attempt proof'),
    ],
    freshness: {
      source: freshnessSource,
      descriptor_locator_ref: '/domain_memory_descriptor_locator',
      refresh_policy: 'domain_manifest_rebuild_required_before_stage_attempt',
    },
    migration_readiness: {
      status: DOMAIN_MEMORY_ADOPTION_STATE,
      migration_state: domainMemoryDescriptorLocator.migration_plan.state,
      memory_body_migration: 'domain_owned_runtime_apply_required',
      descriptor_proof_contract_state: DOMAIN_MEMORY_PROOF_CONTRACT_STATE,
      runtime_writeback_state: DOMAIN_MEMORY_RUNTIME_WRITEBACK_STATE,
      opl_apply_allowed: false,
      repo_tracks_memory_entries: false,
      repo_tracks_receipt_instances: false,
    },
    status: DOMAIN_MEMORY_ADOPTION_STATE,
    authority_boundary: {
      opl_role: 'locator_projection_owner',
      domain_memory_owner: DOMAIN_OWNER,
      forbidden_opl_authority: FAMILY_MEMORY_FORBIDDEN_OPL_AUTHORITY,
      can_write_domain_truth: false,
      can_authorize_quality_verdict: false,
      can_write_artifacts: false,
      can_choose_visual_route: false,
      can_accept_or_reject_memory_writeback: false,
      can_issue_review_or_export_verdict: false,
    },
  };
}
