// @ts-nocheck

import { readJson } from '../json-file.js';

const DOMAIN_OWNER = 'redcube_ai';

export function buildDomainOwnerReceiptContract() {
  return {
    surface_kind: 'owner_receipt_contract',
    contract_id: 'rca.domain_owner_receipt.v1',
    owner: DOMAIN_OWNER,
    contract_model: 'domain_receipt_typed_blocker_no_regression_refs_only',
    allowed_return_shapes: [
      'domain_receipt',
      'typed_blocker',
      'no_regression_evidence',
    ],
    required_refs: [
      'attempt_ref',
      'artifact_locator_ref',
      'memory_receipt_ref',
      'lifecycle_receipt_ref',
      'review_export_ref',
      'forbidden_write_proof_ref',
    ],
    efficiency_handoff_owner_projection: {
      work_order_ref: 'oma_developer_patch_work_order_5a1b68cacbd4',
      projection_ref: 'opl_generated:product_entry_manifest#/rca_efficiency_handoff_projection/target_agent_owner_surface_refs/owner_receipt_contract_ref',
      target_owner_return_ref: 'target-owner-receipt-or-typed-blocker:redcube_ai/oma_developer_patch_work_order_5a1b68cacbd4',
      allowed_return_shapes_ref: 'opl_generated:product_entry_manifest#/domain_owner_receipt_contract/allowed_return_shapes',
      refs_only: true,
      projects_receipt_body: false,
      writes_visual_truth: false,
      writes_artifact_body: false,
      writes_memory_body: false,
      authorizes_quality_or_export: false,
    },
    goal_workflow_agent_lab_suite_owner_projection: {
      suite_id: 'redcube-ai.goal-workflow.minimal-autonomous-visual-delivery.v1',
      suite_ref: 'contracts/production_acceptance/rca-goal-workflow-agent-lab-suite.json',
      handoff_ref: 'contracts/agent_lab_handoff.json',
      projection_ref: 'opl_generated:product_entry_manifest#/goal_workflow_agent_lab_suite',
      allowed_return_shapes_ref: 'opl_generated:product_entry_manifest#/domain_owner_receipt_contract/allowed_return_shapes',
      refs_only: true,
      projects_receipt_body: false,
      writes_visual_truth: false,
      writes_artifact_body: false,
      writes_memory_body: false,
      authorizes_quality_or_export: false,
    },
    external_work_order_owner_closeout: {
      surface_kind: 'external_work_order_owner_closeout_contract',
      action: 'emit_external_work_order_owner_closeout',
      owner: DOMAIN_OWNER,
      contract_ref: '/domain_owner_receipt_contract',
      refs_only: true,
      input_ref_model: {
        execution_receipt_ref: 'agent-lab-work-order-execution-receipt:<work-order-id>',
        absorbed_head_ref: 'git:commit:<sha>',
        target_verification_refs: ['target-verification:redcube-ai/typecheck'],
        no_forbidden_write_refs: ['no_target_domain_truth_write_proof'],
        patch_absorption_ref: 'patch-absorption:redcube_ai/<work-order-id>/source-patch',
        worktree_cleanup_ref: 'worktree-cleanup:redcube_ai/<work-order-id>/source-patch',
      },
      allowed_return_shapes: [
        'no_regression_evidence',
        'typed_blocker',
      ],
      output_ref_model: {
        no_regression_evidence_ref: 'rca-no-regression:external-work-order:<work-order-id>',
        runtime_locator_ref: 'workspace-runtime-ref:external-work-order-owner-closeout:<work-order-id>',
        typed_blocker_ref: 'rca-typed-blocker:external-work-order-owner-closeout:<blocker-id>',
      },
      authority_boundary: {
        rca_owns_closeout_evidence: true,
        opl_can_store_closeout_ref: true,
        opl_can_store_typed_blocker: true,
        opl_can_write_rca_visual_truth: false,
        opl_can_store_artifact_body: false,
        opl_can_store_memory_body: false,
        opl_can_authorize_quality_or_export: false,
      },
      repository_boundary: {
        repo_tracks_contract_refs: true,
        repo_tracks_live_closeout_instance: false,
        repo_tracks_visual_truth: false,
        repo_tracks_artifact_body: false,
        repo_tracks_memory_body: false,
        repo_tracks_quality_or_export_verdict: false,
      },
    },
    receipt_cases: [
      {
        return_shape: 'domain_receipt',
        receipt_ref: 'rca-owner-receipt:visual-stage:<receipt-id>',
        attempt_ref: '/controlled_visual_stage_attempt',
        artifact_locator_ref: '/artifact_locator_contract',
        memory_receipt_ref: 'rca-memory-receipt:visual-pattern:<accepted-receipt-id>',
        lifecycle_receipt_ref: 'rca-lifecycle-receipt:cleanup:<receipt-id>',
        review_export_ref: '/review_state',
        forbidden_write_proof_ref: '/controlled_memory_apply_proof/forbidden_write_audit',
        owner: DOMAIN_OWNER,
      },
      {
        return_shape: 'domain_receipt',
        receipt_ref: 'rca-owner-receipt:review-export:<family>:<route-stage-id>:<deliverable-id>',
        attempt_ref: 'workspace-runtime-ref:review-export:<family>:<route-stage-id>:<deliverable-id>',
        artifact_locator_ref: 'artifact-locator:redcube_ai:<family>:<route-stage-id>:<deliverable-id>',
        memory_receipt_ref: 'rca-memory-receipt:not-applicable:review-export:<family>:<route-stage-id>:<deliverable-id>',
        lifecycle_receipt_ref: 'rca-lifecycle-receipt:review-export:<family>:<route-stage-id>:<deliverable-id>',
        review_export_ref: 'rca-review-export:<family>:<route-stage-id>:<deliverable-id>',
        forbidden_write_proof_ref: 'rca-forbidden-write-proof:review-export:refs-only',
        producer_routes: [
          'visual_director_review',
          'screenshot_review',
          'repair_image_pages',
          'export_pptx',
        ],
        stage_receipt_policy: 'route_artifact_must_carry_owner_receipt_refs_or_typed_blocker_refs_before_stage_folder_current',
        owner: DOMAIN_OWNER,
      },
      {
        return_shape: 'typed_blocker',
        blocker_ref: 'rca-typed-blocker:review-export:<family>:<route-stage-id>:<deliverable-id>',
        blocker_kind: 'missing_required_artifact_or_review_export_gate_blocked',
        source_contract: 'rca.domain_owner_receipt.v1',
        review_export_ref: 'rca-review-export:<family>:<route-stage-id>:<deliverable-id>',
        producer_routes: [
          'visual_director_review',
          'screenshot_review',
          'repair_image_pages',
          'export_pptx',
        ],
        owner: DOMAIN_OWNER,
        next_required_owner_action: 'repair_or_rerun_required_route_stage',
      },
      {
        return_shape: 'controlled_visual_stage_long_soak_evidence',
        evidence_ref: 'rca-long-soak:visual-stage:<soak-id>',
        runtime_locator_ref: 'workspace-runtime-ref:temporal-controlled-visual-stage-long-soak:<soak-id>',
        generator_action: 'emit_temporal_controlled_visual_stage_long_soak_evidence',
        temporal_stage_attempt_ref: 'workspace-runtime-ref:temporal-stage-attempt:<run-id>',
        retry_dead_letter_ref: 'workspace-runtime-ref:retry-dead-letter:<run-id>',
        requery_resume_ref: 'workspace-runtime-ref:requery-resume:<run-id>',
        provider_residency_ref: 'opl-provider-residency:temporal:<proof-id>',
        stage_execution_ai_task_ref: 'opl-stage-ai-task:execution:<task-id>',
        stage_quality_ai_task_ref: 'opl-stage-ai-task:quality:<task-id>',
        domain_owner_receipt_ref: 'rca-owner-receipt:visual-stage:<receipt-id>',
        review_export_ref: 'workspace-runtime-ref:review-export:<run-id>',
        forbidden_write_proof_ref: '/controlled_memory_apply_proof/forbidden_write_audit',
        owner: DOMAIN_OWNER,
      },
      {
        return_shape: 'typed_blocker',
        blocker_ref: 'rca-typed-blocker:controlled-soak:<blocker-id>',
        blocker_kind: 'domain_owner_receipt_required',
        source_contract: 'rca.temporal_controlled_visual_stage_long_soak.v1',
        owner: DOMAIN_OWNER,
        next_required_owner_action: 'run_temporal_controlled_visual_stage_long_soak_or_emit_rca_refs_only_evidence',
      },
      {
        return_shape: 'no_regression_evidence',
        evidence_ref: 'rca-no-regression:visual-stage:<evidence-id>',
        runtime_locator_ref: 'workspace-runtime-ref:no-regression-evidence:<evidence-id>',
        generator_action: 'emit_no_regression_evidence',
        attempt_ref: '/controlled_visual_stage_attempt',
        surface_refs: [
          '/controlled_memory_apply_proof',
          '/lifecycle_guarded_apply_proof',
          '/runtime_residue_retirement',
        ],
        forbidden_write_proof_ref: '/controlled_memory_apply_proof/forbidden_write_audit',
        owner: DOMAIN_OWNER,
      },
    ],
    opl_consumption_policy: {
      opl_can_store_receipt_refs: true,
      opl_can_store_typed_blocker: true,
      opl_can_store_no_regression_evidence_ref: true,
      opl_can_store_visual_truth: false,
      opl_can_store_review_export_verdict: false,
      opl_can_store_canonical_artifact_blob: false,
      opl_can_accept_or_reject_memory_writeback: false,
      opl_can_mutate_domain_artifacts: false,
    },
    repository_boundary: {
      repo_tracks_contract_and_fixture_refs: true,
      repo_tracks_live_receipt_instances: false,
      repo_tracks_runtime_evidence_instances: false,
      repo_tracks_visual_truth: false,
      repo_tracks_review_export_verdict: false,
      repo_tracks_canonical_artifact_blob: false,
      repo_tracks_memory_content_body: false,
    },
  };
}

export function buildNoRegressionOwnerReceiptOplConsumptionProof() {
  return {
    surface_kind: 'no_regression_owner_receipt_opl_consumption_proof',
    proof_id: 'rca.no_regression_owner_receipt.opl_consumption.v1',
    owner: DOMAIN_OWNER,
    status: 'repo_local_focused_proof_landed_production_soak_pending',
    proof_model: 'domain_action_adapter_guarded_actions_emit_refs_and_return_shapes_only',
    guarded_actions: [
      {
        action: 'emit_no_regression_evidence',
        expected_return_shape: 'no_regression_evidence',
        opl_consumable_ref_field: 'evidence_ref',
        runtime_locator_field: 'runtime_locator_ref',
      },
      {
        action: 'emit_temporal_controlled_visual_stage_long_soak_evidence',
        expected_return_shapes: ['controlled_visual_stage_long_soak_evidence', 'typed_blocker'],
        opl_consumable_ref_field: 'evidence_ref',
        runtime_locator_field: 'runtime_locator_ref',
      },
      {
        action: 'emit_domain_owner_receipt',
        expected_return_shapes: ['domain_receipt', 'typed_blocker'],
        opl_consumable_ref_field: 'receipt_ref',
        runtime_locator_field: 'runtime_locator_ref',
      },
      {
        action: 'emit_external_work_order_owner_closeout',
        expected_return_shapes: ['no_regression_evidence', 'typed_blocker'],
        opl_consumable_ref_field: 'evidence_ref',
        runtime_locator_field: 'runtime_locator_ref',
      },
    ],
    opl_consumption_policy: {
      opl_can_store_no_regression_evidence_ref: true,
      opl_can_store_domain_owner_receipt_ref: true,
      opl_can_store_typed_blocker: true,
      opl_can_use_as_controlled_attempt_closeout_input: true,
      opl_can_declare_visual_ready: false,
      opl_can_declare_exportable: false,
      opl_can_declare_handoffable: false,
      opl_can_claim_production_soak_complete: false,
      opl_can_store_visual_truth: false,
      opl_can_store_review_export_verdict: false,
      opl_can_store_canonical_artifact_blob: false,
      opl_can_mutate_domain_artifacts: false,
    },
    repository_boundary: {
      repo_tracks_focused_proof_contract: true,
      repo_tracks_runtime_evidence_instances: false,
      repo_tracks_live_receipt_instances: false,
      repo_tracks_visual_or_export_artifacts: false,
      repo_tracks_production_soak_result: false,
    },
    source_refs: [
      '/product_entry_shell/domain_handler',
      '/controlled_soak_no_regression_attempt',
      '/domain_owner_receipt_contract',
      '/controlled_memory_apply_proof/forbidden_write_audit',
      '/runtime_residue_retirement',
    ],
  };
}

export function buildRuntimeMemoryReceiptInstances() {
  return {
    surface_kind: 'visual_pattern_memory_runtime_receipt_instances',
    owner: DOMAIN_OWNER,
    instance_model: 'runtime_locator_refs_only',
    repo_tracks_receipt_instances: false,
    repo_tracks_memory_content_body: false,
    instances: [
      {
        writeback_status: 'accepted',
        receipt_ref: 'rca-memory-receipt:visual-pattern:<accepted-receipt-id>',
        runtime_locator_ref: 'workspace-runtime-ref:memory-receipt:<accepted-receipt-id>',
        proposal_ref: 'rca-memory-proposal:visual-pattern:<proposal-id>',
        source_review_ref: 'workspace-runtime-ref:review:<run-id>',
        candidate_memory_ref: 'rca-memory:visual-pattern:<memory-id>',
        memory_locator_ref: 'rca-memory:visual-pattern:<memory-id>',
        memory_content_body_ref: 'rca-memory-content-ref:visual-pattern:<memory-id>',
        operator_receipt_projection_ref: '/domain_memory_descriptor_locator/operator_receipt_projection',
        owner: DOMAIN_OWNER,
      },
      {
        writeback_status: 'rejected',
        receipt_ref: 'rca-memory-receipt:visual-pattern:<rejected-receipt-id>',
        runtime_locator_ref: 'workspace-runtime-ref:memory-receipt:<rejected-receipt-id>',
        proposal_ref: 'rca-memory-proposal:visual-pattern:<proposal-id>',
        source_review_ref: 'workspace-runtime-ref:review:<run-id>',
        candidate_memory_ref: 'rca-memory:visual-pattern:<memory-id>',
        memory_locator_ref: 'rca-memory:visual-pattern:<memory-id>',
        memory_content_body_ref: 'rca-memory-content-ref:visual-pattern:<memory-id>',
        operator_receipt_projection_ref: '/domain_memory_descriptor_locator/operator_receipt_projection',
        owner: DOMAIN_OWNER,
      },
    ],
    forbidden_instance_fields: [
      'memory_content_body',
      'visual_verdict',
      'review_verdict',
      'export_verdict',
      'canonical_artifact_blob',
    ],
  };
}

export function buildLifecycleGuardedApplyProof() {
  const operations = [
    ['cleanup', 'rca-lifecycle-receipt:cleanup:<receipt-id>'],
    ['restore', 'rca-lifecycle-receipt:restore:<receipt-id>'],
    ['retention', 'rca-lifecycle-receipt:retention:<receipt-id>'],
  ];
  return {
    surface_kind: 'lifecycle_guarded_apply_proof',
    proof_id: 'rca.lifecycle_guarded_apply_proof.v1',
    owner: DOMAIN_OWNER,
    status: 'guarded_apply_proof_landed_domain_artifact_mutation_requires_receipt',
    operations: operations.map(([operation, receiptRef]) => ({
      operation,
      owner: DOMAIN_OWNER,
      ledger_ref: `/opl_family_lifecycle_adapter/${operation}`,
      artifact_locator_ref: '/artifact_locator_contract',
      receipt_ref: receiptRef,
      opl_can_apply_domain_artifact_mutation: false,
      domain_receipt_required_for_artifact_mutation: true,
      typed_blocker_ref: `rca-lifecycle-blocker:${operation}:domain-receipt-required`,
    })),
    opl_consumption_policy: {
      opl_can_apply_opl_owned_locator_metadata: true,
      opl_can_request_domain_receipt: true,
      opl_can_delete_or_rewrite_domain_artifact: false,
      opl_can_store_artifact_blob: false,
      opl_can_store_review_export_verdict: false,
    },
    repository_boundary: {
      repo_tracks_lifecycle_contract: true,
      repo_tracks_lifecycle_receipt_instances: false,
      repo_tracks_visual_or_export_artifacts: false,
      repo_tracks_runtime_artifact_blobs: false,
    },
  };
}

export function buildVisualTransitionSpec() {
  const stageKinds = [
    'source_intake',
    'communication_strategy',
    'visual_direction',
    'artifact_creation',
    'review_and_revision',
    'package_and_handoff',
  ];
  return {
    surface_kind: 'visual_transition_spec',
    spec_id: 'rca.visual_transition_spec.v1',
    owner: DOMAIN_OWNER,
    status: 'contract_landed_thin_evaluator_landed_runner_owned_by_opl',
    transition_model: 'rca_owned_transition_table_oracle_fixture_refs_only',
    source_contract: 'human_doc:rca_ideal_state_gap_plan#declare_visual_transition_spec',
    covered_family_stage_kinds: stageKinds,
    transition_table: [
      {
        transition_id: 'source_ready_to_strategy',
        from_stage: 'source_intake',
        to_stage: 'communication_strategy',
        required_guard_refs: ['source_readiness_ref', 'source_gap_ref'],
        owner_action: 'continue_to_communication_strategy',
      },
      {
        transition_id: 'strategy_ready_to_visual_direction',
        from_stage: 'communication_strategy',
        to_stage: 'visual_direction',
        required_guard_refs: ['communication_strategy_ref', 'audience_promise_ref'],
        owner_action: 'continue_to_visual_direction',
      },
      {
        transition_id: 'visual_direction_ready_to_artifact_creation',
        from_stage: 'visual_direction',
        to_stage: 'artifact_creation',
        required_guard_refs: ['visual_direction_ref', 'route_selection_ref', 'artifact_locator_ref'],
        owner_action: 'create_visual_artifacts',
      },
      {
        transition_id: 'artifact_ready_to_review',
        from_stage: 'artifact_creation',
        to_stage: 'review_and_revision',
        required_guard_refs: ['artifact_refs', 'prompt_manifest_ref', 'style_manifest_ref'],
        owner_action: 'run_review_and_repair_gate',
      },
      {
        transition_id: 'review_ready_to_package',
        from_stage: 'review_and_revision',
        to_stage: 'package_and_handoff',
        required_guard_refs: ['review_state_ref', 'blocked_item_ref', 'export_proof_ref'],
        owner_action: 'export_or_return_typed_blocker',
      },
    ],
    guard_contract: {
      guard_model: 'refs_and_typed_blockers_only',
      required_guard_classes: [
        'source_readiness',
        'communication_strategy',
        'visual_direction',
        'artifact_locator',
        'review_state',
        'export_proof',
      ],
      allowed_blocker_kinds: [
        'source_material_required',
        'route_selection_required',
        'artifact_refs_missing',
        'review_blocked_items_present',
        'export_proof_missing',
        'domain_owner_receipt_required',
      ],
    },
    oracle_fixture: {
      fixture_id: 'rca.visual_transition_oracle.fixture.v1',
      fixture_model: 'transition_guard_expected_owner_action_refs_only',
      covered_families: ['ppt_deck', 'xiaohongshu', 'poster_onepager'],
      expected_return_shapes: [
        'next_stage',
        'repair_action',
        'typed_blocker',
        'domain_owner_receipt_ref',
        'no_regression_evidence_ref',
      ],
      forbidden_oracle_fields: [
        'visual_verdict',
        'export_verdict',
        'review_verdict',
        'canonical_artifact_blob',
        'memory_content_body',
      ],
    },
    evaluator_descriptor: {
      descriptor_id: 'rca.visual_transition_evaluator.v1',
      surface_kind: 'visual_transition_evaluator',
      status: 'thin_evaluator_landed_runner_owned_by_opl',
      domain_action_adapter_action: 'evaluate_visual_transition',
      input_model: 'transition_id_current_stage_and_explicit_guard_refs',
      return_shapes: [
        'visual_transition_evaluation',
        'typed_blocker',
      ],
      output_refs: [
        'next_stage',
        'repair_action',
        'typed_blocker',
        'domain_owner_receipt_ref',
        'no_regression_evidence_ref',
        'transition_result_ref',
      ],
      refs_only: true,
    },
    family_transition_spec_descriptor: {
      descriptor_id: 'rca.visual_transition.family_transition_spec_descriptor.v1',
      source_visual_transition_spec_ref: '/visual_transition_spec',
      opl_visual_ingestion_surface: 'one-person-lab/src/family-transition-visual-ingestion.ts',
      opl_generic_runner_contract_ref: 'one-person-lab/contracts/opl-framework/family-transition-runner-contract.json',
      rca_evaluator_ref: '/visual_transition_evaluator',
      rca_bridge_evidence_ref: '/visual_transition_evaluator/bridge_evidence_projection',
      descriptor_model: 'rca_visual_spec_to_opl_family_transition_spec_refs_only',
      rca_implements_opl_generic_runner: false,
      rca_writes_runner_state: false,
    },
    runner_boundary: {
      opl_can_execute_transition_spec: true,
      opl_can_retry_or_dead_letter: true,
      opl_can_store_transition_metadata: true,
      opl_can_declare_visual_ready: false,
      opl_can_declare_exportable: false,
      opl_can_mutate_artifacts: false,
      domain_receipt_required_for_visual_closeout: true,
      rca_can_evaluate_guard_refs: true,
      rca_implements_generic_transition_runner: false,
    },
    repository_boundary: {
      repo_tracks_transition_spec: true,
      repo_tracks_oracle_fixture_contract: true,
      repo_tracks_evaluator_contract: true,
      repo_tracks_runner_state: false,
      repo_tracks_visual_or_export_artifacts: false,
      repo_tracks_receipt_instances: false,
    },
  };
}

export function buildVisualTransitionAdapterProfileRegistry() {
  return readJson(new URL(
    '../../../../../contracts/visual_transition_adapter_profile.json',
    import.meta.url,
  ));
}
