// @ts-nocheck

import {
  FUNCTIONAL_MODULE_FORBIDDEN_OWNER_FLAGS,
  FUNCTIONAL_MODULE_FORBIDDEN_OWNER_FLAGS_REF,
  RCA_PRIVATE_PLATFORM_MEMORY_ARTIFACT_LIFECYCLE_RECEIPT_REFS,
  RCA_FUNCTIONAL_MODULE_REPLACEMENT_GUARDS,
  buildBridgeExitGate,
  buildFunctionalModulePhysicalDeletionGuard,
  buildPrivateGenericResidueBridgeExitGate,
  buildVisualAuthorityFunctionsAuditModule,
  buildVisualPackCompilerHandoffAuditModule,
} from './domain-action-adapter-parts/privatized-functional-module-audit.js';
import {
  buildVisualPackCompilerHandoffProjection,
} from './domain-action-adapter-parts/visual-pack-compiler-handoff.js';
export {
  OPL_GENERATED_INTERFACE_CONSUMPTION,
  buildFamilySchedulerReplacementProjection,
  buildOplGenericPrimitiveConsumptionProjection,
  buildOplStabilityReadModelConsumptionProjection,
  buildOplSubstrateAdapterExportProjection,
} from './domain-action-adapter-parts/opl-generic-boundaries.js';
import {
  OPL_GENERATED_INTERFACE_CONSUMPTION,
  RCA_RETAINED_VISUAL_AUTHORITY,
  buildFamilySchedulerReplacementProjection,
  buildOplGenericPrimitiveConsumptionProjection,
  buildOplStabilityReadModelConsumptionProjection,
} from './domain-action-adapter-parts/opl-generic-boundaries.js';
const CLOSED_DEFAULT_RETIREMENT_COUNT = 8;
const CLOSED_DEFAULT_CALLER_RETIREMENT_COUNT = 5;

const CURRENT_ROLE_GUARD = Object.freeze({
  guard_id: 'rca.private_platform.current_role_guard.v1',
  allowed_roles: Object.freeze([
    'domain_handler_target',
    'refs_only_adapter',
    'declarative_pack',
    'minimal_authority_function',
    'native_helper_implementation',
    'repo_native_verification_wrapper',
    'package_protocol_boundary',
  ]),
  forbidden_owner_flags: Object.freeze({
    rca_owns_generic_scheduler: false,
    rca_owns_generic_runner: false,
    rca_owns_generic_attempt_ledger: false,
    rca_owns_generic_workbench: false,
    rca_owns_generic_review_repair_transport: false,
    rca_owns_generic_session_runtime: false,
    rca_owns_generic_artifact_lifecycle: false,
    rca_owns_generic_generated_wrapper: false,
    rca_owns_generic_domain_entry_runtime: false,
  }),
  compatibility_alias_allowed: false,
  active_default_caller_alias_allowed: false,
});

const RCA_REMAINING_EVIDENCE_GATES = Object.freeze([
  'real_artifact_producing_domain_owner_receipt',
  'opl_hosted_controlled_visual_stage_long_soak',
  'real_memory_lifecycle_receipt_instances',
  'cross_family_repeated_no_regression_evidence',
]);

const RCA_FUNCTIONAL_STRUCTURE_FOLLOWTHROUGH_GAPS = Object.freeze([
]);

const RCA_FUNCTIONAL_STRUCTURE_COMPLETED_GAPS = Object.freeze([
  'opl_generated_surface_production_consumption',
  'repo_local_wrapper_active_caller_migration',
  'focused_hosted_attempt_real_path_cutover',
  'artifact_gallery_handoff_shell',
  'review_repair_transport',
  'opl_app_operator_drilldown',
  'workspace_source_lifecycle_receipt_shell',
  'legacy_physical_cleanup',
]);

function ownerEvidenceLaneIndexFor(moduleItems) {
  return {
    'all-retained-private-platform-residue': {
      source_ref: 'contracts/functional_privatization_audit.json#/physical_deletion_guard',
      builder_ref:
        'packages/redcube-domain-entry/src/actions/domain-action-adapter-parts/privatized-functional-module-audit.ts#buildPrivatePlatformRetirementOwnerEvidenceLane:all-retained-private-platform-residue',
    },
    ...Object.fromEntries(moduleItems.map((entry, index) => [
      entry.module_id.replaceAll('_', '-'),
      {
        source_ref: `contracts/functional_privatization_audit.json#/modules/${index}/physical_deletion_guard`,
        builder_ref:
          `packages/redcube-domain-entry/src/actions/domain-action-adapter-parts/privatized-functional-module-audit.ts#buildPrivatePlatformRetirementOwnerEvidenceLane:${entry.module_id.replaceAll('_', '-')}`,
      },
    ])),
  };
}

const RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS = Object.freeze([
  {
    module_id: 'product_entry_continuity_refs_adapter',
    surface_ref: '/session_continuity',
    status: 'opl_generated_workbench_session_surface_consumed',
    classification: 'refs_only_adapter',
    opl_generic_primitive: 'workbench_shell',
    oplAbsorbCandidate: true,
    generic_substrate_owner: 'one-person-lab',
    rca_owns_generic_substrate: false,
    rcaRetains: ['entry_session_domain_refs', 'deliverable_locator_refs', 'latest_visual_run_ref'],
    rca_scope: 'product_entry_session_domain_snapshot_refs',
    audit_readout: 'project_opl_session_shell_retain_domain_snapshot_refs',
    codePaths: [
      'packages/redcube-domain-entry/src/actions/product-entry-session-refs.ts',
      'packages/redcube-domain-entry/src/actions/get-product-entry-session.ts',
      'packages/redcube-domain-entry/src/actions/get-product-entry-session-parts/session-artifacts.ts',
      'packages/redcube-domain-entry/src/actions/get-product-entry-session-parts/session-surfaces.ts',
      'packages/redcube-domain-entry/src/actions/product-entry-continuity-surfaces.ts',
    ],
    activeCallers: [
      'OPL generated product session domain snapshot refs',
      'OPL generated session shell continuation target',
      'operator loop domain locator refs',
    ],
    activeCallerStatus: 'opl_generated_session_shell_domain_refs',
    migrationAction: 'Use OPL/App generic session shell, resume token, operator navigation and workbench state as the default shell; RCA returns entry-session domain snapshot refs only.',
    retentionReason: 'RCA retains entry_session_id to deliverable/topic/run locators and domain-specific continuation snapshot refs.',
    cannotAbsorbReason: 'OPL can own session shell UX but cannot own RCA deliverable truth, review/export gate or visual session authority.',
    tombstone_required: false,
  },
  {
    module_id: 'workspace_source_intake',
    surface_ref: '/source_intake',
    status: 'source_readiness_refs_adapter_landed',
    classification: 'refs_only_adapter',
    opl_generic_primitive: 'workspace_source_intake_shell',
    oplAbsorbCandidate: true,
    rcaRetains: ['source_readiness_verdict', 'communication_strategy_inputs', 'visual_source_pack_refs'],
    rca_scope: 'visual_source_readiness_and_domain_source_pack_refs',
    audit_readout: 'project_opl_workspace_source_shell_retain_rca_source_verdict',
    codePaths: [
      'packages/redcube-domain-entry/src/actions/intake-source.ts',
      'packages/redcube-runtime/src/source-intake.ts',
      'packages/redcube-runtime/src/source-readiness-pack.ts',
      'packages/redcube-runtime/src/shared-source-truth.ts',
    ],
    activeCallers: [
      'OPL generated source wrapper invokes RCA source readiness handler',
      'source-first fanout source pack refs',
      'product-entry manifest source readiness refs',
    ],
    activeCallerStatus: 'opl_workspace_source_shell_domain_handler_refs',
    migrationAction: 'Keep generic workspace locator, source receipt shell, material gap queue and provenance navigation in OPL; RCA returns source readiness and visual source pack refs only.',
    retentionReason: 'RCA must judge visual source readiness, audience promise inputs and communication strategy source adequacy.',
    cannotAbsorbReason: 'OPL can host source transport but cannot own RCA source readiness verdict or narrative/visual source interpretation.',
    tombstone_required: false,
  },
  {
    module_id: 'memory_writeback_receipt_transport',
    surface_ref: '/controlled_memory_apply_proof',
    status: 'memory_receipt_refs_adapter_landed',
    classification: 'refs_only_adapter',
    opl_generic_primitive: 'memory_refs_only_writeback_chain',
    oplAbsorbCandidate: true,
    rcaRetains: ['visual_memory_body', 'accept_reject_authority', 'memory_quality_judgment'],
    rca_scope: 'visual_memory_accept_reject_and_receipt_refs',
    audit_readout: 'project_opl_memory_transport_retain_visual_memory_authority',
    codePaths: [
      'packages/redcube-domain-entry/src/actions/standard-domain-agent-skeleton-parts/memory-apply-proof.ts',
      'packages/redcube-domain-entry/src/actions/domain-action-adapter.ts#apply_visual_memory_writeback',
      'packages/redcube-domain-entry/src/actions/get-product-entry-manifest-parts/workspace-receipt-inventory.ts',
    ],
    activeCallers: ['apply_visual_memory_writeback domain handler action', 'workspace receipt inventory', 'operator evidence readiness projection'],
    activeCallerStatus: 'active_refs_only_transport',
    migrationAction: 'Keep body-free memory transport, freshness grouping and receipt inventory shell in OPL; RCA returns memory decision and receipt refs only.',
    retentionReason: 'RCA owns visual pattern memory body, accept/reject decision and lesson quality semantics.',
    cannotAbsorbReason: 'OPL must not store visual memory body or decide whether a visual pattern is reusable for RCA deliverables.',
    tombstone_required: false,
  },
  {
    module_id: 'artifact_export_lifecycle',
    surface_ref: '/artifact_locator_contract',
    status: 'opl_artifact_lifecycle_shell_consumed_refs_only',
    classification: 'refs_only_adapter',
    opl_generic_primitive: 'artifact_lifecycle',
    oplAbsorbCandidate: true,
    rcaRetains: ['canonical_artifact_authority', 'export_verdict', 'artifact_mutation_permission'],
    rca_scope: 'visual_artifact_export_authority_and_locator_refs',
    audit_readout: 'project_opl_artifact_lifecycle_retain_rca_export_authority',
    codePaths: [
      'packages/redcube-domain-entry/src/actions/domain-action-adapter.ts#/mapped_surfaces/artifact_locator',
      'packages/redcube-domain-entry/src/actions/domain-action-adapter.ts#apply_visual_workspace_lifecycle',
      'packages/redcube-domain-entry/src/actions/get-product-entry-manifest-parts/manifest-return.ts',
    ],
    activeCallers: ['artifact locator contract', 'export_pptx route', 'workspace lifecycle guarded apply', 'domain-handler export internal projection'],
    activeCallerStatus: 'refs_only_artifact_authority_adapter_consuming_opl_lifecycle_shell',
    migrationAction: 'Consume OPL/App generic artifact inventory, gallery, restore/provenance navigation and handoff shell; keep RCA artifact authority and export verdict refs only.',
    retentionReason: 'RCA owns canonical visual artifacts, exportability verdict and artifact mutation permission.',
    cannotAbsorbReason: 'OPL may index artifact refs but cannot publish, mutate or declare RCA visual artifacts exportable.',
    tombstone_required: false,
  },
  {
    module_id: 'review_repair_transport',
    surface_ref: '/review_state',
    status: 'review_repair_refs_adapter_landed',
    classification: 'refs_only_adapter',
    opl_generic_primitive: 'review_repair_transport',
    oplAbsorbCandidate: true,
    rcaRetains: ['visual_review_verdict', 'repair_decision', 'blocked_item_semantics'],
    rca_scope: 'visual_review_export_verdict_and_repair_decision',
    audit_readout: 'retain_domain_gate_project_transport_refs',
    codePaths: [
      'packages/redcube-domain-entry/src/actions/domain-action-adapter-parts/owner-boundary.ts',
      'packages/redcube-domain-entry/src/actions/domain-action-adapter.ts#/mapped_surfaces/review_projection',
      'packages/redcube-domain-entry/src/actions/domain-action-adapter-parts/visual-transition-evaluator.ts',
    ],
    activeCallers: ['visual director review', 'screenshot review', 'repair_image_pages', 'domain-handler review projection refs'],
    activeCallerStatus: 'active_domain_review_gate',
    migrationAction: 'Keep blocked-item queue, rerun envelope, human approval lane and repair transport shell in OPL; RCA returns review/export verdict and repair target refs only.',
    retentionReason: 'RCA owns visual review/export verdicts, blocked-item meaning and repair target selection.',
    cannotAbsorbReason: 'OPL transport cannot decide if a slide/page is visually acceptable, exportable or needs a specific RCA repair route.',
    tombstone_required: false,
  },
  {
    module_id: 'native_helper_envelope',
    surface_ref: '/native_ppt_operator_ux',
    status: 'native_helper_implementation_opl_envelope_tail',
    classification: 'native_helper_implementation',
    opl_generic_primitive: 'native_helper_generic_envelope',
    oplAbsorbCandidate: true,
    rcaRetains: ['python_native_helper_implementation', 'ppt_image_export_mutation_logic', 'helper_specific_proof'],
    rca_scope: 'python_native_helper_implementation',
    audit_readout: 'retain_rca_implementation_project_opl_envelope',
    codePaths: [
      'packages/redcube-domain-entry/src/actions/get-product-entry-manifest-parts/native-ppt-operator-ux.ts',
      'contracts/runtime-program/python-native-helper-catalog.json',
      'python/redcube_ai',
    ],
    activeCallers: ['native PPT proof lane', 'author_pptx_native route', 'repair_pptx_native route', 'python native helper catalog tests'],
    activeCallerStatus: 'active_rca_native_implementation_package_module_only',
    migrationAction: 'Keep helper registration, environment/provisioning metadata, execution receipt and operator-safe launch envelope in OPL; RCA owns the native helper implementation and route-specific proof refs.',
    retentionReason: 'RCA owns PPT/image/export helper implementation and route-specific mutation/review integration.',
    cannotAbsorbReason: 'OPL can standardize execution envelope but cannot own domain helper logic that mutates RCA visual artifacts.',
    tombstone_required: false,
  },
  {
    module_id: 'operator_projection_shell',
    surface_ref: '/operator_evidence_readiness_projection',
    status: 'operator_evidence_refs_projection_landed',
    classification: 'refs_only_adapter',
    opl_generic_primitive: 'workbench_shell',
    oplAbsorbCandidate: true,
    rcaRetains: ['operator_evidence_refs', 'domain_gap_semantics', 'safe_repair_hints'],
    rca_scope: 'rca_operator_projection_refs_only',
    audit_readout: 'project_opl_app_shell_retain_domain_gap_projection',
    codePaths: [
      'packages/redcube-domain-entry/src/actions/get-product-entry-manifest-parts/manifest-return.ts#/operator_evidence_readiness_projection',
      'packages/redcube-domain-entry/src/actions/get-product-status.ts',
      'packages/redcube-domain-entry/src/actions/domain-action-adapter.ts#/mapped_surfaces/operator_evidence_readiness_projection',
    ],
    activeCallers: [
      'OPL generated product status/workbench consumes RCA operator evidence refs',
      'product-entry manifest domain projection refs',
      'domain-handler export refs-only projection',
      'operator evidence readiness tests',
    ],
    activeCallerStatus: 'opl_app_workbench_shell_domain_evidence_refs',
    migrationAction: 'Keep generic dashboard/workbench layout, attention queue, repair command projection and drilldown shell in OPL App; RCA returns domain evidence refs, blocker meaning and safe repair hints only.',
    retentionReason: 'RCA provides domain evidence refs, blocker meaning and safe repair hints for visual deliverable readiness.',
    cannotAbsorbReason: 'OPL App may render projections but cannot turn them into RCA visual ready/exportable claims.',
    tombstone_required: false,
  },
  {
    module_id: 'generic_cli_mcp_wrappers',
    surface_ref: '/family_action_catalog_parity',
    status: 'canonical_metadata_parity_landed',
    classification: 'domain_handler_target',
    opl_generic_primitive: 'standard_domain_agent_scaffold',
    oplAbsorbCandidate: true,
    generic_substrate_owner: 'one-person-lab',
    rca_owns_generic_substrate: false,
    production_api_owner: 'one-person-lab',
    rca_production_api_role: 'domain_handler_target_refs_only',
    rcaRetains: ['rca_action_metadata', 'domain_action_handlers', 'safe_action_refs'],
    rca_scope: 'domain_handler_status_action_metadata_projection',
    audit_readout: 'retain_thin_projection_project_generated_wrappers',
    codePaths: [
      'apps/redcube-cli/src/cli.ts',
      'packages/redcube-domain-entry/src/actions/family-action-catalog.ts',
      'packages/redcube-domain-entry/src/actions/family-action-catalog.ts',
      'packages/redcube-domain-entry/src/actions/domain-action-adapter-parts/guarded-action-catalog.ts',
    ],
    activeCallers: [
      'OPL generated CLI/MCP wrapper domain handler targets',
      'redcube CLI direct diagnostic entry',
      'OPL generated protocol descriptor targeting RCA domain handlers',
      'family action catalog refs',
      'domain-handler guarded action list refs',
    ],
    activeCallerStatus: 'opl_generated_wrappers_domain_handler_targets',
    migrationAction: 'Use OPL standard domain-agent scaffold for generic wrapper generation, command surface registration and MCP action scaffolding; RCA keeps action metadata and domain handlers only.',
    retentionReason: 'RCA retains canonical action metadata and domain handlers because they encode visual deliverable authority boundaries.',
    cannotAbsorbReason: 'OPL can generate wrappers but cannot own RCA action semantics or guarded domain handler authority.',
    tombstone_required: false,
  },
  {
    module_id: 'codex_executor_adapter',
    surface_ref: '/domain_entry_contract/executor',
    status: 'route_executor_policy_refs_adapter_landed',
    classification: 'refs_only_adapter',
    opl_generic_primitive: 'agent_executor_adapter',
    oplAbsorbCandidate: true,
    generic_substrate_owner: 'one-person-lab',
    rca_owns_generic_substrate: false,
    route_run_record_owner: 'one-person-lab',
    executor_adapter_owner: 'one-person-lab',
    rcaRetains: ['default_codex_executor_policy', 'route_executor_requirements', 'executor_receipt_refs'],
    rca_scope: 'route_level_executor_policy_and_receipt_refs',
    audit_readout: 'project_opl_executor_adapter_retain_rca_route_policy',
    codePaths: [
      'packages/redcube-runtime-protocol/src/executor-runtime.ts',
      'packages/redcube-runtime/src/deliverable-routes.ts',
      'packages/redcube-runtime/src/executors/index.ts',
      'packages/redcube-domain-entry/src/actions/run-deliverable-route.ts',
      'packages/redcube-domain-entry/src/actions/run-deliverable-route-parts/recovery.ts',
      'packages/redcube-domain-entry/src/actions/run-deliverable-route-parts/fix-html-escalation.ts',
      'packages/redcube-domain-entry/src/actions/run-deliverable-route-parts/domain-entry-response.ts',
      'packages/redcube-domain-entry/src/actions/run-deliverable-route-parts/stage-artifacts.ts',
      'packages/redcube-domain-entry/src/actions/domain-entry-contract.ts',
      'tests/rca-executor-backend-contract.test.ts',
    ],
    activeCallers: ['deliverable route runner', 'domain entry contract', 'runtime route executor tests'],
    activeCallerStatus: 'route_run_record_api_refs_only_delete_tail',
    migrationAction: 'Keep executor lifecycle/provisioning, attempt ledger ownership, route-run record persistence policy, event log ownership, stale-running-run audit read model, and generic route dependency/continuation orchestration in OPL generic Agent Executor Adapter and route attempt shell; RCA returns route policy, neutral route-run refs, and receipt refs only.',
    retentionReason: 'RCA keeps route-level executor requirements, Codex CLI as current first-class concrete executor for visual deliverables, and neutral refs-only route-run record refs until OPL attempt ledger/runtime record caller parity is proven.',
    cannotAbsorbReason: 'OPL can provide executor adapter and attempt record mechanics but cannot promise non-Codex outputs are visually equivalent for RCA routes or issue RCA visual review/export verdicts.',
    semantic_equivalence_status: 'cleared_by_boundary',
    semantic_equivalence_reason:
      'RCA exposes only route-level executor policy, neutral route-run refs, executor requirement refs, executor receipt refs, typed blocker refs and no-forbidden-write refs; OPL attempt shell parity remains a bridge-exit blocker, not unresolved semantic ownership.',
    semantic_equivalence_evidence_refs: [
      'semantic-equivalence:rca/codex-executor-adapter/refs-only-route-policy-boundary',
      '/domain_entry_contract/executor',
    ],
    semantic_equivalence_typed_blocker_refs: [
      'typed-blocker:rca/default-caller-deletion/codex_executor_adapter/physical-delete-requires-explicit-owner-receipt',
    ],
    semantic_equivalence_no_regression_refs: [
      'no-forbidden-write:rca/default-caller-deletion/codex_executor_adapter/refs-only-boundary',
    ],
    tombstone_required: false,
  },
  {
    module_id: 'observability_stability_read_model',
    surface_ref: '/opl_stability_read_model_consumption',
    status: 'refs_only_consumer_projection_landed',
    classification: 'refs_only_adapter',
    opl_generic_primitive: 'runtime_observability_exporter',
    oplAbsorbCandidate: true,
    rcaRetains: ['domain_blocker_meaning', 'safe_repair_hint_refs', 'no_regression_evidence_refs'],
    rca_scope: 'visual_domain_status_projection_refs_only',
    audit_readout: 'project_only',
    codePaths: [
      'packages/redcube-domain-entry/src/actions/guarded-domain-actions.ts#/opl_stability_read_model_consumption',
      'packages/redcube-domain-entry/src/actions/get-product-status.ts',
      'packages/redcube-domain-entry/src/actions/domain-action-adapter.ts#/runtime_framework',
    ],
    activeCallers: ['product status refs', 'domain-handler runtime framework refs', 'operator evidence readiness projection'],
    activeCallerStatus: 'active_refs_only_consumer_projection',
    migrationAction: 'Keep observability exporter, SLO, control-loop summary, usage and resource-pressure aggregation in OPL.',
    retentionReason: 'RCA contributes domain blocker meaning, visual-safe repair hints and no-regression evidence refs.',
    cannotAbsorbReason: 'OPL observability cannot authorize RCA quality, exportability or visual remediation decisions.',
    tombstone_required: false,
  },
]);

const FUNCTIONAL_MODULE_MIGRATION_CLASSES = Object.freeze({
  product_entry_continuity_refs_adapter: 'refs_only_adapter',
  workspace_source_intake: 'refs_only_adapter',
  memory_writeback_receipt_transport: 'refs_only_adapter',
  artifact_export_lifecycle: 'refs_only_adapter',
  review_repair_transport: 'refs_only_adapter',
  native_helper_envelope: 'native_helper_implementation',
  operator_projection_shell: 'refs_only_adapter',
  generic_cli_mcp_wrappers: 'domain_handler_target',
  codex_executor_adapter: 'refs_only_adapter',
  observability_stability_read_model: 'refs_only_adapter',
});

const FUNCTIONAL_MODULE_CURRENT_SURFACE_REFS = Object.freeze({
  product_entry_continuity_refs_adapter: [
    'product_session',
    '/session_continuity',
  ],
  generic_cli_mcp_wrappers: [
    'cli',
    'mcp',
    'skill',
    'domain_handler',
    'family_action_catalog',
    'guarded_action_catalog',
  ],
  operator_projection_shell: [
    'product_status',
    'status_read_model',
    'workbench',
    'workbench_drilldown',
    'operator_evidence_readiness_projection',
  ],
});

const FUNCTIONAL_MODULE_EXPECTED_MODES = Object.freeze({
  declarative_pack: 'declarative_pack_consumed_by_opl_hosted_surface',
  domain_handler_target: 'domain_handler_target_called_by_opl_generated_surface',
  refs_only_adapter: 'refs_only_adapter_to_opl_surface',
  minimal_authority_function: 'domain_authority_function_called_by_generated_surface',
  native_helper_implementation: 'native_helper_implementation_called_by_opl_envelope',
  provenance: 'provenance_or_retired_guard',
});

const RCA_FRESH_LARGE_PRIVATE_SURFACE_SCAN = Object.freeze({
  surface_kind: 'rca_large_private_platform_surface_scan',
  scan_date: '2026-06-06',
  scope: 'tracked_ts_js_python_cli_status_runtime_watch_workbench_product_entry_projection_locator_storage_attempt_ledger_state_machine_files',
  line_count_thresholds: {
    primary_attention_lines: 800,
    preferred_source_limit_lines: 1000,
    hard_split_signal_lines: 1500,
  },
  authoritative_gate_entrypoint: 'scripts/line-budget.ts',
  retired_duplicate_gate_entrypoints: [
    'scripts/check-line-budget.ts',
  ],
  package_entrypoint_refs: [
    'package.json#/scripts/line-budget',
    'package.json#/scripts/line-budget:strict',
    'package.json#/scripts/test:line-budget',
    'package.json#/scripts/test:line-budget:strict',
  ],
  verify_entrypoint_refs: [
    'scripts/verify.sh line-budget',
    'scripts/verify.sh line-budget-strict',
    'scripts/verify.sh structure',
    'scripts/verify.sh structure-strict',
  ],
  scan_command_refs: [
    'node --experimental-strip-types scripts/line-budget.ts --list',
    'node --experimental-strip-types scripts/line-budget.ts --strict',
  ],
  current_clean_truth: {
    no_tracked_code_file_exceeds_1500_lines: true,
    authoritative_line_budget_gate_count: 1,
    duplicate_check_line_budget_retired: true,
    line_budget_baseline_only_tracks: [],
    reviewed_baseline_ratchet: {},
    strict_gate_currently_passes: true,
    no_obvious_safe_large_generic_control_plane_split_found: true,
    functional_structure_gap_reopened: false,
  },
  large_surface_readout: [],
  high_risk_surfaces_not_migrated: [
    'visual route truth and family profile policy',
    'image-first artifact creation body',
    'native PPT/Office helper implementation',
    'screenshot/layout review helper behavior',
    'review/export verdict and blocked-item materialization',
  ],
  generic_surfaces_for_opl_or_shared_runtime: [
    'provider-backed stage attempt runtime',
    'attempt ledger and route-run event persistence',
    'generic session/workbench shell',
    'workspace/source locator shell',
    'artifact gallery/handoff shell',
    'review/repair transport shell',
    'native helper execution envelope',
    'operator projection/workbench shell',
    'OPL-generated CLI/MCP/product-entry/domain_action_adapter descriptor/status wrappers with RCA domain-handler targets',
  ],
  migration_gates_before_code_retirement: [
    'generated/default caller parity proven for the replacement OPL surface',
    'domain authority refs preserved',
    'owner receipt roundtrip or no-regression proof recorded',
    'no compatibility alias or retired public path restored',
    'no visual truth, artifact blob, memory body, review/export verdict, or owner receipt authority moved to OPL',
  ],
  verification_entry: [
    'scripts/verify.sh line-budget',
    'npm run contracts:current-program:check',
    'npm run test:meta',
  ],
});

export function buildPrivatizedFunctionalModuleAuditProjection({
  familySchedulerReplacement = buildFamilySchedulerReplacementProjection(),
  oplGenericPrimitiveConsumption = null,
  oplStabilityReadModelConsumption = null,
} = {}) {
  const genericConsumption = oplGenericPrimitiveConsumption || buildOplGenericPrimitiveConsumptionProjection();
  const stabilityConsumption = oplStabilityReadModelConsumption || buildOplStabilityReadModelConsumptionProjection();
  return {
    ref: '/privatized_functional_module_audit',
    contract_ref: 'rca.privatized_functional_module_audit.v1',
    owner: 'redcube_ai',
    consumer: 'opl',
    status: 'machine_audit_projection_landed',
    projection_mode: 'module_boundary_audit_read_model',
    read_only: true,
    refs_only: true,
    audit_scope: [
      'OPL stage execution plan route handler refs',
      'product-entry session snapshot refs adapter',
      'workspace/source intake',
      'memory/writeback receipt transport',
      'artifact export lifecycle',
      'review/repair transport',
    'native helper envelope',
    'operator projection shell',
    'generic CLI/MCP wrappers',
    'generated CLI/MCP/product-entry/domain_handler descriptor/status/session/workbench wrappers with RCA domain-handler targets',
      'Codex executor adapter',
      'observability/stability read model',
    ],
    classification_values: [
      'domain_handler_target',
      'refs_only_adapter',
      'minimal_authority_function',
      'native_helper_implementation',
      'provenance',
    ],
    non_adapter_classification_values: [
      'declarative_pack',
    ],
    replacement_expectation_mode: 'opl_replacement_expectation_or_refs_only_projection',
    generated_interface_consumption_ref: OPL_GENERATED_INTERFACE_CONSUMPTION.ref,
    functional_structure_gap_closure: {
      status: 'functional_structure_gaps_closed_evidence_gates_open',
      closed_at: '2026-05-17',
      closure_scope: 'rca_functional_structure_gap_classification',
      functional_structure_gap_count: RCA_FUNCTIONAL_STRUCTURE_FOLLOWTHROUGH_GAPS.length,
      completed_functional_structure_gap_count: RCA_FUNCTIONAL_STRUCTURE_COMPLETED_GAPS.length,
      completed_functional_structure_gap_ids: [...RCA_FUNCTIONAL_STRUCTURE_COMPLETED_GAPS],
      unclassified_private_generic_residue_count: 0,
      long_term_rca_generic_owner_claim_count: 0,
      remaining_gap_class: 'none',
      remaining_functional_structure_gap_ids: [...RCA_FUNCTIONAL_STRUCTURE_FOLLOWTHROUGH_GAPS],
      remaining_functional_structure_gaps: RCA_FUNCTIONAL_STRUCTURE_FOLLOWTHROUGH_GAPS.map((gapId) => ({
        gap_id: gapId,
        current_bucket: 'functional_structure_gap',
        owner: 'one-person-lab',
        rca_role: 'domain_handler_target_or_visual_authority_refs_only',
      })),
      evidence_gap_class: 'production_live_soak_evidence_only',
      remaining_evidence_gate_ids: [...RCA_REMAINING_EVIDENCE_GATES],
      closure_basis_refs: [
        '/family_scheduler_replacement',
        '/opl_generic_primitive_consumption',
        '/opl_stability_read_model_consumption',
        '/opl_generated_interface_consumption',
        '/visual_pack_compiler_handoff',
        '/operator_evidence_readiness_projection',
        '/opl_substrate_adapter_export',
      ],
      allowed_remaining_module_classes: [
        'domain_handler_target',
        'refs_only_adapter',
        'declarative_pack',
        'minimal_authority_function',
        'native_helper_implementation',
        'provenance',
      ],
    },
    physical_deletion_guard: {
      current_safe_tombstone_candidate_count: 0,
      closed_retirement_count: CLOSED_DEFAULT_RETIREMENT_COUNT,
      closed_default_caller_retirement_count: CLOSED_DEFAULT_CALLER_RETIREMENT_COUNT,
      surface_id_policy: 'current_role_guard_with_count_only_closed_retirement_summary',
      deletion_status: 'closed_retirements_counted_current_roles_guarded',
      current_role_guard: { ...CURRENT_ROLE_GUARD },
      remaining_deletion_scope: 'Only visual authority functions, refs-only projections, and declared visual pack inputs remain in RCA package surfaces.',
      required_before_remaining_physical_delete: [],
      physical_delete_authorization_ref: null,
      physical_delete_authorization_refs: [],
      keep_as_authority_adapter_refs: RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS.map((entry) =>
        `rca-keep-authority-adapter:private-platform-retirement:${entry.module_id.replaceAll('_', '-')}`),
      typed_blocker_refs: RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS.map((entry) =>
        `rca-typed-blocker:private-platform-retirement:${entry.module_id.replaceAll('_', '-')}:physical-delete-requires-explicit-owner-receipt`),
      memory_artifact_lifecycle_receipt_ref: 'contracts/live_stage_run_progress_evidence.json#/refs/memory_lifecycle_refs',
      memory_artifact_lifecycle_receipt_refs: [...RCA_PRIVATE_PLATFORM_MEMORY_ARTIFACT_LIFECYCLE_RECEIPT_REFS],
      owner_evidence_lane_ref:
        'contracts/functional_privatization_audit.json#/owner_evidence_lane_index/all-retained-private-platform-residue',
      owner_evidence_lane_builder_ref:
        'packages/redcube-domain-entry/src/actions/domain-action-adapter-parts/privatized-functional-module-audit.ts#buildPrivatePlatformRetirementOwnerEvidenceLane:all-retained-private-platform-residue',
    },
    owner_evidence_lane_index: ownerEvidenceLaneIndexFor(RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS),
    fresh_large_private_surface_scan: RCA_FRESH_LARGE_PRIVATE_SURFACE_SCAN,
    bridge_exit_gate: buildPrivateGenericResidueBridgeExitGate(RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS),
    forbidden_generic_owner_flags: { ...FUNCTIONAL_MODULE_FORBIDDEN_OWNER_FLAGS },
    rca_visual_authority_allowlist: [
      'source_readiness_verdict',
      'communication_visual_direction_decision',
      'review_export_verdict',
      'artifact_mutation_authorization',
      'visual_memory_accept_reject',
      'owner_receipt_signer',
      'native_helper_implementation',
    ],
    visual_pack_compiler_handoff_ref: '/visual_pack_compiler_handoff',
    modules: RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS.map((entry) => {
      const replacementGuard = RCA_FUNCTIONAL_MODULE_REPLACEMENT_GUARDS[entry.module_id] || {};
      const migrationClass = FUNCTIONAL_MODULE_MIGRATION_CLASSES[entry.module_id] || 'refs_only_adapter';
      return {
        ...entry,
        migration_class: migrationClass,
        active_reader_facing_classification: migrationClass,
        opl_owned_generic_primitive_consumer: true,
        rca_owned_visual_domain_authority: [
          'workspace_source_intake',
          'memory_writeback_receipt_transport',
          'artifact_export_lifecycle',
          'review_repair_transport',
          'native_helper_envelope',
          'generic_cli_mcp_wrappers',
          'codex_executor_adapter',
        ].includes(entry.module_id),
        opl_absorb_candidate: entry.oplAbsorbCandidate === true,
        opl_replacement_expectation: {
          owner: 'opl',
          expectation_ref: replacementGuard.expectation_ref || '/opl_generic_primitive_consumption',
          replacement_surface: replacementGuard.opl_replacement_surface || entry.opl_generic_primitive,
          expected_mode: FUNCTIONAL_MODULE_EXPECTED_MODES[migrationClass] || 'refs_only_adapter_to_opl_surface',
          rca_consumes_as: 'consumer_projection_only',
          rca_owns_replacement_runtime: false,
        },
        bridge_exit_gate: buildBridgeExitGate(entry, replacementGuard),
        current_surface_refs: FUNCTIONAL_MODULE_CURRENT_SURFACE_REFS[entry.module_id] || [entry.surface_ref],
        rca_projection_mode: replacementGuard.rca_projection_mode || 'refs_only_projection',
        rca_exports_only: replacementGuard.rca_exports_only || [],
        default_caller_contract: replacementGuard.default_caller_contract
          ? { ...replacementGuard.default_caller_contract }
          : undefined,
        forbidden_generic_owner_flags_ref: FUNCTIONAL_MODULE_FORBIDDEN_OWNER_FLAGS_REF,
        physical_deletion_guard: buildFunctionalModulePhysicalDeletionGuard(entry),
        rca_retains: entry.rcaRetains || [],
        repo_local_handler_target_only: entry.module_id === 'generic_cli_mcp_wrappers' ? true : undefined,
        generated_surface_metadata_owner: entry.module_id === 'generic_cli_mcp_wrappers' ? 'one-person-lab' : undefined,
        generated_session_shell_owner: entry.module_id === 'product_entry_continuity_refs_adapter' ? 'one-person-lab' : undefined,
        retire_tombstone: false,
        writes_visual_truth: false,
        writes_artifact_blob: false,
        writes_memory_body: false,
        declares_visual_ready: false,
        declares_exportable: false,
        declares_handoffable: false,
        declares_production_soak_complete: false,
      };
    }).concat([
      buildVisualPackCompilerHandoffAuditModule(),
      buildVisualAuthorityFunctionsAuditModule(),
    ]),
    opl_owned_generic_primitives: [
      ...new Set([
        ...(familySchedulerReplacement.opl_owned_generic_surfaces || []),
        ...(genericConsumption.opl_owned_generic_primitives || []),
        ...(stabilityConsumption.rca_does_not_own || []),
      ]),
    ],
    opl_generated_interface_consumption: { ...OPL_GENERATED_INTERFACE_CONSUMPTION },
    rca_retained_authority: [...RCA_RETAINED_VISUAL_AUTHORITY],
    protected_rca_surfaces: [
      'visual_deliverable_internal_dag',
      'visual_truth',
      'review_export_verdict',
      'repair_decision',
      'artifact_authority',
      'visual_memory_body',
      'owner_receipt',
      'native_helper_implementation',
    ],
    closed_retirement_summary: {
      surface_kind: 'rca_closed_retirement_count_summary',
      closed_retirement_count: CLOSED_DEFAULT_RETIREMENT_COUNT,
      closed_default_caller_retirement_count: CLOSED_DEFAULT_CALLER_RETIREMENT_COUNT,
      current_role_guard: { ...CURRENT_ROLE_GUARD },
      compatibility_alias_allowed: false,
      active_default_caller_alias_allowed: false,
    },
    must_not_retire: [
      'visual_stage_descriptor',
      'visual_review_export_gate',
      'native_helper_implementation',
      'artifact_gallery_export_refs',
      'codex_cli_default_route_policy',
    ],
    authority_boundary: {
      opl_can_index_audit_projection: true,
      opl_can_import_generic_primitives: true,
      domain_can_claim_generic_runtime_owner: false,
      domain_repo_can_own_generated_surface: false,
      opl_can_write_rca_visual_truth: false,
      opl_can_write_rca_artifact_blob: false,
      opl_can_write_rca_memory_body: false,
      opl_can_declare_visual_ready: false,
      opl_can_declare_exportable: false,
      opl_can_declare_handoffable: false,
      opl_can_claim_production_soak_complete: false,
      rca_generic_scheduler_owner: false,
      rca_native_helper_generic_envelope_owner: false,
      rca_artifact_lifecycle_owner: false,
      rca_review_repair_transport_owner: false,
      rca_observability_export_owner: false,
    },
  };
}

export {
  buildVisualPackCompilerHandoffProjection,
  RCA_COGNITIVE_KERNEL_ADOPTION,
  RCA_GOLDEN_PATH_PROFILE,
} from './domain-action-adapter-parts/visual-pack-compiler-handoff.js';
