// @ts-nocheck
await import('./product-entry-cases/manifest-and-start-surfaces.test.ts');
await import('./product-entry-cases/manifest-status-preflight-surfaces.test.ts');
await import('./product-entry-cases/evidence-scaleout-surfaces.test.ts');
await import('./product-entry-cases/domain-memory-ref-adapter.test.ts');
await import('./product-entry-cases/manifest-memory-and-attempt-surfaces.test.ts');
await import('./product-entry-cases/memory-skeleton-retirement-proof.test.ts');
await import('./product-entry-cases/runtime-and-sidecar-surfaces.test.ts');
await import('./product-entry-cases/runtime-default-product-entry.test.ts');
await import('./product-entry-cases/sidecar-receipt-and-workspace-proof.test.ts');
await import('./product-entry-cases/substrate-adapter-export.test.ts');
await import('./product-entry-cases/temporal-autonomy-readiness.test.ts');
