import {
  auditDeliverable,
  applyReviewMutation,
  createDeliverable,
  doctorWorkspace,
  getDeliverable,
  getOverlayCatalog,
  getPublicationProjection,
  getReviewState,
  getRun as getGatewayRun,
  getManagedRun as getGatewayManagedRun,
  invokeDomainEntry,
  invokeFederatedProductEntry,
  invokeProductEntry,
  getProductFrontdesk,
  getProductEntryManifest,
  getProductStart,
  getProductPreflight,
  getProductEntrySession,
  buildPerformanceReport,
  superviseManagedRun as superviseGatewayManagedRun,
  intakeSource,
  researchSource,
  prepareSourceAugmentation,
  prepareSourceAugmentationResult,
  writeSourceAugmentationResult,
  executeSourceAugmentation,
  listTopics as listTopicsGateway,
  runtimeWatch,
  runDeliverableRoute,
  runManagedDeliverable,
} from '@redcube/gateway';

import type { GatewayActionMap } from './types.js';

const DEFAULT_GATEWAY_ACTIONS = {
  auditDeliverable,
  applyReviewMutation,
  createDeliverable,
  doctorWorkspace,
  getDeliverable,
  getOverlayCatalog,
  getPublicationProjection,
  getReviewState,
  getRun: getGatewayRun,
  getManagedRun: getGatewayManagedRun,
  invokeDomainEntry,
  invokeFederatedProductEntry,
  invokeProductEntry,
  getProductFrontdesk,
  getProductEntryManifest,
  getProductStart,
  getProductPreflight,
  getProductEntrySession,
  buildPerformanceReport,
  superviseManagedRun: superviseGatewayManagedRun,
  intakeSource,
  researchSource,
  prepareSourceAugmentation,
  prepareSourceAugmentationResult,
  writeSourceAugmentationResult,
  executeSourceAugmentation,
  listTopics: listTopicsGateway,
  runtimeWatch,
  runDeliverableRoute,
  runManagedDeliverable,
};

export function getCliGatewayActions(overrides: GatewayActionMap = {}): typeof DEFAULT_GATEWAY_ACTIONS {
  return {
    ...DEFAULT_GATEWAY_ACTIONS,
    ...overrides,
  };
}
