// @ts-nocheck

export const RCA_VISUAL_PACK_DISCIPLINE_CONTRACT = Object.freeze({
  owner: 'redcube_ai',
  policy_ref: 'agent/quality_gates/visual_pack_discipline.md',
  required_before_artifact_creation: true,
  required_contract_fields: [
    'deliverable_family',
    'route',
    'audience',
    'output_format',
    'canvas_or_aspect_ratio',
    'visual_direction_refs',
    'brand_profile_precedence_refs',
    'material_status_refs',
    'source_material_pass_refs',
    'layout_density_refs',
    'sparse_page_evidence_refs',
    'render_acceptance_refs',
    'review_gate_refs',
    'export_target',
  ],
  brand_profile_precedence: {
    precedence_order: [
      'explicit_delivery_request_brand_material',
      'rca_visual_direction_judgment',
      'workspace_profile_defaults',
      'user_profile_defaults',
      'built_in_route_defaults',
    ],
    approved_task_material_overrides_memory_or_defaults: true,
    generated_or_inferred_profile_can_override_approved_material: false,
    defaults_fill_missing_fields_only: true,
    required_refs: [
      'brand_profile_precedence_refs',
      'approved_brand_material_refs',
      'visual_direction_refs',
      'profile_default_refs',
      'typed_blocker_refs',
    ],
  },
  source_material_pass_transparency: {
    required_item_statuses: ['approved', 'provided_unverified', 'missing', 'out_of_scope'],
    pass_level_evidence_required: true,
    per_material_item_required_fields: [
      'material_id',
      'material_kind',
      'status',
      'pass_ref',
      'source_ref',
      'verified',
      'carried_forward',
      'gap_ref',
      'typed_blocker_ref',
    ],
    missing_or_unverified_required_material_yields: [
      'source_gap_refs',
      'material_gap_refs',
      'typed_blocker',
    ],
    opl_generated_surface_may_summarize_refs_only: true,
  },
  layout_density_sparse_page_evidence: {
    density_contract_required_before_layout: true,
    required_fields: [
      'target_density_band',
      'page_or_frame_inventory_refs',
      'minimum_occupancy_evidence_refs',
      'sparse_page_acceptance_reason_refs',
      'merge_split_decision_refs',
      'blocked_page_refs',
      'screenshot_review_refs',
      'export_gate_refs',
    ],
    sparse_page_can_pass_without_rca_rationale: false,
    provider_completion_can_accept_sparse_page: false,
    schema_completeness_can_accept_sparse_page: false,
    allowed_sparse_page_outcomes: [
      'accepted_with_rca_owned_rationale_refs',
      'repair_target_refs',
      'merge_or_split_decision_refs',
      'typed_blocker',
    ],
  },
  material_status_required: true,
  render_acceptance_required: true,
  mechanical_checks_can_issue_visual_verdict: false,
  provider_completion_can_issue_visual_verdict: false,
  allowed_machine_outputs: [
    'typed_blocker',
    'repair_target_refs',
    'preserved_page_refs',
    'no_regression_refs',
    'helper_proof_refs',
  ],
  forbidden_machine_outputs: [
    'visual_ready_verdict',
    'exportable_verdict',
    'handoffable_verdict',
    'publication_ready_verdict',
    'artifact_body_write_without_owner_receipt',
  ],
});

export const RCA_MARKDOWN_MARP_ROUTE_POLICY = Object.freeze({
  owner: 'redcube_ai',
  policy_ref: 'agent/knowledge/markdown_route_policy.md',
  route_family: 'markdown_marp',
  route_default: false,
  explicit_selection_required: true,
  refs_only: true,
  allowed_route_use: [
    'operator_explicit_markdown_or_marp_request',
    'source_to_slide_text_structuring_refs',
    'intermediate_outline_or_script_packaging_refs',
  ],
  default_visual_route_ref: 'author_image_pages',
  external_runtime_authority_allowed: false,
  provider_completion_can_issue_visual_verdict: false,
});

export const RCA_PACKAGE_DISTRIBUTION_GATE = Object.freeze({
  owner: 'redcube_ai',
  policy_ref: 'agent/quality_gates/package_distribution.md',
  gate_id: 'rca.package_distribution_consistency.v1',
  refs_only: true,
  required_consistency_checks: [
    'source_to_package_required_domain_pack_paths_match',
    'plugin_skill_refs_resolve_to_repo_tracked_pack_paths',
    'package_manifest_does_not_add_runtime_authority',
    'packaging_does_not_change_route_default',
  ],
  package_can_omit_required_domain_pack_refs: false,
  packaging_can_change_route_default: false,
  external_runtime_authority_allowed: false,
});

export const RCA_COGNITIVE_STAGE_PACK_REQUIRED_SECTIONS = Object.freeze([
  'prompt_refs',
  'skill_refs',
  'tool_refs',
  'tool_affordance_boundary',
  'knowledge_refs',
  'quality_gate_refs',
  'strategy_refs',
  'candidate_pool_policy',
  'independent_gate_policy',
  'handoff_policy',
]);

export const RCA_DOMAIN_TOOL_AFFORDANCE_REF = Object.freeze({
  ref: 'agent/tools/domain_affordances.md',
  ref_kind: 'repo_path',
  role: 'domain_tool_affordance_catalog',
  catalog_role: 'available_affordance_catalog_not_workflow_script',
});

const RCA_COGNITIVE_TOOL_AFFORDANCE_BOUNDARY = Object.freeze({
  catalog_role: 'available_affordance_catalog_not_workflow_script',
  capability_refs: [
    { ref: 'source_context_and_visual_brief_reading', ref_kind: 'policy_ref', role: 'capability_boundary' },
    { ref: 'visual_direction_and_candidate_generation_support', ref_kind: 'policy_ref', role: 'capability_boundary' },
    { ref: 'native_ppt_render_screenshot_and_export_helpers', ref_kind: 'policy_ref', role: 'capability_boundary' },
    { ref: 'visual_review_repair_and_artifact_lineage_support', ref_kind: 'policy_ref', role: 'capability_boundary' },
  ],
  permission_scope_refs: [
    { ref: 'repo_context_read', ref_kind: 'policy_ref', role: 'permission_scope_boundary' },
    { ref: 'declared_domain_workspace_read', ref_kind: 'policy_ref', role: 'permission_scope_boundary' },
    { ref: 'bounded_domain_artifact_write_when_owner_authorized', ref_kind: 'policy_ref', role: 'permission_scope_boundary' },
    { ref: 'receipt_or_typed_blocker_return', ref_kind: 'policy_ref', role: 'permission_scope_boundary' },
  ],
  credential_boundary_refs: [
    { ref: 'no_secret_material_in_stage_pack', ref_kind: 'policy_ref', role: 'credential_boundary_boundary' },
    { ref: 'executor_must_request_human_gate_for_missing_credentials', ref_kind: 'policy_ref', role: 'credential_boundary_boundary' },
  ],
  write_scope_refs: [
    { ref: 'visual_workspace_refs_only', ref_kind: 'policy_ref', role: 'write_scope_boundary' },
    { ref: 'deliverable_artifact_mutation_only_with_rca_artifact_authority_receipt', ref_kind: 'policy_ref', role: 'write_scope_boundary' },
  ],
  side_effect_risk_refs: [
    { ref: 'external_network_or_portal_side_effect_requires_explicit_stage_permission', ref_kind: 'policy_ref', role: 'side_effect_risk_boundary' },
    { ref: 'artifact_or_package_mutation_requires_domain_owner_receipt', ref_kind: 'policy_ref', role: 'side_effect_risk_boundary' },
  ],
  forbidden_authority_refs: [
    { ref: 'visual_truth_write_by_opl', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
    { ref: 'review_verdict_without_rca_owner_receipt', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
    { ref: 'export_verdict_without_rca_owner_receipt', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
    { ref: 'artifact_body_write_without_artifact_authority_receipt', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
    { ref: 'visual_memory_body_write_by_opl', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
  ],
  executor_autonomy: {
    executor_can_choose_tools: true,
    executor_can_skip_tools: true,
    executor_can_substitute_tools_within_boundary: true,
    executor_can_choose_order_and_parallelism: true,
    executor_can_request_missing_context_or_human_gate: true,
    tool_catalog_can_prescribe_tool_sequence: false,
    tool_catalog_can_define_cognitive_strategy: false,
    tool_catalog_can_override_stage_goal: false,
    tool_catalog_can_authorize_forbidden_write: false,
  },
  policy:
    'redcube_ai tool refs declare available affordances and safety boundaries only; they do not prescribe executor order, stage strategy, stage goal, or forbidden writes.',
});

export const RCA_COGNITIVE_KERNEL_ADOPTION = Object.freeze({
  surface_kind: 'opl_cognitive_kernel_adoption',
  version: 'cognitive-kernel-adoption.v1',
  owner: 'redcube-ai',
  domain_id: 'redcube_ai',
  state: 'advisory_current_contract',
  purpose:
    'RedCube AI declares repo-owned stage-internal cognitive-kernel refs, tool affordances, and independent gate boundaries for OPL-hosted Foundry Agent execution.',
  machine_boundary:
    'This contract is advisory/current adoption metadata. Domain truth, artifact bodies, quality verdicts, owner receipts, typed blockers, human gates, and export authority remain domain-owned; OPL owns transport, attempts, refs, receipts projection, and generated/hosted surfaces only.',
  framework_contract_ref: 'one-person-lab/contracts/opl-framework/cognitive-computation-kernel.json',
  pack_compiler_input_ref: 'contracts/pack_compiler_input.json',
  stage_control_plane_ref: 'contracts/stage_control_plane.json',
  golden_path_profile_ref: 'contracts/golden_path_profile.json',
  domain_affordance_catalog_ref: 'agent/tools/domain_affordances.md',
  stage_pack_required_sections: [...RCA_COGNITIVE_STAGE_PACK_REQUIRED_SECTIONS],
  tool_affordance_boundary: { ...RCA_COGNITIVE_TOOL_AFFORDANCE_BOUNDARY },
  authority_boundary: {
    domain_repo_declares_strategy_not_generic_runtime: true,
    domain_repo_can_claim_generated_surface_owner: false,
    opl_can_write_domain_truth: false,
    opl_can_read_domain_body: false,
    opl_can_create_owner_receipt: false,
    opl_can_create_typed_blocker: false,
    opl_can_claim_domain_ready: false,
    opl_can_claim_artifact_ready: false,
    strategy_refs_completeness_is_launch_hard_gate: false,
    independent_gate_receipt_required_for_quality_progression: true,
    same_attempt_self_review_can_close_quality_gate: false,
  },
  adoption_policy: {
    advisory_not_launch_hard_gate: true,
    tool_catalog_is_not_workflow_script: true,
    route_is_not_stage_strategy: true,
    stage_attempt_is_required_for_execution: true,
    candidate_pool_is_stage_internal_artifact: true,
    meta_review_updates_are_proposals_until_owner_acceptance: true,
  },
  stage_strategy_refs: [
    'visual_brief_goal_and_constraints',
    'image_first_candidate_generation',
    'screenshot_grounded_reflection',
    'visual_candidate_comparative_selection',
    'export_independent_quality_gate',
  ],
  stage_artifact_refs: [
    'source_readiness_manifest_ref',
    'communication_strategy_ref',
    'visual_direction_ref',
    'visual_artifact_candidate_ref',
    'review_revision_packet_ref',
    'package_handoff_ref',
  ],
});

export const RCA_GOLDEN_PATH_PROFILE = Object.freeze({
  surface_kind: 'opl_golden_path_profile',
  schema_version: 'golden-path-profile.v1',
  profile_id: 'redcube-ai.golden-path',
  domain: 'redcube_ai',
  owner: 'redcube-ai',
  domain_id: 'redcube_ai',
  state: 'advisory_current_contract',
  profile_role: 'visual_foundry_agent_golden_path_profile',
  purpose:
    'RedCube AI golden path for OPL-hosted Foundry Agent execution under current_owner_delta and stage-internal cognitive-kernel boundaries.',
  machine_boundary:
    'This profile describes the intended happy path and stop-loss contract. It does not declare domain ready, App release ready, or production ready.',
  default_executor: 'codex_cli',
  default_outer_loop: 'current_owner_delta',
  stage_attempt_strategy: 'cognitive_kernel_stage_internal',
  domain_affordance_catalog_ref: 'agent/tools/domain_affordances.md',
  cognitive_kernel_adoption_ref: 'contracts/cognitive_kernel_adoption.json',
  stage_control_plane_ref: 'contracts/stage_control_plane.json',
  pack_compiler_input_ref: 'contracts/pack_compiler_input.json',
  golden_path_steps: [
    'hydrate_current_owner_delta',
    'run_stage_attempt_with_declared_prompt_skill_tool_knowledge_refs',
    'generate_candidate_pool_or_artifact_delta_inside_domain_workspace',
    'ground_review_in_source_refs_and_tool_evidence',
    'select_or_revise_candidate_with_lineage',
    'record_owner_receipt_typed_blocker_human_gate_or_route_back_ref',
    'project_refs_only_status_to_opl_and_app',
  ],
  required_closeout_refs: [
    'stage_artifact_unit_ref',
    'owner_receipt_ref_or_typed_blocker_ref',
    'independent_gate_receipt_ref_or_route_back_ref',
    'current_owner_delta_ref',
  ],
  stop_loss_policy: {
    missing_domain_truth: 'return_typed_blocker_ref',
    missing_credential_or_human_authority: 'return_human_gate_ref',
    failed_independent_gate: 'return_route_back_ref_or_typed_blocker_ref',
    forbidden_write_requested: 'return_typed_blocker_ref',
  },
  forbidden_claims: [
    'descriptor_ready_means_domain_ready',
    'provider_completion_means_quality_ready',
    'generated_surface_ready_means_export_ready',
    'same_attempt_self_review_closes_quality_gate',
    'tool_catalog_prescribes_executor_sequence',
  ],
  ordinary_path: {
    path_id: 'redcube-ai_ordinary_default',
    path_role: 'ordinary_default',
    stage_refs: [
      'source_intake',
    ],
  },
  explicit_variants: [],
  default_surface_policy: {
    ordinary_route_count: 1,
    variants_hidden_by_default: true,
    raw_evidence_hidden_by_default: true,
  },
  authority_boundary: {
    ordinary_path_count_must_be_one: true,
    variant_can_be_default_without_explicit_selection: false,
    opl_can_write_domain_truth: false,
    opl_can_authorize_domain_ready: false,
    opl_can_authorize_quality_verdict: false,
    opl_can_mutate_artifact_body: false,
  },
});

export const RCA_REQUIRED_DOMAIN_PACK_PATHS = Object.freeze([
  'agent/prompts/source_intake.md',
  'agent/prompts/communication_strategy.md',
  'agent/prompts/visual_direction.md',
  'agent/prompts/artifact_creation.md',
  'agent/prompts/review_and_revision.md',
  'agent/prompts/package_and_handoff.md',
  'agent/stages/source_intake.md',
  'agent/stages/communication_strategy.md',
  'agent/stages/visual_direction.md',
  'agent/stages/artifact_creation.md',
  'agent/stages/review_and_revision.md',
  'agent/stages/package_and_handoff.md',
  'agent/skills/visual_deliverable_authoring.md',
  'agent/skills/native_helper_policy.md',
  'agent/skills/visual_memory_policy.md',
  'agent/professional_skills/rca-ppt-story-architect/SKILL.md',
  'agent/professional_skills/rca-ppt-visual-director/SKILL.md',
  'agent/professional_skills/rca-ppt-page-author/SKILL.md',
  'agent/professional_skills/rca-ppt-reviewer/SKILL.md',
  'agent/professional_skills/rca-native-ppt-designer/SKILL.md',
  'agent/professional_skills/rca-template-profiler/SKILL.md',
  'agent/quality_gates/visual_authority_boundaries.md',
  'agent/quality_gates/source_and_truth.md',
  'agent/quality_gates/communication_and_direction.md',
  'agent/quality_gates/visual_pack_discipline.md',
  'agent/quality_gates/package_distribution.md',
  'agent/quality_gates/artifact_authority.md',
  'agent/quality_gates/review_export_memory.md',
  'agent/knowledge/visual_truth_boundaries.md',
  'agent/knowledge/communication_visual_direction.md',
  'agent/knowledge/artifact_and_export_authority.md',
  'agent/knowledge/review_export_memory.md',
  'agent/knowledge/markdown_route_policy.md',
  'agent/knowledge/owner_receipt_policy.md',
  'agent/tools/domain_affordances.md',
]);

export const OPL_GENERATED_SURFACE_EXIT_GATE = Object.freeze({
  gate_id: 'rca.generated_surface_bridge_exit.v1',
  owner: 'one-person-lab',
  consumer: 'redcube_ai',
  current_rca_status: 'opl_generated_surface_consumed_domain_handlers_only',
  required_before_retiring_repo_local_wrappers: [
    'domain_authority_refs_preserved',
    'no_regression_proof_recorded',
  ],
  repo_local_allowed_roles_before_exit: [
    'domain_handler_target',
    'direct_domain_entry',
    'direct_protocol_adapter',
    'refs_only_adapter',
  ],
  repo_local_forbidden_roles: [
    'unified_metadata_owner',
    'generic_dispatch_owner',
    'generic_session_shell_owner',
    'generic_workbench_owner',
    'generated_surface_owner',
  ],
  after_exit_rca_allowed_surfaces: [
    'declarative_visual_pack_input',
    'domain_handler_targets',
    'minimal_authority_functions',
    'refs_only_locator_projection',
  ],
  rca_can_own_generated_surface: false,
  rca_can_own_generic_session_shell: false,
  rca_can_own_generic_workbench: false,
  declares_generated_surface_descriptor_consumed: true,
  declares_generated_surface_consumption_complete: false,
  declares_production_consumption_complete: false,
  production_consumption_scope: 'descriptor_and_contract_consumed_not_production_default_caller_live_soak',
  declares_visual_stage_long_soak_complete: false,
  false_ready_guard: {
    descriptor_consumption_can_claim_generated_surface_completion: false,
    descriptor_consumption_can_claim_production_consumption: false,
    descriptor_consumption_can_claim_default_caller_cutover: false,
    descriptor_consumption_can_claim_app_operator_consumption: false,
    descriptor_consumption_can_claim_visual_stage_long_soak: false,
    descriptor_consumption_can_claim_domain_ready: false,
    descriptor_consumption_can_claim_artifact_ready: false,
  },
  remaining_blocker_ids: [],
  remaining_evidence_gate_ids: [
    'real_artifact_producing_domain_owner_receipt',
    'opl_hosted_controlled_visual_stage_long_soak',
    'real_memory_lifecycle_receipt_instances',
    'cross_family_repeated_no_regression_evidence',
  ],
});

export const RCA_COGNITIVE_STAGE_PACK_CONTRACT = Object.freeze({
  owner: 'redcube_ai',
  consumer: 'opl_pack_compiler',
  contract_ref: 'contracts/opl-framework/cognitive-computation-kernel.json',
  stage_control_plane_ref: 'contracts/stage_control_plane.json',
  cognitive_kernel_adoption_ref: 'contracts/cognitive_kernel_adoption.json',
  golden_path_profile_ref: 'contracts/golden_path_profile.json',
  domain_affordance_catalog_ref: { ...RCA_DOMAIN_TOOL_AFFORDANCE_REF },
  refs_only: true,
  user_visible_flow_changed: false,
  launch_hard_gate: false,
  required_stage_sections: [...RCA_COGNITIVE_STAGE_PACK_REQUIRED_SECTIONS],
  stage_strategy_owner: 'selected_codex_executor_with_rca_owned_gates',
  tool_affordance_policy: 'available_affordance_catalog_not_workflow_script',
  tool_affordance_boundary: { ...RCA_COGNITIVE_TOOL_AFFORDANCE_BOUNDARY },
  candidate_pool_policy: 'stage_internal_refs_with_lineage_no_user_flow_expansion',
  independent_gate_policy: 'execution_and_review_attempts_must_be_separable_for_quality_progression',
  authority_boundary: {
    opl_can_write_visual_truth: false,
    opl_can_write_artifact_body: false,
    opl_can_authorize_review_export_verdict: false,
    opl_can_sign_owner_receipt: false,
    provider_completion_is_visual_ready: false,
    same_attempt_self_review_can_close_quality_gate: false,
  },
});
