// @ts-nocheck

export const OPL_LEDGER_ARTIFACT_REGISTRATION_CONTRACT_REF = 'contracts/opl_ledger_artifact_registration.json';
export const OPL_LEDGER_ARTIFACT_REGISTRATION_POINTER = '/opl_ledger_artifact_registration';

export function buildOplLedgerArtifactRegistrationContract() {
  return {
    surface_kind: 'opl_ledger_artifact_registration_contract',
    contract_id: 'rca.opl_ledger_artifact_registration.v1',
    version: 'v1',
    domain_id: 'redcube_ai',
    domain_agent_id: 'rca',
    owner: 'redcube_ai',
    ledger_owner: 'one-person-lab/OPL Ledger',
    registration_mode: 'refs_only',
    refs_only: true,
    not_mas_per_figure_provenance_bundle: true,
    summary: (
      'RCA exposes long-lived visual deliverable artifact registration envelopes for OPL Ledger. '
      + 'The ledger stores refs, hashes, index refs, review refs, and receipt refs only.'
    ),
    artifact_classes: [
      {
        class_id: 'visual_page_image_ref',
        allowed_artifact_kinds: ['png_page', 'review_capture'],
        registration_scope: 'rendered_visual_page_or_review_capture_ref',
      },
      {
        class_id: 'visual_export_ref',
        allowed_artifact_kinds: ['pptx_export', 'pdf_export', 'export_bundle'],
        registration_scope: 'deliverable_export_or_handoff_bundle_ref',
      },
      {
        class_id: 'stage_manifest_ref',
        allowed_artifact_kinds: ['stage_folder_manifest', 'prompt_manifest', 'style_manifest'],
        registration_scope: 'stage_or_prompt_manifest_ref_without_manifest_body',
      },
    ],
    registration_payload_contract: {
      required_fields: [
        'domain_id',
        'artifact_class',
        'artifact_kind',
        'artifact_ref',
        'sha256',
        'artifact_index_ref',
        'review_ref',
        'receipt_ref',
      ],
      optional_fields: [
        'topic_id',
        'deliverable_id',
        'run_id',
        'stage_id',
        'source_locator_ref',
        'ledger_registration_ref',
      ],
      hash_algorithm: 'sha256',
      hash_scope: 'referenced_artifact_or_manifest_bytes_external_to_repo',
      payload_body_allowed: false,
    },
    allowed_ref_kinds: [
      'opl_stage_folder_output',
      'opl_stage_folder_manifest',
      'workspace_runtime_artifact',
      'product_entry_session_ref',
      'stage_run_artifact_ref',
      'rca_review_ref',
      'rca_receipt_ref',
      'opl_ledger_registration_ref',
    ],
    required_registration_refs: [
      'artifact_ref',
      'sha256',
      'artifact_index_ref',
      'review_ref',
      'receipt_ref',
    ],
    forbidden_payload_fields: [
      'artifact_body',
      'artifact_blob',
      'png_bytes',
      'pptx_bytes',
      'pdf_bytes',
      'visual_truth_body',
      'visual_memory_body',
      'review_verdict',
      'export_verdict',
      'owner_receipt',
      'owner_receipt_body',
      'typed_blocker',
      'typed_blocker_body',
      'runtime_queue_state',
      'stage_attempt_body',
      'provider_attempt_body',
    ],
    opl_ledger_command_refs: [
      {
        command_ref_id: 'opl-ledger:artifact-register-ref-only.v1',
        owner: 'one-person-lab/OPL Ledger',
        command_template: 'opl ledger artifact register --domain redcube_ai --contract contracts/opl_ledger_artifact_registration.json --artifact-ref <ref> --sha256 <hash> --index-ref <ref> --review-ref <ref> --receipt-ref <ref>',
        effect: 'ledger_registration_write',
        rca_role: 'produce_refs_only_registration_envelope',
      },
      {
        command_ref_id: 'opl-ledger:artifact-readback.v1',
        owner: 'one-person-lab/OPL Ledger',
        command_template: 'opl ledger artifact read --registration-ref <ledger-registration-ref> --format json',
        effect: 'read_only',
        rca_role: 'consume_registration_ref_only',
      },
    ],
    projection_surfaces: {
      product_entry_manifest_ref: OPL_LEDGER_ARTIFACT_REGISTRATION_POINTER,
      domain_handler_export_ref: '/mapped_surfaces/opl_ledger_artifact_registration',
      artifact_inventory_supporting_file_id: 'opl_ledger_artifact_registration',
    },
    owner_boundary: {
      rca_role: 'visual_deliverable_ref_producer',
      opl_ledger_role: 'refs_hash_index_review_receipt_registration_ledger',
      rca_owns_visual_truth: true,
      rca_owns_review_export_verdict: true,
      rca_owns_artifact_authority: true,
      rca_can_write_artifact_body_through_ledger: false,
      rca_can_issue_ledger_owner_receipt: false,
      opl_ledger_can_store_artifact_body: false,
      opl_ledger_can_issue_rca_owner_receipt: false,
      opl_ledger_can_create_rca_typed_blocker: false,
      opl_ledger_can_authorize_review_export_verdict: false,
      opl_ledger_can_enqueue_runtime_work: false,
    },
    repository_boundary: {
      repo_tracks_registration_contract: true,
      repo_tracks_registration_instances: false,
      repo_tracks_artifact_body: false,
      repo_tracks_owner_receipt_body: false,
      repo_tracks_typed_blocker_body: false,
      repo_tracks_runtime_queue_state: false,
    },
    forbidden_claims: [
      'ledger_registration_is_visual_ready',
      'ledger_registration_is_exportable',
      'ledger_registration_is_handoffable',
      'ledger_registration_is_owner_receipt',
      'ledger_registration_is_review_or_export_verdict',
      'ledger_registration_is_runtime_queue_progress',
      'refs_only_registration_is_mas_per_figure_provenance_bundle',
    ],
  };
}
