// @ts-nocheck

export const SOURCE_THINNING_TAIL_GATE = Object.freeze({
  gate_id: 'rca.source_morphology.default_caller_tail_thinning.v1',
  state: 'non_live_functional_structure_gate_landed',
  gate_role:
    'classify_retained_repo_local_tails_before_default_caller_cutover_without_authorizing_delete_or_readiness',
  applies_to_surface_ids: [],
  current_non_tail_surface_ids: [
    'product_entry_continuity_refs_adapter',
    'domain_action_adapter_guarded_actions',
    'product_entry_manifest_projection',
    'deliverable_route_attempt_shell',
    'repo_shell_verification_wrappers',
  ],
  retained_current_refs_only_boundary_ids: [
    'runtime_watch_projection',
    'operator_evidence_stability_projection',
    'executor_runtime_route_run_records',
  ],
  allowed_current_roles: [
    'refs_only_read_model',
    'retained_current_refs_only_boundary',
    'domain_handler_target',
    'service_safe_domain_entry',
    'minimal_visual_authority_function',
    'visual_native_helper_implementation',
    'repo_native_verification_wrapper',
    'tombstone_or_provenance',
  ],
  required_before_physical_delete_or_further_thin: [
    'opl_generated_default_caller_parity',
    'no_active_repo_local_default_caller',
    'rca_owner_receipt_or_typed_blocker_roundtrip',
    'no_forbidden_write_proof',
    'current_role_guard_no_alias_proof',
    'compressed_history_index_pointer',
  ],
  false_ready_guard: {
    source_classification_can_claim_physical_delete_authorized: false,
    source_classification_can_claim_default_caller_cutover_complete: false,
    source_classification_can_claim_visual_ready: false,
    source_classification_can_claim_exportable: false,
    source_classification_can_claim_handoffable: false,
    source_classification_can_claim_domain_ready: false,
    source_classification_can_claim_production_ready: false,
  },
  current_role_guard: {
    runtimeWatch_can_return_to_domain_action_adapter_default_dispatch: false,
    domain_action_adapter_can_become_generic_dispatch_owner: false,
    domain_action_adapter_can_become_generated_wrapper_owner: false,
    product_session_can_become_generic_session_shell_owner: false,
    operator_projection_can_become_generic_workbench_owner: false,
    route_run_records_can_become_attempt_ledger_owner: false,
    shell_wrappers_can_become_runtime_owner: false,
    compatibility_alias_or_facade_allowed: false,
  },
  active_source_resurrection_scan_policy: {
    policy_id: 'rca.source_morphology.active_source_no_resurrection_scan.v1',
    scan_roots: [
      'agent',
      'apps',
      'packages',
      'contracts',
      'plugins',
      'scripts',
      'tools',
      'python',
    ],
    helper_ref: 'tests/helpers/rca-retired-surface-guard.ts#ACTIVE_PRIVATE_PLATFORM_RESURRECTION_CLAIM_PATTERNS',
    test_ref: 'tests/rca-legacy-name-allowance.test.ts#RCA source-morphology tail thinning gate prevents runtimeWatch and domain_action_adapter resurrection',
    forbidden_true_claim_keys: [
      'runtimeWatch_can_return_to_domain_action_adapter_default_dispatch',
      'domain_action_adapter_can_become_generic_dispatch_owner',
      'domain_action_adapter_can_become_generated_wrapper_owner',
      'default_runtime_watch_dispatch_allowed',
      'generic_dispatch_owner_allowed',
      'generic_domain_action_adapter_owner_allowed',
      'generic_generated_wrapper_owner_allowed',
      'generic_session_runtime_owner_allowed',
      'generic_workbench_owner_allowed',
      'generic_runtime_owner_allowed',
    ],
    fail_closed_conditions: [
      'active_source_claims_runtimeWatch_default_dispatch',
      'active_source_claims_generic_domain_action_adapter_owner',
      'active_source_claims_generated_wrapper_owner',
      'active_source_claims_generic_runtime_or_workbench_owner',
      'compatibility_alias_or_facade_resurrection_claim',
    ],
    authority_boundary: {
      scan_can_authorize_physical_delete: false,
      scan_can_claim_default_caller_cutover: false,
      scan_can_claim_visual_ready: false,
      scan_can_claim_domain_ready: false,
      scan_can_claim_production_ready: false,
    },
  },
  retirement_readback_cleanup_guard: {
    guard_id: 'rca.source_morphology.retirement_readback_cleanup_guard.v1',
    state: 'readback_guard_available_physical_delete_not_authorized',
    readback_surface_ref: 'contracts/physical_source_morphology_policy.json#/default_caller_tail_thinning_gate',
    json_transport_guard: {
      guard_id: 'rca.source_morphology.retirement_readback_json_transport_guard.v1',
      state: 'complete_parseable_json_required',
      command_refs: [
        'npm run private-platform:readback',
        'npm run test:private-platform:strict',
      ],
      required_properties: [
        'stdout_must_flush_before_exit',
        'direct_readback_json_must_parse',
        'strict_gate_payload_must_equal_direct_readback_payload',
        'large_readback_over_64kb_must_not_truncate',
      ],
      false_ready_guard: {
        parseable_json_can_claim_physical_delete_authorized: false,
        parseable_json_can_claim_default_caller_cutover_complete: false,
        parseable_json_can_claim_visual_ready: false,
        parseable_json_can_claim_domain_ready: false,
        parseable_json_can_claim_production_ready: false,
      },
    },
    allowed_readback_outputs: [
      'active_surface_classification',
      'current_non_tail_surface',
      'missing_evidence_worklist',
      'owner_delta_route',
      'retained_current_refs_only_boundary',
      'typed_blocker_ref_shape',
      'current_role_guard',
    ],
    forbidden_readback_outputs: [
      'physical_delete_operation',
      'owner_receipt_signature',
      'typed_blocker_instance_creation',
      'visual_ready_or_exportable_claim',
      'production_ready_claim',
      'app_or_default_caller_cutover_claim',
    ],
    required_before_cleanup_apply: [
      'opl_generated_default_caller_parity',
      'no_active_repo_local_default_caller',
      'rca_owner_receipt_or_typed_blocker_roundtrip',
      'no_forbidden_write_proof',
      'current_role_guard_no_alias_proof',
      'compressed_history_index_pointer',
      'owner_receipt://redcube_ai/physical_delete_or_tombstone_authorization',
    ],
    false_ready_claim_guard_keys: [
      'retirement_readback_cleanup_complete',
      'retirement_readback_guard_satisfied',
      'cleanup_readback_physical_delete_authorized',
      'claims_cleanup_readback_authorizes_delete',
      'claims_retirement_cleanup_applied',
    ],
    claims: {
      claims_retirement_cleanup_complete: false,
      claims_physical_delete_authorized: false,
      claims_owner_receipt_signed: false,
      claims_typed_blocker_created: false,
      claims_visual_ready: false,
      claims_exportable: false,
      claims_handoffable: false,
      claims_domain_ready: false,
      claims_production_ready: false,
    },
    authority_boundary: {
      guard_can_identify_cleanup_candidates: true,
      guard_can_route_owner_delta: true,
      guard_can_authorize_physical_delete: false,
      guard_can_sign_owner_receipt: false,
      guard_can_create_typed_blocker: false,
      guard_can_claim_default_caller_cutover: false,
      guard_can_claim_app_or_live_readiness: false,
      guard_can_claim_visual_or_export_readiness: false,
    },
  },
});
