// @ts-nocheck

export {
  buildRcaMinimalAuthoritySurfaceContracts,
  buildRcaMinimalAuthoritySurfaceTaxonomy,
} from './visual-pack-compiler-handoff/authority-surfaces.js';
export {
  RCA_COGNITIVE_KERNEL_ADOPTION,
  RCA_GOLDEN_PATH_PROFILE,
  OPL_GENERATED_SURFACE_EXIT_GATE,
} from './visual-pack-compiler-handoff/visual-pack-contracts.js';

import {
  RCA_MINIMAL_AUTHORITY_FUNCTIONS,
  buildRcaMinimalAuthoritySurfaceContracts,
  buildRcaMinimalAuthoritySurfaceTaxonomy,
} from './visual-pack-compiler-handoff/authority-surfaces.js';
import {
  OPL_GENERATED_DESCRIPTOR_SCOPE,
  OPL_GENERATED_SURFACE_TARGETS,
  RCA_REPO_LOCAL_HANDLER_TARGETS,
} from './visual-pack-compiler-handoff/generated-surfaces.js';
import {
  RCA_COGNITIVE_STAGE_PACK_CONTRACT,
  RCA_MARKDOWN_MARP_ROUTE_POLICY,
  OPL_GENERATED_SURFACE_EXIT_GATE,
  RCA_PACKAGE_DISTRIBUTION_GATE,
  RCA_REQUIRED_DOMAIN_PACK_PATHS,
  RCA_VISUAL_PACK_DISCIPLINE_CONTRACT,
} from './visual-pack-compiler-handoff/visual-pack-contracts.js';

export function buildVisualPackCompilerHandoffProjection() {
  return {
    surface_kind: 'visual_pack_compiler_handoff',
    projection_id: 'rca.visual_pack_compiler_handoff.v1',
    ref: '/visual_pack_compiler_handoff',
    visual_pack_compiler_input_ref: '/visual_pack_compiler_handoff/declarative_visual_pack_input',
    generated_surface_handoff_ref: '/visual_pack_compiler_handoff/generated_surface_handoff',
    contract_ref: 'rca.visual_pack_compiler_handoff.v1',
    owner: 'redcube_ai',
    consumer: 'opl_pack_compiler',
    status: 'machine_handoff_surface_landed',
    projection_mode: 'declarative_visual_pack_input_with_generated_surface_handoff',
    read_only: true,
    refs_only: true,
    declares_production_soak_complete: false,
    visual_pack_discipline: {
      surface_kind: 'visual_pack_discipline_refs',
      discipline_id: 'rca.executable_visual_pack_discipline.v1',
      owner: 'redcube_ai',
      consumer: 'opl_pack_compiler',
      status: 'refs_only_projection_landed',
      read_only: true,
      refs_only: true,
      inspiration_scope: 'external_document_system_lessons_adapted_to_rca_refs_only',
      canonical_pack_root: 'agent/',
      pack_compiler_input_ref: 'contracts/pack_compiler_input.json',
      stage_prompt_refs: [
        'agent/prompts/source_intake.md',
        'agent/prompts/communication_strategy.md',
        'agent/prompts/visual_direction.md',
        'agent/prompts/artifact_creation.md',
        'agent/prompts/review_and_revision.md',
        'agent/prompts/package_and_handoff.md',
      ],
      stage_descriptor_refs: [
        'agent/stages/source_intake.md',
        'agent/stages/communication_strategy.md',
        'agent/stages/visual_direction.md',
        'agent/stages/artifact_creation.md',
        'agent/stages/review_and_revision.md',
        'agent/stages/package_and_handoff.md',
      ],
      quality_gate_refs: [
        'agent/quality_gates/visual_authority_boundaries.md',
        'agent/quality_gates/source_and_truth.md',
        'agent/quality_gates/communication_and_direction.md',
        'agent/quality_gates/visual_pack_discipline.md',
        'agent/quality_gates/artifact_authority.md',
        'agent/quality_gates/review_export_memory.md',
        'agent/quality_gates/screenshot_review.md',
      ],
      authority_boundary: {
        opl_can_discover_pack_refs: true,
        opl_can_compile_generated_surfaces_from_refs: true,
        opl_can_write_rca_visual_truth: false,
        opl_can_write_artifact_body: false,
        opl_can_write_visual_memory_body: false,
        opl_can_authorize_review_export_verdict: false,
        provider_completion_is_visual_ready: false,
      },
      forbidden_outputs: [
        'visual_truth_body',
        'artifact_body',
        'visual_memory_body',
        'review_export_verdict_body',
        'provider_completion_visual_ready_claim',
      ],
    },
    markdown_marp_route_policy: {
      surface_kind: 'markdown_marp_optional_route_policy_refs',
      route_policy_id: 'rca.markdown_marp_optional_route_policy.v1',
      owner: 'redcube_ai',
      consumer: 'opl_pack_compiler',
      status: 'optional_refs_only_policy_landed',
      read_only: true,
      refs_only: true,
      route_family: RCA_MARKDOWN_MARP_ROUTE_POLICY.route_family,
      route_default: RCA_MARKDOWN_MARP_ROUTE_POLICY.route_default,
      explicit_selection_required: RCA_MARKDOWN_MARP_ROUTE_POLICY.explicit_selection_required,
      policy_ref: RCA_MARKDOWN_MARP_ROUTE_POLICY.policy_ref,
      allowed_route_use: [...RCA_MARKDOWN_MARP_ROUTE_POLICY.allowed_route_use],
      default_visual_route_ref: RCA_MARKDOWN_MARP_ROUTE_POLICY.default_visual_route_ref,
      route_material_refs: [
        'agent/knowledge/markdown_route_policy.md',
        'agent/quality_gates/visual_pack_discipline.md',
        'agent/quality_gates/review_export_memory.md',
      ],
      authority_boundary: {
        redcube_ai_owns_route_truth: true,
        opl_can_discover_route_refs: true,
        opl_can_compile_optional_route_surface_from_refs: true,
        external_runtime_authority_allowed: RCA_MARKDOWN_MARP_ROUTE_POLICY.external_runtime_authority_allowed,
        provider_completion_is_visual_ready: RCA_MARKDOWN_MARP_ROUTE_POLICY.provider_completion_can_issue_visual_verdict,
        markdown_marp_route_can_replace_default: false,
      },
      forbidden_outputs: [
        'default_route_replacement',
        'external_runtime_authority',
        'visual_ready_verdict',
        'exportable_verdict',
        'artifact_body_write_without_owner_receipt',
      ],
    },
    package_distribution_gate: {
      surface_kind: 'package_distribution_consistency_gate_refs',
      gate_id: RCA_PACKAGE_DISTRIBUTION_GATE.gate_id,
      owner: 'redcube_ai',
      consumer: 'opl_pack_compiler',
      status: 'source_to_package_consistency_gate_landed',
      read_only: true,
      refs_only: true,
      policy_ref: RCA_PACKAGE_DISTRIBUTION_GATE.policy_ref,
      required_domain_pack_paths: [...RCA_REQUIRED_DOMAIN_PACK_PATHS],
      required_consistency_checks: [...RCA_PACKAGE_DISTRIBUTION_GATE.required_consistency_checks],
      authority_boundary: {
        package_can_omit_required_domain_pack_refs: RCA_PACKAGE_DISTRIBUTION_GATE.package_can_omit_required_domain_pack_refs,
        packaging_can_change_route_default: RCA_PACKAGE_DISTRIBUTION_GATE.packaging_can_change_route_default,
        external_runtime_authority_allowed: RCA_PACKAGE_DISTRIBUTION_GATE.external_runtime_authority_allowed,
        packaging_can_issue_visual_verdict: false,
      },
      forbidden_outputs: [
        'package_manifest_runtime_authority',
        'missing_required_domain_pack_ref',
        'route_default_mutation',
        'visual_ready_verdict',
      ],
    },
    render_review_gate_contract: {
      surface_kind: 'render_review_gate_contract_refs',
      contract_id: 'rca.render_review_gate_contract.v1',
      owner: 'redcube_ai',
      consumer: 'opl_generated_surface',
      status: 'refs_only_projection_landed',
      read_only: true,
      refs_only: true,
      review_export_authority_surface_id: 'review_export_verdict',
      render_gate_refs: [
        'agent/quality_gates/artifact_authority.md',
        'agent/quality_gates/screenshot_review.md',
      ],
      review_gate_refs: [
        'agent/quality_gates/review_export_memory.md',
        '/review_state',
        '/publication_projection',
      ],
      required_stage_refs: [
        'visual_director_review',
        'screenshot_review',
        'export_pptx',
      ],
      required_return_shapes: [
        'verdict_refs',
        'typed_blocker',
        'owner_receipt_refs',
      ],
      authority_boundary: {
        redcube_ai_owns_review_export_verdict: true,
        opl_can_discover_gate_refs: true,
        opl_can_store_gate_refs: true,
        opl_can_authorize_review_export_verdict: false,
        opl_can_declare_visual_ready: false,
        opl_can_declare_exportable: false,
        provider_completion_is_visual_ready: false,
      },
      forbidden_outputs: [
        'visual_truth_write',
        'artifact_blob_write_without_owner_receipt',
        'memory_body_write',
        'review_export_verdict_body',
        'mechanical_ready_verdict',
        'programmatic_ready_verdict',
        'provider_completion_visual_ready_claim',
      ],
    },
    declarative_visual_pack_input: {
      input_id: 'rca.declarative_visual_pack_input.v1',
      owner: 'redcube_ai',
      compiler_owner: 'opl',
      input_mode: 'domain_descriptor_refs_only',
      generated_surface_mode: 'opl_generated_surface_consumed_domain_handlers_only',
      source_refs: [
        { source_id: 'domain_descriptor', ref: '/standard_domain_agent_skeleton' },
        { source_id: 'deliverable_family_graph', ref: '/family_stage_control_plane' },
        { source_id: 'action_metadata', ref: '/family_action_catalog' },
        { source_id: 'visual_transition_spec', ref: '/visual_transition_spec' },
        { source_id: 'review_export_policies', refs: ['/review_state', '/publication_projection'] },
        { source_id: 'artifact_locator_policy', ref: '/artifact_locator_contract' },
        { source_id: 'memory_locator_policy', ref: '/domain_memory_descriptor_locator' },
        { source_id: 'receipt_schema', ref: '/domain_owner_receipt_contract' },
        { source_id: 'lifecycle_receipt_schema', ref: '/lifecycle_guarded_apply_proof' },
        { source_id: 'native_helper_catalog', ref: 'contracts/runtime-program/python-native-helper-catalog.json' },
        { source_id: 'visual_pack_discipline_policy', ref: RCA_VISUAL_PACK_DISCIPLINE_CONTRACT.policy_ref },
        { source_id: 'markdown_marp_route_policy', ref: RCA_MARKDOWN_MARP_ROUTE_POLICY.policy_ref },
        { source_id: 'package_distribution_policy', ref: RCA_PACKAGE_DISTRIBUTION_GATE.policy_ref },
        { source_id: 'cognitive_kernel_adoption', ref: 'contracts/cognitive_kernel_adoption.json' },
        { source_id: 'golden_path_profile', ref: 'contracts/golden_path_profile.json' },
        { source_id: 'domain_tool_affordance_catalog', ref: 'agent/tools/domain_affordances.md' },
        { source_id: 'professional_specialist_skill_pack', ref: 'agent/professional_skills/' },
      ],
      required_input_families: [
        'domain_descriptor',
        'deliverable_family_graph',
        'stage_action_metadata',
        'source_readiness_policy',
        'visual_transition_spec',
        'review_export_policy',
        'artifact_locator_policy',
        'memory_locator_policy',
        'receipt_schema',
        'authority_function_manifest',
        'oracle_fixtures',
        'tool_affordance_catalog',
        'cognitive_kernel_adoption_contract',
        'golden_path_profile',
      ],
      required_domain_pack_paths: [...RCA_REQUIRED_DOMAIN_PACK_PATHS],
      authority_function_manifest: {
        owner: 'redcube_ai',
        retained_authority_surface_ids: [...RCA_MINIMAL_AUTHORITY_FUNCTIONS],
        retained_authority_surface_count: RCA_MINIMAL_AUTHORITY_FUNCTIONS.length,
        authority_surface_taxonomy: buildRcaMinimalAuthoritySurfaceTaxonomy(),
        retained_surface_contracts: buildRcaMinimalAuthoritySurfaceContracts(),
        all_other_generic_shells_generated_by_opl: true,
      },
      generated_descriptor_contract: {
        owner: 'opl',
        unified_metadata_owner: 'one-person-lab',
        descriptor_scope: [...OPL_GENERATED_DESCRIPTOR_SCOPE],
        repo_local_handler_targets: [...RCA_REPO_LOCAL_HANDLER_TARGETS],
        repo_local_handlers_are_generated_surface_owners: false,
        redcube_cli_role: 'domain_handler_target_or_direct_domain_entry_only',
        redcube_mcp_role: 'domain_handler_target_or_direct_protocol_adapter_only',
        bridge_exit_gate: { ...OPL_GENERATED_SURFACE_EXIT_GATE },
      },
      repository_boundary: {
        repo_tracks_declarative_pack_input: true,
        repo_tracks_generated_wrapper_outputs: false,
        repo_tracks_workbench_shell: false,
        repo_tracks_visual_or_export_artifact_blobs: false,
        repo_tracks_visual_memory_body: false,
        repo_tracks_live_receipt_instances: false,
      },
      visual_pack_discipline_contract: { ...RCA_VISUAL_PACK_DISCIPLINE_CONTRACT },
      cognitive_stage_pack_contract: { ...RCA_COGNITIVE_STAGE_PACK_CONTRACT },
      markdown_marp_route_policy: { ...RCA_MARKDOWN_MARP_ROUTE_POLICY },
      package_distribution_gate: { ...RCA_PACKAGE_DISTRIBUTION_GATE },
    },
    generated_surface_handoff: {
      handoff_id: 'rca.opl_generated_surface_handoff.v1',
      owner: 'opl',
      consumer: 'redcube_ai',
      generation_owner: 'opl_pack_compiler',
      rca_role: 'declarative_visual_pack_provider_and_authority_function_owner',
      generated_surface_targets: [...OPL_GENERATED_SURFACE_TARGETS],
      generated_descriptor_scope: [...OPL_GENERATED_DESCRIPTOR_SCOPE],
      repo_local_handler_targets: [...RCA_REPO_LOCAL_HANDLER_TARGETS],
      rca_generated_surface_owner: false,
      current_rca_shell_status: 'opl_generated_surface_consumed_domain_handlers_only',
      post_closure_evidence_guard_ids: [
        'domain_authority_refs_preserved',
        'no_regression_proof_recorded',
      ],
      bridge_exit_gate: { ...OPL_GENERATED_SURFACE_EXIT_GATE },
      generated_surfaces_are_not_rca_long_term_owner: true,
      repo_local_launcher_policy: {
        generated_descriptor_owner: 'one-person-lab',
        domain_handler_owner: 'redcube_ai',
        redcube_cli_role: 'domain_handler_target_or_direct_domain_entry_only',
        redcube_mcp_role: 'domain_handler_target_or_direct_protocol_adapter_only',
        domain_handler_role: 'domain_handler_target_with_internal_domain_action_adapter_implementation_refs_only',
        product_entry_continuity_refs_adapter_role: 'entry_session_domain_snapshot_refs_only_adapter',
        cli_mcp_skill_product_status_workbench_metadata_owner: 'one-person-lab',
        default_generic_dispatch_owner: 'one-person-lab',
        default_supervision_owner: 'one-person-lab',
        legacy_supervision_public_surface: 'retired',
        redcube_cli_is_unified_metadata_owner: false,
        redcube_mcp_is_unified_metadata_owner: false,
        product_entry_continuity_refs_adapter_is_generic_session_owner: false,
      },
      wrappers: {
        cli: { owner: 'opl', current_rca_role: 'domain_handler_target', long_term_rca_owner: false },
        mcp: { owner: 'opl', current_rca_role: 'domain_handler_target', long_term_rca_owner: false },
        skill: { owner: 'opl', current_rca_role: 'generated_domain_app_skill_descriptor', long_term_rca_owner: false },
        product_entry: { owner: 'opl', current_rca_role: 'direct_domain_entry_target', long_term_rca_owner: false },
        domain_handler: {
          owner: 'opl',
          current_rca_role: 'domain_handler_target_with_internal_domain_action_adapter_implementation_refs_only',
          domain_handler_target: 'domain_handler',
          long_term_rca_owner: false,
        },
        status: { owner: 'opl', current_rca_role: 'domain_status_projection_target', long_term_rca_owner: false },
        session: { owner: 'opl', current_rca_role: 'domain_session_snapshot_refs_adapter', long_term_rca_owner: false },
        workbench: { owner: 'opl', current_rca_role: 'generated_surface', long_term_rca_owner: false },
        harness: { owner: 'opl', current_rca_role: 'generated_surface', long_term_rca_owner: false },
      },
      authority_boundary: {
        opl_can_generate_cli_wrapper: true,
        opl_can_generate_mcp_wrapper: true,
        opl_can_generate_product_entry_wrapper: true,
        opl_can_generate_domain_handler_wrapper: true,
        opl_can_generate_status_projection: true,
        opl_can_generate_session_shell: true,
        opl_can_generate_workbench_shell: true,
        opl_can_generate_functional_harness: true,
        opl_can_write_rca_visual_truth: false,
        opl_can_authorize_source_readiness: false,
        opl_can_authorize_communication_visual_direction: false,
        opl_can_authorize_review_export_verdict: false,
        opl_can_authorize_artifact_mutation: false,
        opl_can_accept_or_reject_visual_memory: false,
        opl_can_issue_owner_receipt: false,
        opl_can_own_native_helper_implementation: false,
      },
    },
    minimal_authority_function_contract: {
      contract_id: 'rca.minimal_authority_functions.v1',
      owner: 'redcube_ai',
      allowed_authority_surface_ids: [...RCA_MINIMAL_AUTHORITY_FUNCTIONS],
      authority_surface_taxonomy: buildRcaMinimalAuthoritySurfaceTaxonomy(),
      authority_surface_contracts: buildRcaMinimalAuthoritySurfaceContracts(),
      forbidden_rca_long_term_owner_surfaces: [...OPL_GENERATED_SURFACE_TARGETS],
      only_allowed_long_term_rca_authority: true,
      authority_surface_boundaries: {
        source_readiness_verdict: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        communication_visual_direction_decision: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        review_export_verdict: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        artifact_mutation_authorization: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        visual_memory_accept_reject: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        owner_receipt_signer: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        native_helper_implementation: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
      },
    },
  };
}
