// @ts-nocheck

export const RCA_MINIMAL_AUTHORITY_FUNCTIONS = Object.freeze([
  'source_readiness_verdict',
  'communication_visual_direction_decision',
  'review_export_verdict',
  'artifact_mutation_authorization',
  'visual_memory_accept_reject',
  'owner_receipt_signer',
  'native_helper_implementation',
]);

export const RCA_AI_FIRST_JUDGMENT_SURFACES = Object.freeze([
  'source_readiness_verdict',
  'communication_visual_direction_decision',
  'review_export_verdict',
  'visual_memory_accept_reject',
]);

export const RCA_PROGRAMMATIC_AUTHORITY_SURFACES = Object.freeze([
  'artifact_mutation_authorization',
  'owner_receipt_signer',
  'native_helper_implementation',
]);

const AUTHORITY_SURFACE_PROFILES = Object.freeze({
  source_readiness_verdict: {
    work_mode: 'ai_first_visual_judgment_surface',
    judgment_owner: 'ai_first_source_readiness_stage_artifact',
    programmatic_role: 'source_pack_ref_validator_and_typed_blocker',
    ai_stage_artifact_required: true,
    allowed_return_shapes: ['verdict_refs', 'typed_blocker', 'owner_receipt_refs'],
  },
  communication_visual_direction_decision: {
    work_mode: 'ai_first_visual_judgment_surface',
    judgment_owner: 'ai_authored_communication_strategy_or_visual_direction_stage_artifact',
    programmatic_role: 'visual_direction_ref_materializer',
    ai_stage_artifact_required: true,
    allowed_return_shapes: ['visual_direction_refs', 'typed_blocker', 'owner_receipt_refs'],
  },
  review_export_verdict: {
    work_mode: 'ai_first_visual_judgment_surface',
    judgment_owner: 'ai_first_visual_review_or_export_gate_artifact',
    programmatic_role: 'review_export_ref_validator_and_receipt_guard',
    ai_stage_artifact_required: true,
    allowed_return_shapes: ['verdict_refs', 'typed_blocker', 'owner_receipt_refs'],
  },
  artifact_mutation_authorization: {
    work_mode: 'programmatic_authority_guard_surface',
    judgment_owner: 'rca_owner_receipt_blocked_item_and_repair_target',
    programmatic_role: 'artifact_mutation_materializer_and_guard',
    ai_stage_artifact_required: false,
    allowed_return_shapes: ['artifact_refs', 'typed_blocker', 'owner_receipt_refs'],
  },
  visual_memory_accept_reject: {
    work_mode: 'ai_first_visual_judgment_surface',
    judgment_owner: 'ai_first_visual_memory_learning_stage_artifact',
    programmatic_role: 'memory_receipt_writer_and_locator_projection',
    ai_stage_artifact_required: true,
    allowed_return_shapes: ['memory_receipt_refs', 'typed_blocker', 'owner_receipt_refs'],
  },
  owner_receipt_signer: {
    work_mode: 'programmatic_authority_guard_surface',
    judgment_owner: 'rca_owner_receipt_schema_and_domain_provenance',
    programmatic_role: 'receipt_schema_signer_and_blocker_guard',
    ai_stage_artifact_required: false,
    allowed_return_shapes: ['owner_receipt_refs', 'typed_blocker', 'no_regression_evidence_refs'],
  },
  native_helper_implementation: {
    work_mode: 'programmatic_authority_guard_surface',
    judgment_owner: 'rca_native_helper_catalog_and_owner_receipt_policy',
    programmatic_role: 'native_ppt_image_export_helper_implementation',
    ai_stage_artifact_required: false,
    allowed_return_shapes: ['helper_proof_refs', 'artifact_refs', 'typed_blocker'],
  },
});

export function buildRcaMinimalAuthoritySurfaceTaxonomy() {
  return {
    surface_kind: 'rca_minimal_authority_surface_taxonomy',
    taxonomy_id: 'rca.minimal_authority_surface_taxonomy.v1',
    owner: 'redcube_ai',
    ai_first_judgment_surface_ids: [...RCA_AI_FIRST_JUDGMENT_SURFACES],
    programmatic_authority_surface_ids: [...RCA_PROGRAMMATIC_AUTHORITY_SURFACES],
    all_surface_ids: [...RCA_MINIMAL_AUTHORITY_FUNCTIONS],
    mechanical_decision_forbidden_for_all_surfaces: true,
    programmatic_verdict_generation_allowed: false,
    policy: 'visual/source/review/memory judgments require AI-first stage artifacts; programmatic surfaces guard owner receipts and refs only',
  };
}

export function buildRcaMinimalAuthoritySurfaceContracts() {
  return RCA_MINIMAL_AUTHORITY_FUNCTIONS.map((surfaceId) => {
    const profile = AUTHORITY_SURFACE_PROFILES[surfaceId];
    return {
      surface_kind: 'rca_minimal_authority_surface',
      authority_surface_id: surfaceId,
      owner: 'redcube_ai',
      retention_class: 'rca_minimal_authority_function',
      generated_by_opl: false,
      opl_generated_wrapper_allowed: true,
      work_mode: profile.work_mode,
      judgment_owner: profile.judgment_owner,
      programmatic_role: profile.programmatic_role,
      ai_stage_artifact_required: profile.ai_stage_artifact_required,
      stage_or_owner_receipt_evidence_required: true,
      mechanical_decision_forbidden: true,
      programmatic_verdict_generation_allowed: false,
      allowed_return_shapes: [...profile.allowed_return_shapes],
      output_boundary: {
        allowed_return_shapes: [...profile.allowed_return_shapes],
        forbidden_outputs: [
          'visual_truth_write',
          'artifact_blob_write_without_owner_receipt',
          'memory_body_write',
          'mechanical_ready_verdict',
          'programmatic_ready_verdict',
          'ai_free_visual_verdict',
          'schema_completeness_ready_verdict',
          'generic_lifecycle_completion_verdict',
        ],
      },
      forbidden_decision_sources: [
        'schema_completeness',
        'provider_completion',
        'generic_lifecycle_completion',
        'artifact_file_presence',
        'mechanical_screenshot_metrics_alone',
        'controller_route_state',
        'runtime_queue_state',
      ],
      decision_boundary: {
        ai_first_judgment_required: profile.ai_stage_artifact_required,
        programmatic_role_may_materialize_refs_only: true,
        programmatic_role_may_compute_ready_verdict: false,
        owner_receipt_or_typed_blocker_required_when_evidence_missing: true,
      },
    };
  });
}

export const OPL_GENERATED_SURFACE_TARGETS = Object.freeze([
  'cli_wrapper',
  'mcp_wrapper',
  'skill_wrapper',
  'product_entry_wrapper',
  'domain_handler_wrapper',
  'status_projection_wrapper',
  'session_wrapper',
  'workbench_wrapper',
  'functional_harness_wrapper',
]);

export const OPL_GENERATED_DESCRIPTOR_SCOPE = Object.freeze([
  'cli',
  'mcp',
  'skill',
  'product_entry',
  'product_status',
  'product_session',
  'domain_handler',
  'workbench',
]);

export const RCA_REPO_LOCAL_HANDLER_TARGETS = Object.freeze([
  'redcube_cli',
  'redcube_mcp',
  'invokeProductEntry',
  'invokeDomainEntry',
  'domain_handler',
  'product_entry_continuity_refs_adapter',
]);

export const RCA_VISUAL_PACK_DISCIPLINE_CONTRACT = Object.freeze({
  owner: 'redcube_ai',
  policy_ref: 'agent/quality_gates/visual_pack_discipline.md',
  required_before_artifact_creation: true,
  required_contract_fields: [
    'deliverable_family',
    'route',
    'audience',
    'output_format',
    'canvas_or_aspect_ratio',
    'visual_direction_refs',
    'brand_profile_precedence_refs',
    'material_status_refs',
    'source_material_pass_refs',
    'layout_density_refs',
    'sparse_page_evidence_refs',
    'render_acceptance_refs',
    'review_gate_refs',
    'export_target',
  ],
  brand_profile_precedence: {
    precedence_order: [
      'explicit_delivery_request_brand_material',
      'rca_visual_direction_judgment',
      'workspace_profile_defaults',
      'user_profile_defaults',
      'built_in_route_defaults',
    ],
    approved_task_material_overrides_memory_or_defaults: true,
    generated_or_inferred_profile_can_override_approved_material: false,
    defaults_fill_missing_fields_only: true,
    required_refs: [
      'brand_profile_precedence_refs',
      'approved_brand_material_refs',
      'visual_direction_refs',
      'profile_default_refs',
      'typed_blocker_refs',
    ],
  },
  source_material_pass_transparency: {
    required_item_statuses: ['approved', 'provided_unverified', 'missing', 'out_of_scope'],
    pass_level_evidence_required: true,
    per_material_item_required_fields: [
      'material_id',
      'material_kind',
      'status',
      'pass_ref',
      'source_ref',
      'verified',
      'carried_forward',
      'gap_ref',
      'typed_blocker_ref',
    ],
    missing_or_unverified_required_material_yields: [
      'source_gap_refs',
      'material_gap_refs',
      'typed_blocker',
    ],
    opl_generated_surface_may_summarize_refs_only: true,
  },
  layout_density_sparse_page_evidence: {
    density_contract_required_before_layout: true,
    required_fields: [
      'target_density_band',
      'page_or_frame_inventory_refs',
      'minimum_occupancy_evidence_refs',
      'sparse_page_acceptance_reason_refs',
      'merge_split_decision_refs',
      'blocked_page_refs',
      'screenshot_review_refs',
      'export_gate_refs',
    ],
    sparse_page_can_pass_without_rca_rationale: false,
    provider_completion_can_accept_sparse_page: false,
    schema_completeness_can_accept_sparse_page: false,
    allowed_sparse_page_outcomes: [
      'accepted_with_rca_owned_rationale_refs',
      'repair_target_refs',
      'merge_or_split_decision_refs',
      'typed_blocker',
    ],
  },
  material_status_required: true,
  render_acceptance_required: true,
  mechanical_checks_can_issue_visual_verdict: false,
  provider_completion_can_issue_visual_verdict: false,
  allowed_machine_outputs: [
    'typed_blocker',
    'repair_target_refs',
    'preserved_page_refs',
    'no_regression_refs',
    'helper_proof_refs',
  ],
  forbidden_machine_outputs: [
    'visual_ready_verdict',
    'exportable_verdict',
    'handoffable_verdict',
    'publication_ready_verdict',
    'artifact_body_write_without_owner_receipt',
  ],
});

export const RCA_MARKDOWN_MARP_ROUTE_POLICY = Object.freeze({
  owner: 'redcube_ai',
  policy_ref: 'agent/knowledge/markdown_route_policy.md',
  route_family: 'markdown_marp',
  route_default: false,
  explicit_selection_required: true,
  refs_only: true,
  allowed_route_use: [
    'operator_explicit_markdown_or_marp_request',
    'source_to_slide_text_structuring_refs',
    'intermediate_outline_or_script_packaging_refs',
  ],
  default_visual_route_ref: 'author_image_pages',
  external_runtime_authority_allowed: false,
  provider_completion_can_issue_visual_verdict: false,
});

export const RCA_PACKAGE_DISTRIBUTION_GATE = Object.freeze({
  owner: 'redcube_ai',
  policy_ref: 'agent/quality_gates/package_distribution.md',
  gate_id: 'rca.package_distribution_consistency.v1',
  refs_only: true,
  required_consistency_checks: [
    'source_to_package_required_domain_pack_paths_match',
    'plugin_skill_refs_resolve_to_repo_tracked_pack_paths',
    'package_manifest_does_not_add_runtime_authority',
    'packaging_does_not_change_route_default',
  ],
  package_can_omit_required_domain_pack_refs: false,
  packaging_can_change_route_default: false,
  external_runtime_authority_allowed: false,
});

export const RCA_COGNITIVE_STAGE_PACK_REQUIRED_SECTIONS = Object.freeze([
  'prompt_refs',
  'skill_refs',
  'tool_refs',
  'tool_affordance_boundary',
  'knowledge_refs',
  'quality_gate_refs',
  'strategy_refs',
  'candidate_pool_policy',
  'independent_gate_policy',
  'handoff_policy',
]);

export const RCA_DOMAIN_TOOL_AFFORDANCE_REF = Object.freeze({
  ref: 'agent/tools/domain_affordances.md',
  ref_kind: 'repo_path',
  role: 'domain_tool_affordance_catalog',
  catalog_role: 'available_affordance_catalog_not_workflow_script',
});

export const RCA_COGNITIVE_TOOL_AFFORDANCE_BOUNDARY = Object.freeze({
  catalog_role: 'available_affordance_catalog_not_workflow_script',
  capability_refs: [
    { ref: 'source_context_and_visual_brief_reading', ref_kind: 'policy_ref', role: 'capability_boundary' },
    { ref: 'visual_direction_and_candidate_generation_support', ref_kind: 'policy_ref', role: 'capability_boundary' },
    { ref: 'native_ppt_render_screenshot_and_export_helpers', ref_kind: 'policy_ref', role: 'capability_boundary' },
    { ref: 'visual_review_repair_and_artifact_lineage_support', ref_kind: 'policy_ref', role: 'capability_boundary' },
  ],
  permission_scope_refs: [
    { ref: 'repo_context_read', ref_kind: 'policy_ref', role: 'permission_scope_boundary' },
    { ref: 'declared_domain_workspace_read', ref_kind: 'policy_ref', role: 'permission_scope_boundary' },
    { ref: 'bounded_domain_artifact_write_when_owner_authorized', ref_kind: 'policy_ref', role: 'permission_scope_boundary' },
    { ref: 'receipt_or_typed_blocker_return', ref_kind: 'policy_ref', role: 'permission_scope_boundary' },
  ],
  credential_boundary_refs: [
    { ref: 'no_secret_material_in_stage_pack', ref_kind: 'policy_ref', role: 'credential_boundary_boundary' },
    { ref: 'executor_must_request_human_gate_for_missing_credentials', ref_kind: 'policy_ref', role: 'credential_boundary_boundary' },
  ],
  write_scope_refs: [
    { ref: 'visual_workspace_refs_only', ref_kind: 'policy_ref', role: 'write_scope_boundary' },
    { ref: 'deliverable_artifact_mutation_only_with_rca_artifact_authority_receipt', ref_kind: 'policy_ref', role: 'write_scope_boundary' },
  ],
  side_effect_risk_refs: [
    { ref: 'external_network_or_portal_side_effect_requires_explicit_stage_permission', ref_kind: 'policy_ref', role: 'side_effect_risk_boundary' },
    { ref: 'artifact_or_package_mutation_requires_domain_owner_receipt', ref_kind: 'policy_ref', role: 'side_effect_risk_boundary' },
  ],
  forbidden_authority_refs: [
    { ref: 'visual_truth_write_by_opl', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
    { ref: 'review_verdict_without_rca_owner_receipt', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
    { ref: 'export_verdict_without_rca_owner_receipt', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
    { ref: 'artifact_body_write_without_artifact_authority_receipt', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
    { ref: 'visual_memory_body_write_by_opl', ref_kind: 'policy_ref', role: 'forbidden_authority_boundary' },
  ],
  executor_autonomy: {
    executor_can_choose_tools: true,
    executor_can_skip_tools: true,
    executor_can_substitute_tools_within_boundary: true,
    executor_can_choose_order_and_parallelism: true,
    executor_can_request_missing_context_or_human_gate: true,
    tool_catalog_can_prescribe_tool_sequence: false,
    tool_catalog_can_define_cognitive_strategy: false,
    tool_catalog_can_override_stage_goal: false,
    tool_catalog_can_authorize_forbidden_write: false,
  },
  policy:
    'redcube_ai tool refs declare available affordances and safety boundaries only; they do not prescribe executor order, stage strategy, stage goal, or forbidden writes.',
});

export const RCA_COGNITIVE_KERNEL_ADOPTION = Object.freeze({
  surface_kind: 'opl_cognitive_kernel_adoption',
  version: 'cognitive-kernel-adoption.v1',
  owner: 'redcube-ai',
  domain_id: 'redcube_ai',
  state: 'advisory_current_contract',
  purpose:
    'RedCube AI declares repo-owned stage-internal cognitive-kernel refs, tool affordances, and independent gate boundaries for OPL-hosted Foundry Agent execution.',
  machine_boundary:
    'This contract is advisory/current adoption metadata. Domain truth, artifact bodies, quality verdicts, owner receipts, typed blockers, human gates, and export authority remain domain-owned; OPL owns transport, attempts, refs, receipts projection, and generated/hosted surfaces only.',
  framework_contract_ref: 'one-person-lab/contracts/opl-framework/cognitive-computation-kernel.json',
  pack_compiler_input_ref: 'contracts/pack_compiler_input.json',
  stage_control_plane_ref: 'contracts/stage_control_plane.json',
  golden_path_profile_ref: 'contracts/golden_path_profile.json',
  domain_affordance_catalog_ref: 'agent/tools/domain_affordances.md',
  stage_pack_required_sections: [...RCA_COGNITIVE_STAGE_PACK_REQUIRED_SECTIONS],
  tool_affordance_boundary: { ...RCA_COGNITIVE_TOOL_AFFORDANCE_BOUNDARY },
  authority_boundary: {
    domain_repo_declares_strategy_not_generic_runtime: true,
    domain_repo_can_claim_generated_surface_owner: false,
    opl_can_write_domain_truth: false,
    opl_can_read_domain_body: false,
    opl_can_create_owner_receipt: false,
    opl_can_create_typed_blocker: false,
    opl_can_claim_domain_ready: false,
    opl_can_claim_artifact_ready: false,
    strategy_refs_completeness_is_launch_hard_gate: false,
    independent_gate_receipt_required_for_quality_progression: true,
    same_attempt_self_review_can_close_quality_gate: false,
  },
  adoption_policy: {
    advisory_not_launch_hard_gate: true,
    tool_catalog_is_not_workflow_script: true,
    route_is_not_stage_strategy: true,
    stage_attempt_is_required_for_execution: true,
    candidate_pool_is_stage_internal_artifact: true,
    meta_review_updates_are_proposals_until_owner_acceptance: true,
  },
  stage_strategy_refs: [
    'visual_brief_goal_and_constraints',
    'image_first_candidate_generation',
    'screenshot_grounded_reflection',
    'visual_candidate_comparative_selection',
    'export_independent_quality_gate',
  ],
  stage_artifact_refs: [
    'source_readiness_manifest_ref',
    'communication_strategy_ref',
    'visual_direction_ref',
    'visual_artifact_candidate_ref',
    'review_revision_packet_ref',
    'package_handoff_ref',
  ],
});

export const RCA_GOLDEN_PATH_PROFILE = Object.freeze({
  surface_kind: 'opl_foundry_agent_golden_path_profile',
  version: 'golden-path-profile.v1',
  owner: 'redcube-ai',
  domain_id: 'redcube_ai',
  state: 'advisory_current_contract',
  profile_role: 'visual_foundry_agent_golden_path_profile',
  purpose:
    'RedCube AI golden path for OPL-hosted Foundry Agent execution under current_owner_delta and stage-internal cognitive-kernel boundaries.',
  machine_boundary:
    'This profile describes the intended happy path and stop-loss contract. It does not declare domain ready, App release ready, or production ready.',
  default_executor: 'codex_cli',
  default_outer_loop: 'current_owner_delta',
  stage_attempt_strategy: 'cognitive_kernel_stage_internal',
  domain_affordance_catalog_ref: 'agent/tools/domain_affordances.md',
  cognitive_kernel_adoption_ref: 'contracts/cognitive_kernel_adoption.json',
  stage_control_plane_ref: 'contracts/stage_control_plane.json',
  pack_compiler_input_ref: 'contracts/pack_compiler_input.json',
  golden_path_steps: [
    'hydrate_current_owner_delta',
    'run_stage_attempt_with_declared_prompt_skill_tool_knowledge_refs',
    'generate_candidate_pool_or_artifact_delta_inside_domain_workspace',
    'ground_review_in_source_refs_and_tool_evidence',
    'select_or_revise_candidate_with_lineage',
    'record_owner_receipt_typed_blocker_human_gate_or_route_back_ref',
    'project_refs_only_status_to_opl_and_app',
  ],
  required_closeout_refs: [
    'stage_artifact_unit_ref',
    'owner_receipt_ref_or_typed_blocker_ref',
    'independent_gate_receipt_ref_or_route_back_ref',
    'current_owner_delta_ref',
  ],
  stop_loss_policy: {
    missing_domain_truth: 'return_typed_blocker_ref',
    missing_credential_or_human_authority: 'return_human_gate_ref',
    failed_independent_gate: 'return_route_back_ref_or_typed_blocker_ref',
    forbidden_write_requested: 'return_typed_blocker_ref',
  },
  forbidden_claims: [
    'descriptor_ready_means_domain_ready',
    'provider_completion_means_quality_ready',
    'generated_surface_ready_means_export_ready',
    'same_attempt_self_review_closes_quality_gate',
    'tool_catalog_prescribes_executor_sequence',
  ],
});

export const RCA_REQUIRED_DOMAIN_PACK_PATHS = Object.freeze([
  'agent/prompts/source_intake.md',
  'agent/prompts/communication_strategy.md',
  'agent/prompts/visual_direction.md',
  'agent/prompts/artifact_creation.md',
  'agent/prompts/review_and_revision.md',
  'agent/prompts/package_and_handoff.md',
  'agent/stages/source_intake.md',
  'agent/stages/communication_strategy.md',
  'agent/stages/visual_direction.md',
  'agent/stages/artifact_creation.md',
  'agent/stages/review_and_revision.md',
  'agent/stages/package_and_handoff.md',
  'agent/skills/visual_deliverable_authoring.md',
  'agent/skills/native_helper_policy.md',
  'agent/skills/visual_memory_policy.md',
  'agent/quality_gates/visual_authority_boundaries.md',
  'agent/quality_gates/source_and_truth.md',
  'agent/quality_gates/communication_and_direction.md',
  'agent/quality_gates/visual_pack_discipline.md',
  'agent/quality_gates/package_distribution.md',
  'agent/quality_gates/artifact_authority.md',
  'agent/quality_gates/review_export_memory.md',
  'agent/knowledge/visual_truth_boundaries.md',
  'agent/knowledge/communication_visual_direction.md',
  'agent/knowledge/artifact_and_export_authority.md',
  'agent/knowledge/review_export_memory.md',
  'agent/knowledge/markdown_route_policy.md',
  'agent/knowledge/owner_receipt_policy.md',
  'agent/tools/domain_affordances.md',
]);

export const OPL_GENERATED_SURFACE_EXIT_GATE = Object.freeze({
  gate_id: 'rca.generated_surface_bridge_exit.v1',
  owner: 'one-person-lab',
  consumer: 'redcube_ai',
  current_rca_status: 'opl_generated_surface_consumed_domain_handlers_only',
  required_before_retiring_repo_local_wrappers: [
    'domain_authority_refs_preserved',
    'no_regression_proof_recorded',
  ],
  repo_local_allowed_roles_before_exit: [
    'domain_handler_target',
    'direct_domain_entry',
    'direct_protocol_adapter',
    'refs_only_adapter',
  ],
  repo_local_forbidden_roles: [
    'unified_metadata_owner',
    'generic_dispatch_owner',
    'generic_session_shell_owner',
    'generic_workbench_owner',
    'generated_surface_owner',
  ],
  after_exit_rca_allowed_surfaces: [
    'declarative_visual_pack_input',
    'domain_handler_targets',
    'minimal_authority_functions',
    'refs_only_locator_projection',
  ],
  rca_can_own_generated_surface: false,
  rca_can_own_generic_session_shell: false,
  rca_can_own_generic_workbench: false,
  declares_generated_surface_consumption_complete: true,
  declares_production_consumption_complete: true,
  production_consumption_scope: 'opl_generated_surface_consumption_only_not_visual_stage_live_soak',
  declares_visual_stage_long_soak_complete: false,
  remaining_blocker_ids: [],
  remaining_evidence_gate_ids: [
    'real_artifact_producing_domain_owner_receipt',
    'opl_hosted_controlled_visual_stage_long_soak',
    'real_memory_lifecycle_receipt_instances',
    'cross_family_repeated_no_regression_evidence',
  ],
});

export const RCA_COGNITIVE_STAGE_PACK_CONTRACT = Object.freeze({
  owner: 'redcube_ai',
  consumer: 'opl_pack_compiler',
  contract_ref: 'contracts/opl-framework/cognitive-computation-kernel.json',
  stage_control_plane_ref: 'contracts/stage_control_plane.json',
  cognitive_kernel_adoption_ref: 'contracts/cognitive_kernel_adoption.json',
  golden_path_profile_ref: 'contracts/golden_path_profile.json',
  domain_affordance_catalog_ref: { ...RCA_DOMAIN_TOOL_AFFORDANCE_REF },
  refs_only: true,
  user_visible_flow_changed: false,
  launch_hard_gate: false,
  required_stage_sections: [...RCA_COGNITIVE_STAGE_PACK_REQUIRED_SECTIONS],
  stage_strategy_owner: 'selected_codex_executor_with_rca_owned_gates',
  tool_affordance_policy: 'available_affordance_catalog_not_workflow_script',
  tool_affordance_boundary: { ...RCA_COGNITIVE_TOOL_AFFORDANCE_BOUNDARY },
  candidate_pool_policy: 'stage_internal_refs_with_lineage_no_user_flow_expansion',
  independent_gate_policy: 'execution_and_review_attempts_must_be_separable_for_quality_progression',
  authority_boundary: {
    opl_can_write_visual_truth: false,
    opl_can_write_artifact_body: false,
    opl_can_authorize_review_export_verdict: false,
    opl_can_sign_owner_receipt: false,
    provider_completion_is_visual_ready: false,
    same_attempt_self_review_can_close_quality_gate: false,
  },
});

export function buildVisualPackCompilerHandoffProjection() {
  return {
    surface_kind: 'visual_pack_compiler_handoff',
    projection_id: 'rca.visual_pack_compiler_handoff.v1',
    ref: '/visual_pack_compiler_handoff',
    visual_pack_compiler_input_ref: '/visual_pack_compiler_handoff/declarative_visual_pack_input',
    generated_surface_handoff_ref: '/visual_pack_compiler_handoff/generated_surface_handoff',
    contract_ref: 'rca.visual_pack_compiler_handoff.v1',
    owner: 'redcube_ai',
    consumer: 'opl_pack_compiler',
    status: 'machine_handoff_surface_landed',
    projection_mode: 'declarative_visual_pack_input_with_generated_surface_handoff',
    read_only: true,
    refs_only: true,
    declares_production_soak_complete: false,
    visual_pack_discipline: {
      surface_kind: 'visual_pack_discipline_refs',
      discipline_id: 'rca.executable_visual_pack_discipline.v1',
      owner: 'redcube_ai',
      consumer: 'opl_pack_compiler',
      status: 'refs_only_projection_landed',
      read_only: true,
      refs_only: true,
      inspiration_scope: 'external_document_system_lessons_adapted_to_rca_refs_only',
      canonical_pack_root: 'agent/',
      pack_compiler_input_ref: 'contracts/pack_compiler_input.json',
      stage_prompt_refs: [
        'agent/prompts/source_intake.md',
        'agent/prompts/communication_strategy.md',
        'agent/prompts/visual_direction.md',
        'agent/prompts/artifact_creation.md',
        'agent/prompts/review_and_revision.md',
        'agent/prompts/package_and_handoff.md',
      ],
      stage_descriptor_refs: [
        'agent/stages/source_intake.md',
        'agent/stages/communication_strategy.md',
        'agent/stages/visual_direction.md',
        'agent/stages/artifact_creation.md',
        'agent/stages/review_and_revision.md',
        'agent/stages/package_and_handoff.md',
      ],
      quality_gate_refs: [
        'agent/quality_gates/visual_authority_boundaries.md',
        'agent/quality_gates/source_and_truth.md',
        'agent/quality_gates/communication_and_direction.md',
        'agent/quality_gates/visual_pack_discipline.md',
        'agent/quality_gates/artifact_authority.md',
        'agent/quality_gates/review_export_memory.md',
        'agent/quality_gates/screenshot_review.md',
      ],
      authority_boundary: {
        opl_can_discover_pack_refs: true,
        opl_can_compile_generated_surfaces_from_refs: true,
        opl_can_write_rca_visual_truth: false,
        opl_can_write_artifact_body: false,
        opl_can_write_visual_memory_body: false,
        opl_can_authorize_review_export_verdict: false,
        provider_completion_is_visual_ready: false,
      },
      forbidden_outputs: [
        'visual_truth_body',
        'artifact_body',
        'visual_memory_body',
        'review_export_verdict_body',
        'provider_completion_visual_ready_claim',
      ],
    },
    markdown_marp_route_policy: {
      surface_kind: 'markdown_marp_optional_route_policy_refs',
      route_policy_id: 'rca.markdown_marp_optional_route_policy.v1',
      owner: 'redcube_ai',
      consumer: 'opl_pack_compiler',
      status: 'optional_refs_only_policy_landed',
      read_only: true,
      refs_only: true,
      route_family: RCA_MARKDOWN_MARP_ROUTE_POLICY.route_family,
      route_default: RCA_MARKDOWN_MARP_ROUTE_POLICY.route_default,
      explicit_selection_required: RCA_MARKDOWN_MARP_ROUTE_POLICY.explicit_selection_required,
      policy_ref: RCA_MARKDOWN_MARP_ROUTE_POLICY.policy_ref,
      allowed_route_use: [...RCA_MARKDOWN_MARP_ROUTE_POLICY.allowed_route_use],
      default_visual_route_ref: RCA_MARKDOWN_MARP_ROUTE_POLICY.default_visual_route_ref,
      route_material_refs: [
        'agent/knowledge/markdown_route_policy.md',
        'agent/quality_gates/visual_pack_discipline.md',
        'agent/quality_gates/review_export_memory.md',
      ],
      authority_boundary: {
        redcube_ai_owns_route_truth: true,
        opl_can_discover_route_refs: true,
        opl_can_compile_optional_route_surface_from_refs: true,
        external_runtime_authority_allowed: RCA_MARKDOWN_MARP_ROUTE_POLICY.external_runtime_authority_allowed,
        provider_completion_is_visual_ready: RCA_MARKDOWN_MARP_ROUTE_POLICY.provider_completion_can_issue_visual_verdict,
        markdown_marp_route_can_replace_default: false,
      },
      forbidden_outputs: [
        'default_route_replacement',
        'external_runtime_authority',
        'visual_ready_verdict',
        'exportable_verdict',
        'artifact_body_write_without_owner_receipt',
      ],
    },
    package_distribution_gate: {
      surface_kind: 'package_distribution_consistency_gate_refs',
      gate_id: RCA_PACKAGE_DISTRIBUTION_GATE.gate_id,
      owner: 'redcube_ai',
      consumer: 'opl_pack_compiler',
      status: 'source_to_package_consistency_gate_landed',
      read_only: true,
      refs_only: true,
      policy_ref: RCA_PACKAGE_DISTRIBUTION_GATE.policy_ref,
      required_domain_pack_paths: [...RCA_REQUIRED_DOMAIN_PACK_PATHS],
      required_consistency_checks: [...RCA_PACKAGE_DISTRIBUTION_GATE.required_consistency_checks],
      authority_boundary: {
        package_can_omit_required_domain_pack_refs: RCA_PACKAGE_DISTRIBUTION_GATE.package_can_omit_required_domain_pack_refs,
        packaging_can_change_route_default: RCA_PACKAGE_DISTRIBUTION_GATE.packaging_can_change_route_default,
        external_runtime_authority_allowed: RCA_PACKAGE_DISTRIBUTION_GATE.external_runtime_authority_allowed,
        packaging_can_issue_visual_verdict: false,
      },
      forbidden_outputs: [
        'package_manifest_runtime_authority',
        'missing_required_domain_pack_ref',
        'route_default_mutation',
        'visual_ready_verdict',
      ],
    },
    render_review_gate_contract: {
      surface_kind: 'render_review_gate_contract_refs',
      contract_id: 'rca.render_review_gate_contract.v1',
      owner: 'redcube_ai',
      consumer: 'opl_generated_surface',
      status: 'refs_only_projection_landed',
      read_only: true,
      refs_only: true,
      review_export_authority_surface_id: 'review_export_verdict',
      render_gate_refs: [
        'agent/quality_gates/artifact_authority.md',
        'agent/quality_gates/screenshot_review.md',
      ],
      review_gate_refs: [
        'agent/quality_gates/review_export_memory.md',
        '/review_state',
        '/publication_projection',
      ],
      required_stage_refs: [
        'visual_director_review',
        'screenshot_review',
        'export_pptx',
      ],
      required_return_shapes: [
        'verdict_refs',
        'typed_blocker',
        'owner_receipt_refs',
      ],
      authority_boundary: {
        redcube_ai_owns_review_export_verdict: true,
        opl_can_discover_gate_refs: true,
        opl_can_store_gate_refs: true,
        opl_can_authorize_review_export_verdict: false,
        opl_can_declare_visual_ready: false,
        opl_can_declare_exportable: false,
        provider_completion_is_visual_ready: false,
      },
      forbidden_outputs: [
        'visual_truth_write',
        'artifact_blob_write_without_owner_receipt',
        'memory_body_write',
        'review_export_verdict_body',
        'mechanical_ready_verdict',
        'programmatic_ready_verdict',
        'provider_completion_visual_ready_claim',
      ],
    },
    declarative_visual_pack_input: {
      input_id: 'rca.declarative_visual_pack_input.v1',
      owner: 'redcube_ai',
      compiler_owner: 'opl',
      input_mode: 'domain_descriptor_refs_only',
      generated_surface_mode: 'opl_generated_surface_consumed_domain_handlers_only',
      source_refs: [
        { source_id: 'domain_descriptor', ref: '/standard_domain_agent_skeleton' },
        { source_id: 'deliverable_family_graph', ref: '/family_stage_control_plane' },
        { source_id: 'action_metadata', ref: '/family_action_catalog' },
        { source_id: 'visual_transition_spec', ref: '/visual_transition_spec' },
        { source_id: 'review_export_policies', refs: ['/review_state', '/publication_projection'] },
        { source_id: 'artifact_locator_policy', ref: '/artifact_locator_contract' },
        { source_id: 'memory_locator_policy', ref: '/domain_memory_descriptor_locator' },
        { source_id: 'receipt_schema', ref: '/domain_owner_receipt_contract' },
        { source_id: 'lifecycle_receipt_schema', ref: '/lifecycle_guarded_apply_proof' },
        { source_id: 'native_helper_catalog', ref: 'contracts/runtime-program/python-native-helper-catalog.json' },
        { source_id: 'visual_pack_discipline_policy', ref: RCA_VISUAL_PACK_DISCIPLINE_CONTRACT.policy_ref },
        { source_id: 'markdown_marp_route_policy', ref: RCA_MARKDOWN_MARP_ROUTE_POLICY.policy_ref },
        { source_id: 'package_distribution_policy', ref: RCA_PACKAGE_DISTRIBUTION_GATE.policy_ref },
        { source_id: 'cognitive_kernel_adoption', ref: 'contracts/cognitive_kernel_adoption.json' },
        { source_id: 'golden_path_profile', ref: 'contracts/golden_path_profile.json' },
        { source_id: 'domain_tool_affordance_catalog', ref: 'agent/tools/domain_affordances.md' },
      ],
      required_input_families: [
        'domain_descriptor',
        'deliverable_family_graph',
        'stage_action_metadata',
        'source_readiness_policy',
        'visual_transition_spec',
        'review_export_policy',
        'artifact_locator_policy',
        'memory_locator_policy',
        'receipt_schema',
        'authority_function_manifest',
        'oracle_fixtures',
        'tool_affordance_catalog',
        'cognitive_kernel_adoption_contract',
        'golden_path_profile',
      ],
      required_domain_pack_paths: [...RCA_REQUIRED_DOMAIN_PACK_PATHS],
      authority_function_manifest: {
        owner: 'redcube_ai',
        retained_authority_surface_ids: [...RCA_MINIMAL_AUTHORITY_FUNCTIONS],
        retained_authority_surface_count: RCA_MINIMAL_AUTHORITY_FUNCTIONS.length,
        authority_surface_taxonomy: buildRcaMinimalAuthoritySurfaceTaxonomy(),
        retained_surface_contracts: buildRcaMinimalAuthoritySurfaceContracts(),
        all_other_generic_shells_generated_by_opl: true,
      },
      generated_descriptor_contract: {
        owner: 'opl',
        unified_metadata_owner: 'one-person-lab',
        descriptor_scope: [...OPL_GENERATED_DESCRIPTOR_SCOPE],
        repo_local_handler_targets: [...RCA_REPO_LOCAL_HANDLER_TARGETS],
        repo_local_handlers_are_generated_surface_owners: false,
        redcube_cli_role: 'domain_handler_target_or_direct_domain_entry_only',
        redcube_mcp_role: 'domain_handler_target_or_direct_protocol_adapter_only',
        bridge_exit_gate: { ...OPL_GENERATED_SURFACE_EXIT_GATE },
      },
      repository_boundary: {
        repo_tracks_declarative_pack_input: true,
        repo_tracks_generated_wrapper_outputs: false,
        repo_tracks_workbench_shell: false,
        repo_tracks_visual_or_export_artifact_blobs: false,
        repo_tracks_visual_memory_body: false,
        repo_tracks_live_receipt_instances: false,
      },
      visual_pack_discipline_contract: { ...RCA_VISUAL_PACK_DISCIPLINE_CONTRACT },
      cognitive_stage_pack_contract: { ...RCA_COGNITIVE_STAGE_PACK_CONTRACT },
      markdown_marp_route_policy: { ...RCA_MARKDOWN_MARP_ROUTE_POLICY },
      package_distribution_gate: { ...RCA_PACKAGE_DISTRIBUTION_GATE },
    },
    generated_surface_handoff: {
      handoff_id: 'rca.opl_generated_surface_handoff.v1',
      owner: 'opl',
      consumer: 'redcube_ai',
      generation_owner: 'opl_pack_compiler',
      rca_role: 'declarative_visual_pack_provider_and_authority_function_owner',
      generated_surface_targets: [...OPL_GENERATED_SURFACE_TARGETS],
      generated_descriptor_scope: [...OPL_GENERATED_DESCRIPTOR_SCOPE],
      repo_local_handler_targets: [...RCA_REPO_LOCAL_HANDLER_TARGETS],
      rca_generated_surface_owner: false,
      current_rca_shell_status: 'opl_generated_surface_consumed_domain_handlers_only',
      post_closure_evidence_guard_ids: [
        'domain_authority_refs_preserved',
        'no_regression_proof_recorded',
      ],
      bridge_exit_gate: { ...OPL_GENERATED_SURFACE_EXIT_GATE },
      generated_surfaces_are_not_rca_long_term_owner: true,
      repo_local_launcher_policy: {
        generated_descriptor_owner: 'one-person-lab',
        domain_handler_owner: 'redcube_ai',
        redcube_cli_role: 'domain_handler_target_or_direct_domain_entry_only',
        redcube_mcp_role: 'domain_handler_target_or_direct_protocol_adapter_only',
        domain_handler_role: 'domain_handler_target_with_internal_domain_action_adapter_implementation_refs_only',
        product_entry_continuity_refs_adapter_role: 'entry_session_domain_snapshot_refs_only_adapter',
        cli_mcp_skill_product_status_workbench_metadata_owner: 'one-person-lab',
        default_generic_dispatch_owner: 'one-person-lab',
        default_supervision_owner: 'one-person-lab',
        legacy_supervision_public_surface: 'retired',
        redcube_cli_is_unified_metadata_owner: false,
        redcube_mcp_is_unified_metadata_owner: false,
        product_entry_continuity_refs_adapter_is_generic_session_owner: false,
      },
      wrappers: {
        cli: { owner: 'opl', current_rca_role: 'domain_handler_target', long_term_rca_owner: false },
        mcp: { owner: 'opl', current_rca_role: 'domain_handler_target', long_term_rca_owner: false },
        skill: { owner: 'opl', current_rca_role: 'generated_domain_app_skill_descriptor', long_term_rca_owner: false },
        product_entry: { owner: 'opl', current_rca_role: 'direct_domain_entry_target', long_term_rca_owner: false },
        domain_handler: {
          owner: 'opl',
          current_rca_role: 'domain_handler_target_with_internal_domain_action_adapter_implementation_refs_only',
          domain_handler_target: 'domain_handler',
          long_term_rca_owner: false,
        },
        status: { owner: 'opl', current_rca_role: 'domain_status_projection_target', long_term_rca_owner: false },
        session: { owner: 'opl', current_rca_role: 'domain_session_snapshot_refs_adapter', long_term_rca_owner: false },
        workbench: { owner: 'opl', current_rca_role: 'generated_surface', long_term_rca_owner: false },
        harness: { owner: 'opl', current_rca_role: 'generated_surface', long_term_rca_owner: false },
      },
      authority_boundary: {
        opl_can_generate_cli_wrapper: true,
        opl_can_generate_mcp_wrapper: true,
        opl_can_generate_product_entry_wrapper: true,
        opl_can_generate_domain_handler_wrapper: true,
        opl_can_generate_status_projection: true,
        opl_can_generate_session_shell: true,
        opl_can_generate_workbench_shell: true,
        opl_can_generate_functional_harness: true,
        opl_can_write_rca_visual_truth: false,
        opl_can_authorize_source_readiness: false,
        opl_can_authorize_communication_visual_direction: false,
        opl_can_authorize_review_export_verdict: false,
        opl_can_authorize_artifact_mutation: false,
        opl_can_accept_or_reject_visual_memory: false,
        opl_can_issue_owner_receipt: false,
        opl_can_own_native_helper_implementation: false,
      },
    },
    minimal_authority_function_contract: {
      contract_id: 'rca.minimal_authority_functions.v1',
      owner: 'redcube_ai',
      allowed_authority_surface_ids: [...RCA_MINIMAL_AUTHORITY_FUNCTIONS],
      authority_surface_taxonomy: buildRcaMinimalAuthoritySurfaceTaxonomy(),
      authority_surface_contracts: buildRcaMinimalAuthoritySurfaceContracts(),
      forbidden_rca_long_term_owner_surfaces: [...OPL_GENERATED_SURFACE_TARGETS],
      only_allowed_long_term_rca_authority: true,
      authority_surface_boundaries: {
        source_readiness_verdict: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        communication_visual_direction_decision: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        review_export_verdict: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        artifact_mutation_authorization: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        visual_memory_accept_reject: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        owner_receipt_signer: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
        native_helper_implementation: {
          owner: 'redcube_ai',
          output_refs_only_for_opl: true,
          opl_can_authorize: false,
        },
      },
    },
  };
}
