// @ts-nocheck

import {
  FUNCTIONAL_MODULE_FORBIDDEN_OWNER_FLAGS,
  RCA_FUNCTIONAL_MODULE_REPLACEMENT_GUARDS,
  buildBridgeExitGate,
  buildFunctionalModulePhysicalDeletionGuard,
  buildPrivateGenericResidueBridgeExitGate,
  buildVisualAuthorityFunctionsAuditModule,
  buildVisualPackCompilerHandoffAuditModule,
} from './product-sidecar-parts/privatized-functional-module-audit.js';
import {
  buildVisualPackCompilerHandoffProjection,
} from './product-sidecar-parts/visual-pack-compiler-handoff.js';
export {
  OPL_GENERATED_INTERFACE_CONSUMPTION,
  OPL_FUNCTIONAL_HARNESS_COVERAGE,
  OPL_OWNED_GENERIC_PRIMITIVES,
  OPL_STABILITY_READ_MODEL_SURFACES,
  RCA_RETAINED_VISUAL_AUTHORITY,
  buildFamilySchedulerReplacementProjection,
  buildOplGenericPrimitiveConsumptionProjection,
  buildOplStabilityReadModelConsumptionProjection,
  buildOplSubstrateAdapterExportProjection,
} from './product-sidecar-parts/opl-generic-boundaries.js';
import {
  OPL_GENERATED_INTERFACE_CONSUMPTION,
  RCA_RETAINED_VISUAL_AUTHORITY,
  buildFamilySchedulerReplacementProjection,
  buildOplGenericPrimitiveConsumptionProjection,
  buildOplStabilityReadModelConsumptionProjection,
} from './product-sidecar-parts/opl-generic-boundaries.js';

export const SIDECAR_GUARDED_ACTIONS = Object.freeze([
  {
    action: 'runtime_watch',
    effect: 'read_only',
    summary: 'Read RCA runtimeWatch for an existing run locator as a refs-only projection; this does not run a generic supervisor or continuation loop.',
    required_fields: ['workspace_root', 'topic_id', 'deliverable_id', 'run_id'],
    api_surface: 'runtimeWatch',
  },
  {
    action: 'emit_no_regression_evidence',
    effect: 'guarded_runtime_evidence_write',
    summary: 'Emit RCA-owned no-regression evidence refs for descriptor/runtime surfaces without writing visual artifacts or claiming long soak.',
    required_fields: ['workspace_root', 'evidence_id'],
    api_surface: 'productSidecarEmitNoRegressionEvidence',
  },
  {
    action: 'emit_domain_owner_receipt',
    effect: 'guarded_domain_owner_receipt_write',
    summary: 'Emit an RCA-owned domain receipt instance into workspace runtime receipts when required refs are present; otherwise return a typed blocker.',
    required_fields: [
      'workspace_root',
      'receipt_id',
      'attempt_ref',
      'artifact_locator_ref',
      'memory_receipt_ref',
      'lifecycle_receipt_ref',
      'review_export_ref',
      'forbidden_write_proof_ref',
    ],
    api_surface: 'productSidecarEmitDomainOwnerReceipt',
  },
  {
    action: 'apply_visual_memory_writeback',
    effect: 'guarded_domain_memory_receipt_write',
    summary: 'Apply an RCA-owned visual pattern memory accept/reject decision and write a locator-only runtime receipt.',
    required_fields: [
      'workspace_root',
      'proposal_id',
      'decision',
      'decision_owner',
      'source_review_ref',
      'candidate_memory_ref',
    ],
    api_surface: 'productSidecarApplyVisualMemoryWriteback',
  },
  {
    action: 'apply_visual_workspace_lifecycle',
    effect: 'guarded_lifecycle_receipt_write',
    summary: 'Emit RCA-owned cleanup/restore/retention receipts for visual workspace lifecycle requests without mutating artifacts from the sidecar.',
    required_fields: [
      'workspace_root',
      'operation',
      'receipt_id',
      'domain_receipt_ref',
      'artifact_locator_ref',
    ],
    api_surface: 'productSidecarApplyVisualWorkspaceLifecycle',
  },
  {
    action: 'evaluate_visual_transition',
    effect: 'read_only_transition_guard_evaluation',
    summary: 'Evaluate an RCA-owned visual_transition_spec transition against explicit guard refs and return next-stage metadata or a typed blocker; OPL keeps generic runner ownership.',
    required_fields: ['workspace_root', 'transition_id', 'current_stage'],
    api_surface: 'productSidecarEvaluateVisualTransition',
  },
  {
    action: 'emit_workspace_receipt_proof',
    effect: 'guarded_workspace_receipt_proof_write',
    summary: 'Emit a workspace-runtime proof pack that chains RCA-owned memory, lifecycle, no-regression, and domain owner receipt refs without writing visual artifacts or OPL generic runtime state.',
    required_fields: [
      'workspace_root',
      'proof_id',
      'attempt_ref',
      'artifact_locator_ref',
      'review_export_ref',
      'forbidden_write_proof_ref',
    ],
    api_surface: 'productSidecarEmitWorkspaceReceiptProof',
  },
  {
    action: 'notification_receipt',
    effect: 'control_plane_ack_only',
    summary: 'Acknowledge an OPL/Hermes notification without writing RCA visual truth, review verdict, or publication gate.',
    required_fields: ['notification_id'],
    api_surface: 'none',
  },
]);

export const SIDECAR_FORBIDDEN_WRITES = Object.freeze([
  'visual_truth',
  'review_verdict',
  'publication_gate',
  'canonical_artifacts',
]);

export const SIDECAR_BLOCKED_ACTIONS = Object.freeze([
  'write_visual_truth',
  'write_canonical_artifacts',
  'write_review_verdict',
  'write_publication_gate',
  'mutate_review_state',
  'publish_export_bundle',
]);

export const RCA_REMAINING_EVIDENCE_GATES = Object.freeze([
  'real_artifact_producing_domain_owner_receipt',
  'opl_hosted_controlled_visual_stage_long_soak',
  'real_memory_lifecycle_receipt_instances',
  'cross_family_repeated_no_regression_evidence',
]);

export const RCA_FUNCTIONAL_STRUCTURE_FOLLOWTHROUGH_GAPS = Object.freeze([
]);

export const RCA_FUNCTIONAL_STRUCTURE_COMPLETED_GAPS = Object.freeze([
  'opl_generated_surface_production_consumption',
  'repo_local_wrapper_active_caller_migration',
  'focused_hosted_attempt_real_path_cutover',
  'artifact_gallery_handoff_shell',
  'review_repair_transport',
  'opl_app_operator_drilldown',
  'workspace_source_lifecycle_receipt_shell',
  'legacy_physical_cleanup',
]);

export const RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS = Object.freeze([
  {
    module_id: 'product_entry_session_store',
    surface_ref: '/session_continuity',
    status: 'opl_generated_workbench_session_surface_consumed',
    classification: 'split_owner_boundary',
    opl_generic_primitive: 'workbench_shell',
    oplAbsorbCandidate: true,
    rcaRetains: ['entry_session_domain_refs', 'deliverable_locator_refs', 'latest_visual_run_ref'],
    rca_scope: 'product_entry_session_domain_snapshot_refs',
    audit_readout: 'project_opl_session_shell_retain_domain_snapshot_refs',
    codePaths: [
      'packages/redcube-runtime/src/product-entry-session-snapshot-ref-adapter.ts',
      'packages/redcube-gateway/src/actions/get-product-entry-session.ts',
      'packages/redcube-gateway/src/actions/product-entry-continuity-surfaces.ts',
    ],
    activeCallers: [
      'redcube product session domain snapshot refs',
      'OPL generated session shell continuation target',
      'operator loop domain locator refs',
    ],
    activeCallerStatus: 'opl_generated_session_shell_domain_refs',
    migrationAction: 'Consume OPL/App generic session shell, resume token, operator navigation and workbench state; keep RCA entry-session domain snapshot refs only.',
    retentionReason: 'RCA retains entry_session_id to deliverable/topic/run locators and domain-specific continuation snapshot refs.',
    cannotAbsorbReason: 'OPL can own session shell UX but cannot own RCA deliverable truth, review/export gate or visual session authority.',
    tombstone_required: false,
  },
  {
    module_id: 'workspace_source_intake',
    surface_ref: '/source_intake',
    status: 'workspace_source_shell_bridge_with_exit_gate',
    classification: 'split_owner_boundary',
    opl_generic_primitive: 'workspace_source_intake_shell',
    oplAbsorbCandidate: true,
    rcaRetains: ['source_readiness_verdict', 'communication_strategy_inputs', 'visual_source_pack_refs'],
    rca_scope: 'visual_source_readiness_and_domain_source_pack_refs',
    audit_readout: 'project_opl_workspace_source_shell_retain_rca_source_verdict',
    codePaths: [
      'packages/redcube-gateway/src/actions/intake-source.ts',
      'packages/redcube-runtime/src/source-intake.ts',
      'packages/redcube-runtime/src/source-readiness-pack.ts',
      'packages/redcube-runtime/src/shared-source-truth.ts',
    ],
    activeCallers: [
      'OPL generated source wrapper invokes RCA source readiness handler',
      'source-first fanout source pack refs',
      'product-entry manifest source readiness refs',
    ],
    activeCallerStatus: 'opl_workspace_source_shell_domain_handler_refs',
    migrationAction: 'Move generic workspace locator, source receipt shell, material gap queue and provenance navigation to OPL.',
    retentionReason: 'RCA must judge visual source readiness, audience promise inputs and communication strategy source adequacy.',
    cannotAbsorbReason: 'OPL can host source transport but cannot own RCA source readiness verdict or narrative/visual source interpretation.',
    tombstone_required: false,
  },
  {
    module_id: 'memory_writeback_receipt_transport',
    surface_ref: '/controlled_memory_apply_proof',
    status: 'split_owner_boundary_landed',
    classification: 'split_owner_boundary',
    opl_generic_primitive: 'memory_refs_only_writeback_chain',
    oplAbsorbCandidate: true,
    rcaRetains: ['visual_memory_body', 'accept_reject_authority', 'memory_quality_judgment'],
    rca_scope: 'visual_memory_accept_reject_and_receipt_refs',
    audit_readout: 'project_opl_memory_transport_retain_visual_memory_authority',
    codePaths: [
      'packages/redcube-gateway/src/actions/standard-domain-agent-skeleton-parts/memory-apply-proof.ts',
      'packages/redcube-gateway/src/actions/product-sidecar.ts#apply_visual_memory_writeback',
      'packages/redcube-gateway/src/actions/get-product-entry-manifest-parts/workspace-receipt-inventory.ts',
    ],
    activeCallers: ['apply_visual_memory_writeback sidecar action', 'workspace receipt inventory', 'operator evidence readiness projection'],
    activeCallerStatus: 'active_refs_only_transport',
    migrationAction: 'Move body-free memory transport, freshness grouping and receipt inventory shell to OPL.',
    retentionReason: 'RCA owns visual pattern memory body, accept/reject decision and lesson quality semantics.',
    cannotAbsorbReason: 'OPL must not store visual memory body or decide whether a visual pattern is reusable for RCA deliverables.',
    tombstone_required: false,
  },
  {
    module_id: 'artifact_export_lifecycle',
    surface_ref: '/artifact_locator_contract',
    status: 'opl_artifact_lifecycle_shell_consumed_refs_only',
    classification: 'split_owner_boundary',
    opl_generic_primitive: 'artifact_lifecycle',
    oplAbsorbCandidate: true,
    rcaRetains: ['canonical_artifact_authority', 'export_verdict', 'artifact_mutation_permission'],
    rca_scope: 'visual_artifact_export_authority_and_locator_refs',
    audit_readout: 'project_opl_artifact_lifecycle_retain_rca_export_authority',
    codePaths: [
      'packages/redcube-gateway/src/actions/product-sidecar.ts#/mapped_surfaces/artifact_locator',
      'packages/redcube-gateway/src/actions/product-sidecar.ts#apply_visual_workspace_lifecycle',
      'packages/redcube-gateway/src/actions/get-product-entry-manifest-parts/manifest-return.ts',
    ],
    activeCallers: ['artifact locator contract', 'export_pptx route', 'workspace lifecycle guarded apply', 'product sidecar export'],
    activeCallerStatus: 'refs_only_artifact_authority_adapter_consuming_opl_lifecycle_shell',
    migrationAction: 'Consume OPL/App generic artifact inventory, gallery, restore/provenance navigation and handoff shell; keep RCA artifact authority and export verdict refs only.',
    retentionReason: 'RCA owns canonical visual artifacts, exportability verdict and artifact mutation permission.',
    cannotAbsorbReason: 'OPL may index artifact refs but cannot publish, mutate or declare RCA visual artifacts exportable.',
    tombstone_required: false,
  },
  {
    module_id: 'review_repair_transport',
    surface_ref: '/review_state',
    status: 'split_owner_boundary_landed',
    classification: 'split_owner_boundary',
    opl_generic_primitive: 'review_repair_transport',
    oplAbsorbCandidate: true,
    rcaRetains: ['visual_review_verdict', 'repair_decision', 'blocked_item_semantics'],
    rca_scope: 'visual_review_export_verdict_and_repair_decision',
    audit_readout: 'retain_domain_gate_project_transport_refs',
    codePaths: [
      'packages/redcube-gateway/src/actions/product-sidecar-parts/owner-boundary.ts',
      'packages/redcube-gateway/src/actions/product-sidecar.ts#/mapped_surfaces/review_projection',
      'packages/redcube-gateway/src/actions/product-sidecar-parts/visual-transition-evaluator.ts',
    ],
    activeCallers: ['visual director review', 'screenshot review', 'repair_image_pages', 'product sidecar review projection'],
    activeCallerStatus: 'active_domain_review_gate',
    migrationAction: 'Move blocked-item queue, rerun envelope, human approval lane and repair transport shell to OPL.',
    retentionReason: 'RCA owns visual review/export verdicts, blocked-item meaning and repair target selection.',
    cannotAbsorbReason: 'OPL transport cannot decide if a slide/page is visually acceptable, exportable or needs a specific RCA repair route.',
    tombstone_required: false,
  },
  {
    module_id: 'native_helper_envelope',
    surface_ref: '/native_ppt_operator_ux',
    status: 'split_owner_boundary_landed',
    classification: 'split_owner_boundary',
    opl_generic_primitive: 'native_helper_generic_envelope',
    oplAbsorbCandidate: true,
    rcaRetains: ['python_native_helper_implementation', 'ppt_image_export_mutation_logic', 'helper_specific_proof'],
    rca_scope: 'python_native_helper_implementation',
    audit_readout: 'retain_rca_implementation_project_opl_envelope',
    codePaths: [
      'packages/redcube-gateway/src/actions/get-product-entry-manifest-parts/native-ppt-operator-ux.ts',
      'contracts/runtime-program/python-native-helper-catalog.json',
      'python/redcube_ai',
    ],
    activeCallers: ['native PPT proof lane', 'author_pptx_native route', 'repair_pptx_native route', 'python native helper catalog tests'],
    activeCallerStatus: 'active_rca_native_implementation_package_module_only',
    migrationAction: 'Move helper registration, environment/provisioning metadata, execution receipt and operator-safe launch envelope to OPL.',
    retentionReason: 'RCA owns PPT/image/export helper implementation and route-specific mutation/review integration.',
    cannotAbsorbReason: 'OPL can standardize execution envelope but cannot own domain helper logic that mutates RCA visual artifacts.',
    tombstone_required: false,
  },
  {
    module_id: 'operator_projection_shell',
    surface_ref: '/operator_evidence_readiness_projection',
    status: 'opl_app_workbench_shell_bridge_with_exit_gate',
    classification: 'opl_owned_workbench_consumer_projection',
    opl_generic_primitive: 'workbench_shell',
    oplAbsorbCandidate: true,
    rcaRetains: ['operator_evidence_refs', 'domain_gap_semantics', 'safe_repair_hints'],
    rca_scope: 'rca_operator_projection_refs_only',
    audit_readout: 'project_opl_app_shell_retain_domain_gap_projection',
    codePaths: [
      'packages/redcube-gateway/src/actions/get-product-entry-manifest-parts/manifest-return.ts#/operator_evidence_readiness_projection',
      'packages/redcube-gateway/src/actions/get-product-status.ts',
      'packages/redcube-gateway/src/actions/product-sidecar.ts#/mapped_surfaces/operator_evidence_readiness_projection',
    ],
    activeCallers: [
      'OPL generated product status/workbench consumes RCA operator evidence refs',
      'product-entry manifest domain projection refs',
      'product sidecar export refs-only projection',
      'operator evidence readiness tests',
    ],
    activeCallerStatus: 'opl_app_workbench_shell_domain_evidence_refs',
    migrationAction: 'Move generic dashboard/workbench layout, attention queue, repair command projection and drilldown shell to OPL App.',
    retentionReason: 'RCA provides domain evidence refs, blocker meaning and safe repair hints for visual deliverable readiness.',
    cannotAbsorbReason: 'OPL App may render projections but cannot turn them into RCA visual ready/exportable claims.',
    tombstone_required: false,
  },
  {
    module_id: 'generic_cli_mcp_wrappers',
    surface_ref: '/family_action_catalog_parity',
    status: 'canonical_metadata_parity_landed',
    classification: 'opl_discoverable_projection_rca_owned_action_metadata',
    opl_generic_primitive: 'standard_domain_agent_scaffold',
    oplAbsorbCandidate: true,
    rcaRetains: ['rca_action_metadata', 'domain_action_handlers', 'safe_action_refs'],
    rca_scope: 'product_sidecar_status_action_metadata_projection',
    audit_readout: 'retain_thin_projection_project_generated_wrappers',
    codePaths: [
      'apps/redcube-cli/src/cli.ts',
      'apps/redcube-mcp/src/server.ts',
      'packages/redcube-gateway/src/actions/family-action-catalog.ts',
      'packages/redcube-gateway/src/actions/product-sidecar-guarded-actions.ts',
    ],
    activeCallers: [
      'OPL generated CLI/MCP wrapper domain handler targets',
      'redcube CLI direct diagnostic entry',
      'redcube MCP direct protocol adapter',
      'family action catalog refs',
      'product sidecar guarded action list refs',
    ],
    activeCallerStatus: 'opl_generated_wrappers_domain_handler_targets',
    migrationAction: 'Move generic wrapper generation, command surface registration and MCP action scaffolding to OPL standard domain-agent scaffold.',
    retentionReason: 'RCA retains canonical action metadata and domain handlers because they encode visual deliverable authority boundaries.',
    cannotAbsorbReason: 'OPL can generate wrappers but cannot own RCA action semantics or guarded sidecar handler authority.',
    tombstone_required: false,
  },
  {
    module_id: 'codex_executor_adapter',
    surface_ref: '/domain_entry_contract/executor',
    status: 'split_owner_boundary_landed',
    classification: 'opl_owned_executor_adapter_rca_default_executor_policy',
    opl_generic_primitive: 'agent_executor_adapter',
    oplAbsorbCandidate: true,
    rcaRetains: ['default_codex_executor_policy', 'route_executor_requirements', 'executor_receipt_refs'],
    rca_scope: 'route_level_executor_policy_and_receipt_refs',
    audit_readout: 'project_opl_executor_adapter_retain_rca_route_policy',
    codePaths: [
      'packages/redcube-runtime/src/executors.ts',
      'packages/redcube-gateway/src/actions/run-deliverable-route.ts',
      'packages/redcube-gateway/src/actions/domain-entry-contract.ts',
      'tests/rca-executor-backend-contract.test.ts',
    ],
    activeCallers: ['deliverable route runner', 'domain entry contract', 'runtime route executor tests'],
    activeCallerStatus: 'active_codex_cli_first_class_default',
    migrationAction: 'Move concrete executor lifecycle/provisioning/receipt adapter to OPL generic Agent Executor Adapter.',
    retentionReason: 'RCA keeps route-level executor requirements and Codex CLI as current first-class default for visual deliverables.',
    cannotAbsorbReason: 'OPL can provide executor adapter mechanics but cannot promise non-Codex outputs are visually equivalent for RCA routes.',
    tombstone_required: false,
  },
  {
    module_id: 'observability_stability_read_model',
    surface_ref: '/opl_stability_read_model_consumption',
    status: 'refs_only_consumer_projection_landed',
    classification: 'opl_owned_observability_stability_read_model_consumed_by_rca',
    opl_generic_primitive: 'runtime_observability_exporter',
    oplAbsorbCandidate: true,
    rcaRetains: ['domain_blocker_meaning', 'safe_repair_hint_refs', 'no_regression_evidence_refs'],
    rca_scope: 'visual_domain_status_projection_refs_only',
    audit_readout: 'project_only',
    codePaths: [
      'packages/redcube-gateway/src/actions/product-sidecar-guarded-actions.ts#/opl_stability_read_model_consumption',
      'packages/redcube-gateway/src/actions/get-product-status.ts',
      'packages/redcube-gateway/src/actions/product-sidecar.ts#/runtime_framework',
    ],
    activeCallers: ['product status', 'product sidecar runtime framework', 'operator evidence readiness projection'],
    activeCallerStatus: 'active_refs_only_consumer_projection',
    migrationAction: 'Keep observability exporter, SLO, control-loop summary, usage and resource-pressure aggregation in OPL.',
    retentionReason: 'RCA contributes domain blocker meaning, visual-safe repair hints and no-regression evidence refs.',
    cannotAbsorbReason: 'OPL observability cannot authorize RCA quality, exportability or visual remediation decisions.',
    tombstone_required: false,
  },
]);

const FUNCTIONAL_MODULE_MIGRATION_CLASSES = Object.freeze({
  product_entry_session_store: 'refs_only_adapter',
  workspace_source_intake: 'refs_only_adapter',
  memory_writeback_receipt_transport: 'refs_only_adapter',
  artifact_export_lifecycle: 'refs_only_adapter',
  review_repair_transport: 'refs_only_adapter',
  native_helper_envelope: 'native_helper_implementation',
  operator_projection_shell: 'refs_only_adapter',
  generic_cli_mcp_wrappers: 'domain_handler_target',
  codex_executor_adapter: 'refs_only_adapter',
  observability_stability_read_model: 'refs_only_adapter',
});

const FUNCTIONAL_MODULE_EXPECTED_MODES = Object.freeze({
  declarative_pack: 'declarative_pack_consumed_by_opl_hosted_surface',
  domain_handler_target: 'domain_handler_target_called_by_opl_generated_surface',
  refs_only_adapter: 'refs_only_adapter_to_opl_surface',
  minimal_authority_function: 'domain_authority_function_called_by_generated_surface',
  native_helper_implementation: 'native_helper_implementation_called_by_opl_envelope',
  provenance: 'provenance_or_retired_guard',
});

export function buildPrivatizedFunctionalModuleAuditProjection({
  familySchedulerReplacement = buildFamilySchedulerReplacementProjection(),
  oplGenericPrimitiveConsumption = null,
  oplStabilityReadModelConsumption = null,
} = {}) {
  const genericConsumption = oplGenericPrimitiveConsumption || buildOplGenericPrimitiveConsumptionProjection();
  const stabilityConsumption = oplStabilityReadModelConsumption || buildOplStabilityReadModelConsumptionProjection();
  return {
    ref: '/privatized_functional_module_audit',
    contract_ref: 'rca.privatized_functional_module_audit.v1',
    owner: 'redcube_ai',
    consumer: 'opl',
    status: 'machine_audit_projection_landed',
    projection_mode: 'module_boundary_audit_read_model',
    read_only: true,
    refs_only: true,
    audit_scope: [
      'OPL stage execution plan route handler refs',
      'product-entry session store',
      'workspace/source intake',
      'memory/writeback receipt transport',
      'artifact export lifecycle',
      'review/repair transport',
      'native helper envelope',
      'operator projection shell',
      'generic CLI/MCP wrappers',
      'generated CLI/MCP/product-entry/sidecar/status/session/workbench wrappers',
      'Codex executor adapter',
      'observability/stability read model',
    ],
    classification_values: [
      'domain_handler_target',
      'refs_only_adapter',
      'minimal_authority_function',
      'native_helper_implementation',
      'provenance',
    ],
    non_adapter_classification_values: [
      'declarative_pack',
    ],
    replacement_expectation_mode: 'opl_replacement_expectation_or_refs_only_projection',
    generated_interface_consumption_ref: OPL_GENERATED_INTERFACE_CONSUMPTION.ref,
    generated_interface_consumption: { ...OPL_GENERATED_INTERFACE_CONSUMPTION },
    functional_structure_gap_closure: {
      status: 'functional_structure_gaps_closed_evidence_gates_open',
      closed_at: '2026-05-17',
      closure_scope: 'rca_functional_structure_gap_classification',
      functional_structure_gap_count: RCA_FUNCTIONAL_STRUCTURE_FOLLOWTHROUGH_GAPS.length,
      completed_functional_structure_gap_count: RCA_FUNCTIONAL_STRUCTURE_COMPLETED_GAPS.length,
      completed_functional_structure_gap_ids: [...RCA_FUNCTIONAL_STRUCTURE_COMPLETED_GAPS],
      unclassified_private_generic_residue_count: 0,
      long_term_rca_generic_owner_claim_count: 0,
      remaining_gap_class: 'none',
      remaining_functional_structure_gap_ids: [...RCA_FUNCTIONAL_STRUCTURE_FOLLOWTHROUGH_GAPS],
      remaining_functional_structure_gaps: RCA_FUNCTIONAL_STRUCTURE_FOLLOWTHROUGH_GAPS.map((gapId) => ({
        gap_id: gapId,
        current_bucket: 'functional_structure_gap',
        owner: 'one-person-lab',
        rca_role: 'domain_handler_target_or_visual_authority_refs_only',
      })),
      evidence_gap_class: 'production_live_soak_evidence_only',
      remaining_evidence_gate_ids: [...RCA_REMAINING_EVIDENCE_GATES],
      closure_basis_refs: [
        '/family_scheduler_replacement',
        '/opl_generic_primitive_consumption',
        '/opl_stability_read_model_consumption',
        '/opl_generated_interface_consumption',
        '/visual_pack_compiler_handoff',
        '/operator_evidence_readiness_projection',
        '/opl_substrate_adapter_export',
      ],
      allowed_remaining_module_classes: [
        'domain_handler_target',
        'refs_only_adapter',
        'declarative_pack',
        'minimal_authority_function',
        'native_helper_implementation',
        'provenance',
      ],
    },
    physical_deletion_guard: {
      current_safe_tombstone_candidate_count: 0,
      deleted_or_thinned_default_surfaces: [
        'retired_product_sidecar.supervision_action_tombstone',
        'retired_product_sidecar.continuation_action_tombstone',
        'retired_public_entry.run_lookup_tombstone',
        'retired_public_entry.supervision_lookup_tombstone',
        'retired_repo_local_visual_loop.deliverable_runner_deleted',
        'retired_repo_local_visual_loop.run_store_deleted',
        'retired_repo_local_visual_loop.dag_runner_deleted',
      ],
      deletion_status: 'legacy_runtime_physical_cleanup_closed',
      remaining_deletion_scope: 'Only visual authority functions, refs-only projections, and declared visual pack inputs remain in RCA package surfaces.',
      required_before_remaining_physical_delete: [],
    },
    bridge_exit_gate: buildPrivateGenericResidueBridgeExitGate(RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS),
    forbidden_generic_owner_flags: { ...FUNCTIONAL_MODULE_FORBIDDEN_OWNER_FLAGS },
    rca_visual_authority_allowlist: [
      'source_readiness_verdict',
      'communication_visual_direction_decision',
      'review_export_verdict',
      'artifact_mutation_authorization',
      'visual_memory_accept_reject',
      'owner_receipt_signer',
      'native_helper_implementation',
    ],
    visual_pack_compiler_handoff_ref: '/visual_pack_compiler_handoff',
    modules: RCA_PRIVATIZED_FUNCTIONAL_MODULE_AUDIT_ITEMS.map((entry) => {
      const replacementGuard = RCA_FUNCTIONAL_MODULE_REPLACEMENT_GUARDS[entry.module_id] || {};
      const migrationClass = FUNCTIONAL_MODULE_MIGRATION_CLASSES[entry.module_id] || 'refs_only_adapter';
      return {
        ...entry,
        migration_class: migrationClass,
        active_reader_facing_classification: migrationClass,
        opl_owned_generic_primitive_consumer: true,
        rca_owned_visual_domain_authority: [
          'workspace_source_intake',
          'memory_writeback_receipt_transport',
          'artifact_export_lifecycle',
          'review_repair_transport',
          'native_helper_envelope',
          'generic_cli_mcp_wrappers',
          'codex_executor_adapter',
        ].includes(entry.module_id),
        opl_absorb_candidate: entry.oplAbsorbCandidate === true,
        opl_replacement_expectation: {
          owner: 'opl',
          expectation_ref: replacementGuard.expectation_ref || '/opl_generic_primitive_consumption',
          replacement_surface: replacementGuard.opl_replacement_surface || entry.opl_generic_primitive,
          expected_mode: FUNCTIONAL_MODULE_EXPECTED_MODES[migrationClass] || 'refs_only_adapter_to_opl_surface',
          rca_consumes_as: 'consumer_projection_only',
          rca_owns_replacement_runtime: false,
        },
        bridge_exit_gate: buildBridgeExitGate(entry, replacementGuard),
        rca_projection_mode: replacementGuard.rca_projection_mode || 'refs_only_projection',
        rca_exports_only: replacementGuard.rca_exports_only || [],
        forbidden_generic_owner_flags: { ...FUNCTIONAL_MODULE_FORBIDDEN_OWNER_FLAGS },
        physical_deletion_guard: buildFunctionalModulePhysicalDeletionGuard(entry),
        rca_retains: entry.rcaRetains || [],
        repo_local_handler_target_only: entry.module_id === 'generic_cli_mcp_wrappers' ? true : undefined,
        generated_surface_metadata_owner: entry.module_id === 'generic_cli_mcp_wrappers' ? 'one-person-lab' : undefined,
        generated_session_shell_owner: entry.module_id === 'product_entry_session_store' ? 'one-person-lab' : undefined,
        retire_tombstone: false,
        writes_visual_truth: false,
        writes_artifact_blob: false,
        writes_memory_body: false,
        declares_visual_ready: false,
        declares_exportable: false,
        declares_handoffable: false,
        declares_production_soak_complete: false,
      };
    }).concat([
      buildVisualPackCompilerHandoffAuditModule(),
      buildVisualAuthorityFunctionsAuditModule(),
    ]),
    opl_owned_generic_primitives: [
      ...new Set([
        ...(familySchedulerReplacement.opl_owned_generic_surfaces || []),
        ...(genericConsumption.opl_owned_generic_primitives || []),
        ...(stabilityConsumption.rca_does_not_own || []),
      ]),
    ],
    opl_generated_interface_consumption: { ...OPL_GENERATED_INTERFACE_CONSUMPTION },
    rca_retained_authority: [...RCA_RETAINED_VISUAL_AUTHORITY],
    protected_rca_surfaces: [
      'visual_deliverable_internal_dag',
      'visual_truth',
      'review_export_verdict',
      'repair_decision',
      'artifact_authority',
      'visual_memory_body',
      'owner_receipt',
      'native_helper_implementation',
    ],
    retired_no_resurrection_guards: [
      {
        surface_id: 'retired_product_sidecar.supervision_action_tombstone',
        retired_legacy_surface_id: 'product_sidecar_dispatch.retired_managed_supervision',
        retired_at: '2026-05-17',
        replacement_owner: 'opl',
        replacement_surface: 'opl_generic_runner_and_supervisor_tick',
        retained_rca_surface: null,
        active_default_caller: false,
        active_caller: false,
        compatibility_alias_allowed: false,
        resurrection_policy: 'forbidden',
      },
      {
        surface_id: 'retired_product_sidecar.continuation_action_tombstone',
        retired_legacy_surface_id: 'product_sidecar_dispatch.product_entry_continuation',
        retired_at: '2026-05-17',
        replacement_owner: 'opl',
        replacement_surface: 'opl_generated_session_shell_and_product_entry_wrapper',
        retained_rca_surface: 'direct product entry invoke/session surfaces',
        active_default_caller: false,
        active_caller: false,
        compatibility_alias_allowed: false,
        resurrection_policy: 'forbidden',
      },
    ],
    must_not_retire: [
      'visual_stage_descriptor',
      'visual_review_export_gate',
      'native_helper_implementation',
      'artifact_gallery_export_refs',
      'codex_cli_default_route_policy',
    ],
    authority_boundary: {
      opl_can_index_audit_projection: true,
      opl_can_import_generic_primitives: true,
      opl_can_write_rca_visual_truth: false,
      opl_can_write_rca_artifact_blob: false,
      opl_can_write_rca_memory_body: false,
      opl_can_declare_visual_ready: false,
      opl_can_declare_exportable: false,
      opl_can_declare_handoffable: false,
      opl_can_claim_production_soak_complete: false,
      rca_generic_scheduler_owner: false,
      rca_native_helper_generic_envelope_owner: false,
      rca_artifact_lifecycle_owner: false,
      rca_review_repair_transport_owner: false,
      rca_observability_export_owner: false,
    },
  };
}

export { buildVisualPackCompilerHandoffProjection };

export function listProductSidecarGuardedActions() {
  return SIDECAR_GUARDED_ACTIONS.map((entry) => ({ ...entry }));
}

export function listProductSidecarGuardedActionIds() {
  return SIDECAR_GUARDED_ACTIONS.map((entry) => entry.action);
}

export function productSidecarGuardedActionSet() {
  return new Set(listProductSidecarGuardedActionIds());
}

export function listProductSidecarForbiddenWrites() {
  return [...SIDECAR_FORBIDDEN_WRITES];
}

export function listProductSidecarBlockedActions() {
  return [...SIDECAR_BLOCKED_ACTIONS];
}
