type JsonRecord = Record<string, any>;
type NativePptRoute = 'author_pptx_native' | 'repair_pptx_native';

const SAMPLE_STATUS_PROOF_BOARD = Object.freeze({
  archetype_id: 'sample_status_proof_board',
  use_when: 'one-slide sample with three compact status items and one proof band',
  layout_description: 'title+claim, shared hub -> 3 route cards -> proof band',
  required_zones: ['title_zone', 'claim_zone', 'status_zone', 'proof_zone'],
  content_schema: {
    required_shape_roles: ['title', 'core_sentence', 'input_hub', 'flow_connector', 'content_panel', 'point_text', 'proof_band', 'evidence_item'],
    required_shape_role_groups: ['title_text', 'core_claim_text', 'input_hub', 'flow_connector', 'content_container', 'audience_body_text', 'structural_visual', 'evidence_or_metric_text'],
    min_filled_required_zone_share: 1,
    max_audience_text_shapes: 8,
    exact_status_card_count: 3,
    status_card_layout: 'horizontal_row_required',
    status_card_width_in_min: 4.0,
    status_card_height_in_min: 1.35,
    status_card_quality_role_required: 'content',
    status_card_text_box_height_in_min: 0.96,
	    status_card_point_text_max_estimated_lines: 2,
	    status_card_point_text_min_cjk_chars: 12,
	    status_card_point_text_max_cjk_chars: 22,
	    status_card_separate_route_label_allowed: false,
	    status_card_single_point_text_required: true,
	    status_zone_height_in_min: 3.45,
    input_hub_label_min_cjk_chars: 12,
    input_hub_label_max_cjk_chars: 16,
    input_hub_label_min_cjk_chars_when_content: 12,
    input_hub_label_height_in_min: 0.54,
    input_hub_label_width_in_min: 10.4,
    input_hub_width_in_min: 10.4,
    input_hub_height_in_min: 0.82,
    input_hub_font_pt_min: 22,
    input_hub_centered_over_route_row_required: true,
    input_hub_spans_route_card_centers_required: true,
    input_hub_center_tolerance_in: 0.35,
    connector_thickness_in_min: 0.03,
    connector_vertical_width_in_max: 0.04,
    connector_vertical_height_in_min: 0.66,
    connector_hub_gap_in_max: 0.12,
    horizontal_connector_bus_allowed: false,
    connector_text_clearance_in_min: 0.12,
    connector_lane_must_stay_inside_declared_zone: true,
    input_hub_card_flow_geometry_required: true,
    connector_card_center_tolerance_in: 0.22,
    route_card_connector_landing_required: 'exactly 3 vertical arrows: hub bottom to card top centers',
    route_card_connector_kind_required: 'connector',
    connector_direction_required: 'tailEnd=triangle | tailEnd=arrow | line.end_arrow=true',
    proof_zone_height_in_min: 1.35,
    core_sentence_height_in_min: 0.95,
    evidence_item_height_in_min: 0.84,
    proof_zone_text_block_count_max: 1,
    boundary_note_visible_text_allowed: false,
    min_body_font_pt: 18,
    first_glance_flow_required: 'input_hub_to_cards_to_proof_band',
  },
  prohibited: [
    'takeaway_zone',
    'takeaway_panel',
    'separate takeaway text',
    'evidence axis over evidence text',
    'artifact inventory',
    'connector-heavy flow map',
  ],
});

const SAMPLE_DECISION_PROOF_SPLIT = Object.freeze({
  archetype_id: 'sample_decision_proof_split',
  use_when: 'one-slide sample with dominant decision plus proof stack',
  layout_description: 'title+claim, left decision, right proof, rail, bottom takeaway',
  required_zones: ['title_zone', 'claim_zone', 'decision_zone', 'proof_zone', 'takeaway_zone'],
  content_schema: {
    required_shape_roles: ['title', 'core_sentence', 'decision_rail', 'content_panel', 'point_text', 'proof_band', 'metric', 'takeaway'],
    required_shape_role_groups: ['title_text', 'core_claim_text', 'decision_rail', 'content_container', 'audience_body_text', 'structural_visual', 'evidence_or_metric_text', 'takeaway_text'],
    min_filled_required_zone_share: 1,
    max_audience_text_shapes: 8,
    max_bottom_text_blocks: 1,
    min_body_font_pt: 18,
  },
  prohibited: [
    'status cards plus extra proof/takeaway bands',
    'artifact inventory',
    'connector-heavy flow map',
  ],
});

const PROFESSIONAL_DESIGN_PACK_CONTRACT = Object.freeze({
  required: true,
  creative_owner: 'llm_agent',
  materializer_can_select_layout: false,
  layout_archetype_taxonomy: [
    { archetype_id: 'flow_hub_to_cards_proof_band' },
    { archetype_id: 'decision_split_with_proof_stack' },
    { archetype_id: 'system_map_with_gate_stack' },
    { archetype_id: 'evidence_timeline_rail' },
    { archetype_id: 'risk_control_matrix' },
    { archetype_id: 'executive_status_board' },
  ],
  capacity_budgets: {
    body_font_pt_min: 18,
    card_width_in_min: 4.0,
    card_height_in_min: 1.35,
  },
  connector_semantics: {
    real_ppt_connector_required: true,
    horizontal_bus_for_route_cards_allowed: false,
  },
  design_reference_discipline: {
    source_projects: ['ppt-master', 'PPTAgent', 'officecli-pptx', 'presenton', 'ppt-agent-skills'],
  },
});

export function buildNativeSampleShapePlanOutputContract({
  aiFirstEditingContract,
  route,
  sampleProfile = null,
}: {
  aiFirstEditingContract: JsonRecord;
  route: NativePptRoute;
  sampleProfile?: JsonRecord | null;
}) {
  const safeZoneBlueprints = sampleProfile?.safe_zone_blueprints && typeof sampleProfile.safe_zone_blueprints === 'object'
    ? sampleProfile.safe_zone_blueprints
    : null;
  return {
    ai_first_editing_contract: aiFirstEditingContract,
    editable_shape_plan: {
      contract_kind: 'redcube_ai_first_native_ppt_shape_plan',
      route,
      authoring_mode: 'native_visual_sample_compact',
      scope: 'deck_authoring',
      target_slide_ids: ['S01'],
      authoring_ir: {
        kind: 'redcube_svg_ir',
        version: 1,
        required: true,
        strict_svg_preflight_required: true,
        allowed_svg_tags: ['svg', 'g', 'rect', 'text'],
        unsupported_svg_tags: ['image', 'foreignObject', 'script'],
      },
      materializer: {
        kind: 'officecli_pptx_materializer',
        role: 'execute_ai_spatial_plan_only',
        helper_template_layout_allowed: false,
        officecli_gate_required: ['save', 'validate', 'view_issues', 'view_text'],
      },
      professional_design_pack_contract: PROFESSIONAL_DESIGN_PACK_CONTRACT,
      structural_contract: {
        contract_kind: 'native_pptx_ai_first_structural_plan_v1',
        required: true,
        enforcement: 'bounded_repair_then_materialize_best_available_or_diagnostic',
        ai_authoring_owner: 'llm_agent',
        materializer_inference_allowed: false,
        required_top_level_fields: ['design_spec_lock', 'deck_layout_rhythm_plan', 'template_layout_grammar', 'slides'],
        per_slide_required_fields: ['slide_id', 'layout_intent', 'template_layout_binding', 'native_shapes'],
        slide_binding_required_before_shapes: true,
        shape_zone_binding_required: true,
        sample_archetype_only: true,
      },
      deck_layout_rhythm_plan: {
        required: true,
        owner: 'llm_agent',
        slides_array_required: true,
        slides: [{
          slide_id: 'S01',
          rhetorical_role: '<role>',
          selected_archetype: 'sample_status_proof_board | sample_decision_proof_split',
          primary_grid: '<grid>',
          composition_signature_budget: '<composition>',
          proof_object: '<visible proof object>',
        }],
        rules: {
          every_slide_needs_a_proof_object: true,
          no_empty_placeholder_slots: true,
          single_slide_sample_accepts_one_archetype: true,
        },
      },
      template_layout_grammar: {
        grammar_id: 'native_pptx_template_layout_grammar_v1',
        owner: 'llm_agent',
        required: true,
        materializer_role: 'execute_selected_archetype_zones_only',
        helper_template_layout_allowed: false,
        reference_discipline: {
          template_profile_required: true,
          semantic_layout_selection_required: true,
          placeholder_capacity_required: true,
          reference_deck_analysis_required: true,
          action_title_required: true,
          source_projects: ['ppt-master', 'PPTAgent', 'officecli-pptx', 'presenton', 'ppt-agent-skills'],
          rule: 'Zones before coords.',
        },
        canvas_in: { width: 16, height: 9 },
        global_rules: {
          edge_margin_in_min: 0.6,
          zone_gap_in_min: 0.32,
          zone_inset_in_min: 0.15,
          selected_archetype_required_before_shapes: true,
          every_content_shape_must_bind_to_layout_zone: true,
          every_structural_shape_must_bind_to_layout_zone: true,
          connector_lane_must_be_separate_from_text_zones: true,
          empty_placeholder_slots_allowed: false,
          safe_zone_blueprint_must_be_used_before_coordinates: Boolean(safeZoneBlueprints),
        },
        archetype_catalog: [
          SAMPLE_STATUS_PROOF_BOARD,
          SAMPLE_DECISION_PROOF_SPLIT,
        ],
        compact_sample_catalog_rule: 'Catalog: two sample archetypes only; sample_proof_band is a role.',
        safe_zone_blueprints: safeZoneBlueprints,
        safe_zone_blueprint_rule: safeZoneBlueprints
          ? 'Copy tuple zones; hub spans card centers; use exactly 3 vertical connector drops.'
          : null,
        slide_binding_contract: {
          required_fields: ['selected_archetype', 'archetype_instance_id', 'rhythm_role', 'zones'],
          zone_required_fields: ['zone_id', 'semantic_role', 'bounds', 'intended_content', 'min_font_pt', 'safe_inset_in'],
          shape_binding_field: 'layout_zone_id',
          acceptance_rule: 'All non-decorative/non-auxiliary shapes bind to a declared sample zone and remain inside it.',
        },
        native_shape_style_schema: {
          required_text_fields: ['editable_text', 'font_size'],
          optional_text_fields: ['font', 'font_ea', 'color', 'bold', 'align', 'valign', 'margin_in'],
          forbidden_nested_style_fields: ['font.size_pt', 'font.family', 'text.margin_*'],
          rule: 'top-level font_size/margin_in only.',
        },
      },
      sample_capacity_contract: {
        required: true,
        allowed_selected_archetypes: ['sample_status_proof_board', 'sample_decision_proof_split'],
        forbidden_selected_archetypes: ['executive_status_board', 'decision_dashboard', 'professional_system_map', 'evidence_timeline', 'risk_control_matrix'],
        forbidden_catalog_archetypes: ['sample_proof_band', 'partial_component_archetype'],
        evidence_text_rule: 'compact sentence only; refs metadata-only',
        structural_visual_required: true,
        helper_layout_fallback_allowed: false,
        safe_zone_blueprints_required_before_coordinates: Boolean(safeZoneBlueprints),
      },
      design_spec_lock: {
        spec_id: 'native_pptx_sample_spec_lock_v1',
        owner: 'llm_agent',
        required: true,
        source: 'visual_direction_plus_one_target_slide_blueprint',
        canvas_in: { width: 16, height: 9 },
        palette: {
          canvas: '<hex>',
          ink: '<hex>',
          accent: '<hex>',
          panel: '<hex>',
        },
        motif: '<one sample visual motif used without title underlines>',
        layout_archetypes: ['sample_status_proof_board', 'sample_decision_proof_split'],
        forbidden_motifs: ['decorative_title_underline', 'empty_four_card_template', 'general_deck_archetype_substitution'],
        typography: {
          title_pt_min: 40,
          title_pt_range: [40, 44],
          body_pt_min: 18,
          title_body_ratio_min: 2.0,
        },
        grid: {
          edge_margin_in_min: 0.6,
          inter_block_gap_in_min: 0.32,
        },
        layout_rhythm: {
          repeated_concrete_composition_limit: 1,
          required_distinct_composition_share: 1,
        },
        professional_design_brief: {
          design_register: 'executive proof board',
          reference_style_family: 'proof board',
          first_glance_hierarchy: 'title/claim -> hub -> 3 routes -> proof',
          template_profile_strategy: 'semantic zones + capacity floors',
          capacity_strategy: 'fit hub/cards/proof before coords',
          forbidden_amateur_patterns: ['generic card grid', 'artifact ledger', 'title underline'],
        },
        borrowed_principles: [
          'ppt_master_style_spec_lock',
          'template_layout_grammar',
          'template_profile',
          'semantic_layout_selection',
          'reference_deck_analysis',
          'per_page_visual_plan',
          'layout_rhythm',
          'rendered_quality_gate',
        ],
        qa_gates: ['bounds', 'font_floor', 'text_fit', 'structural_visual', 'slot_fill', 'layout_variety', 'true_render_screenshot'],
      },
      slides: [
        {
          slide_id: 'S01',
          layout_intent: {
            required_fields: ['rhetorical_role', 'composition_signature', 'primary_grid', 'visual_weight', 'negative_space_strategy', 'non_text_visual', 'forbidden_template_reuse_checked'],
          },
          template_layout_binding: {
            selected_archetype: 'sample_status_proof_board | sample_decision_proof_split',
            required: true,
            zone_gap_in_min: 0.32,
            zone_inset_in_min: 0.15,
          },
          native_shapes: {
            allowed_kind_values: ['text_box', 'shape', 'rect', 'rounded_rect', 'oval', 'line', 'connector', 'picture', 'group', 'path', 'chart', 'table', 'metric_grid'],
            required_fields: ['shape_id', 'kind', 'role', 'quality_role', 'layout_zone_id', 'bounds'],
            text_shape_required_fields: ['editable_text', 'font_size'],
            style_schema_rule: 'Use top-level font_size/margin_in; no nested font/text style.',
            text_bearing_shapes_require_editable_text: true,
            structural_roles: ['input_hub', 'flow_connector', 'proof_band', 'decision_rail', 'proof_rail'],
          },
        },
      ],
    },
  };
}

export function buildNativeShapePlanOutputContract({
  aiFirstEditingContract,
  route,
}: {
  aiFirstEditingContract: JsonRecord;
  route: NativePptRoute;
}) {
    return {
      ai_first_editing_contract: aiFirstEditingContract,
      editable_shape_plan: {
        contract_kind: 'redcube_ai_first_native_ppt_shape_plan',
        route,
        scope: route === 'repair_pptx_native' ? 'page_repair' : 'deck_authoring',
        target_slide_ids: ['S02'],
        authoring_ir: {
          kind: 'redcube_svg_ir',
          version: 1,
          required: true,
          strict_svg_preflight_required: true,
          allowed_svg_tags: ['svg', 'g', 'rect', 'text'],
          unsupported_svg_tags: ['image', 'foreignObject', 'script'],
        },
        materializer: {
          kind: 'officecli_pptx_materializer',
          role: 'execute_ai_spatial_plan_only',
          helper_template_layout_allowed: false,
          officecli_gate_required: ['save', 'validate', 'view_issues', 'view_text'],
        },
        professional_design_pack_contract: PROFESSIONAL_DESIGN_PACK_CONTRACT,
        structural_contract: {
          contract_kind: 'native_pptx_ai_first_structural_plan_v1',
          required: true,
          enforcement: 'bounded_repair_then_materialize_best_available_or_diagnostic',
          ai_authoring_owner: 'llm_agent',
          materializer_inference_allowed: false,
          required_top_level_fields: [
            'design_spec_lock',
            'deck_layout_rhythm_plan',
            'template_layout_grammar',
            'slides',
          ],
          per_slide_required_fields: [
            'slide_id',
            'layout_intent',
            'template_layout_binding',
            'native_shapes',
          ],
          slide_binding_required_before_shapes: true,
          shape_zone_binding_required: true,
          slide_acceptance_rule: 'Every returned slide object must include template_layout_binding as a sibling field before native_shapes. The binding must select a catalog archetype, declare semantic zones, and every non-decorative/non-auxiliary native_shape, including structural rails, connectors, bands, axes, hubs, panels, and audience text, must set layout_zone_id to one of those zones.',
          forbidden_partial_outputs: [
            'native_shapes without sibling template_layout_binding',
            'layout_zone_id values without declared zones',
            'asking officecli or Python to infer template zones',
          ],
        },
        deck_layout_rhythm_plan: {
          required: true,
          owner: 'llm_agent',
          purpose: 'Plan the contact-sheet rhythm before individual coordinates so native pages do not collapse into repeated card grids.',
          slides_array_required: true,
          slides: [{
            slide_id: '<slide id>',
            rhetorical_role: '<role>',
            selected_archetype: '<archetype>',
            primary_grid: '<grid>',
            composition_signature_budget: '<composition>',
            proof_object: '<visible proof object>',
          }],
          rules: {
            consecutive_same_selected_archetype_max: 2,
            consecutive_same_primary_grid_max: 2,
            distinct_composition_signature_share_min: 0.75,
            min_distinct_archetypes_for_decks_5_slides_or_more: 3,
            every_slide_needs_a_proof_object: true,
            no_empty_placeholder_slots: true,
          },
        },
        template_layout_grammar: {
          grammar_id: 'native_pptx_template_layout_grammar_v1',
          owner: 'llm_agent',
          required: true,
          purpose: 'Choose a professional editable-PPT layout archetype and semantic zones before emitting coordinates.',
          materializer_role: 'execute_selected_archetype_zones_only',
          helper_template_layout_allowed: false,
          source: 'claim_spine_plus_visual_direction_plus_slide_blueprint',
          reference_discipline: {
            template_profile_required: true,
            semantic_layout_selection_required: true,
            placeholder_capacity_required: true,
            reference_deck_analysis_required: true,
            action_title_required: true,
            source_projects: ['ppt-master', 'PPTAgent', 'officecli-pptx', 'presenton', 'ppt-agent-skills'],
            rule: 'Treat templates and reference decks as layout intelligence before coordinates: infer semantic zones, placeholder capacity, spacing rhythm, and action-title hierarchy.',
          },
          canvas_in: { width: 16, height: 9 },
          global_rules: {
            edge_margin_in_min: 0.6,
            zone_gap_in_min: 0.32,
            zone_inset_in_min: 0.15,
            selected_archetype_required_before_shapes: true,
            every_content_shape_must_bind_to_layout_zone: true,
            every_structural_shape_must_bind_to_layout_zone: true,
            connector_lane_must_be_separate_from_text_zones: true,
            empty_placeholder_slots_allowed: false,
            repeated_concrete_archetype_limit: 2,
            contact_sheet_rhythm_required: true,
          },
          archetype_catalog: [
            {
              archetype_id: 'sample_status_proof_board',
              use_when: 'native_visual_sample one-slide proof when the page needs three compact status items and a single proof band',
              layout_description: 'Title/claim, shared hub, three route cards, connector arrows, one proof band.',
              required_zones: ['title_zone', 'claim_zone', 'status_zone', 'proof_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'input_hub', 'flow_connector', 'content_panel', 'point_text', 'proof_band', 'evidence_item'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'input_hub', 'flow_connector', 'content_container', 'audience_body_text', 'structural_visual', 'evidence_or_metric_text'],
                min_filled_required_zone_share: 1,
                max_audience_text_shapes: 8,
                max_bottom_text_blocks: 1,
                exact_status_card_count: 3,
                status_card_width_in_min: 4.0,
                status_card_height_in_min: 1.35,
                status_card_quality_role_required: 'content',
                status_card_text_box_height_in_min: 0.96,
                status_card_point_text_max_estimated_lines: 2,
                status_card_point_text_min_cjk_chars: 12,
                status_card_point_text_max_cjk_chars: 22,
                status_zone_height_in_min: 3.45,
                input_hub_label_min_cjk_chars: 12,
                input_hub_label_max_cjk_chars: 16,
                input_hub_label_min_cjk_chars_when_content: 12,
                input_hub_label_height_in_min: 0.54,
                input_hub_label_width_in_min: 10.4,
                input_hub_width_in_min: 10.4,
                input_hub_height_in_min: 0.82,
                input_hub_font_pt_min: 22,
                input_hub_centered_over_route_row_required: true,
                input_hub_spans_route_card_centers_required: true,
                input_hub_center_tolerance_in: 0.35,
                connector_thickness_in_min: 0.03,
                connector_vertical_width_in_max: 0.04,
                connector_vertical_height_in_min: 0.66,
                connector_hub_gap_in_max: 0.12,
                horizontal_connector_bus_allowed: false,
                connector_text_clearance_in_min: 0.12,
                connector_lane_must_stay_inside_declared_zone: true,
                input_hub_card_flow_geometry_required: true,
                connector_card_center_tolerance_in: 0.22,
                route_card_connector_kind_required: 'connector',
                route_card_connector_landing_required: 'exactly 3 vertical arrows: hub bottom to card top centers',
                connector_direction_required: 'tailEnd=triangle | tailEnd=arrow | line.end_arrow=true',
                proof_zone_height_in_min: 1.35,
                core_sentence_height_in_min: 0.95,
                evidence_item_height_in_min: 0.84,
                proof_zone_text_block_count_max: 1,
                boundary_note_visible_text_allowed: false,
                min_body_font_pt: 18,
                first_glance_flow_required: 'input_hub_to_three_route_cards_to_proof_band',
              },
              prohibited: [
                'takeaway_zone',
                'takeaway_panel',
                'separate bottom takeaway text',
                'evidence axis over evidence text',
                'artifact inventory receipts',
                'connector-heavy flow map',
              ],
            },
            {
              archetype_id: 'sample_decision_proof_split',
              use_when: 'native_visual_sample one-slide proof when the slide needs a dominant decision and a separate proof stack',
              layout_description: 'Title/claim, left decision panel, right proof stack, rail, bottom takeaway.',
              required_zones: ['title_zone', 'claim_zone', 'decision_zone', 'proof_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'decision_rail', 'content_panel', 'point_text', 'proof_band', 'metric', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'decision_rail', 'content_container', 'audience_body_text', 'structural_visual', 'evidence_or_metric_text', 'takeaway_text'],
                min_filled_required_zone_share: 1,
                max_audience_text_shapes: 8,
                max_bottom_text_blocks: 1,
                min_body_font_pt: 18,
              },
              prohibited: [
                'three equal status cards plus separate proof and takeaway bands',
                'artifact inventory receipts',
                'connector-heavy flow map',
              ],
            },
            {
              archetype_id: 'professional_system_map',
              use_when: 'workflow, route, system, gate, or evidence flow needs to be understood at a glance',
              layout_description: 'Claim and title above an editable system map; route lanes, gate stack, and evidence band occupy distinct semantic zones with connector lanes outside text.',
              required_zones: ['title_zone', 'claim_zone', 'system_map_zone', 'gate_zone', 'evidence_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'system_map_panel', 'route_label', 'gate_card', 'evidence_item'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'structural_visual', 'gate_or_route_label', 'evidence_or_metric_text'],
                min_filled_required_zone_share: 0.8,
                max_audience_text_shapes: 12,
                min_body_font_pt: 18,
              },
              prohibited: ['connector crossing readable text', 'three narrow route cards', 'labels placed on rails'],
            },
            {
              archetype_id: 'executive_status_board',
              use_when: 'one-slide status proof or decision summary',
              layout_description: 'Large status cards or panels in the middle with a separate proof/takeaway band; suitable for a low-density executive slide.',
              required_zones: ['title_zone', 'claim_zone', 'status_zone', 'evidence_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'content_panel', 'point_text', 'evidence_item', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'content_container', 'audience_body_text', 'takeaway_text'],
                min_filled_required_zone_share: 0.8,
                max_audience_text_shapes: 12,
                min_card_width_in: 3.3,
                min_card_height_in: 1.55,
              },
              prohibited: ['receipt label pile', 'empty four-card grid', 'tiny KPI badges'],
            },
            {
              archetype_id: 'evidence_timeline',
              use_when: 'sequence, milestone, or proof evolution',
              layout_description: 'Horizontal or vertical timeline rail with milestone nodes, labels placed off the rail, and proof/takeaway zones separated from the sequence.',
              required_zones: ['title_zone', 'claim_zone', 'timeline_zone', 'evidence_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'timeline_panel', 'point_text', 'evidence_item', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'timeline_marker', 'audience_body_text', 'evidence_or_metric_text'],
                min_filled_required_zone_share: 0.8,
                max_milestone_count: 4,
                min_body_font_pt: 18,
              },
              prohibited: ['timeline rail through labels', 'milestone text below 18pt'],
            },
            {
              archetype_id: 'risk_control_matrix',
              use_when: 'compare risks, controls, gates, or quality criteria',
              layout_description: 'Matrix or comparison field with filled cells, clear row/column grammar, and a separate signal or takeaway area.',
              required_zones: ['title_zone', 'claim_zone', 'matrix_zone', 'signal_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'compare_panel', 'point_text', 'metric', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'matrix_or_compare_container', 'audience_body_text', 'evidence_or_metric_text'],
                min_filled_required_zone_share: 0.8,
                empty_cell_allowed: false,
                min_body_font_pt: 18,
              },
              prohibited: ['unfilled matrix cell', 'four-card template with fewer than four facts'],
            },
            {
              archetype_id: 'decision_dashboard',
              use_when: 'decision, recommendation, operating readout, or proof dashboard',
              layout_description: 'A decision or recommendation zone with supporting proof objects; visual hierarchy starts from the decision, not equal cards.',
              required_zones: ['title_zone', 'claim_zone', 'decision_zone', 'proof_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'content_panel', 'point_text', 'metric', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'content_container', 'evidence_or_metric_text', 'takeaway_text'],
                min_filled_required_zone_share: 0.8,
                first_glance_hierarchy_required: true,
                min_body_font_pt: 18,
              },
              prohibited: ['all content in equal cards', 'no first-glance hierarchy'],
            },
          ],
          slide_binding_contract: {
            required_fields: ['selected_archetype', 'archetype_instance_id', 'rhythm_role', 'zones'],
            zone_required_fields: ['zone_id', 'semantic_role', 'bounds', 'intended_content', 'min_font_pt', 'safe_inset_in'],
            shape_binding_field: 'layout_zone_id',
            acceptance_rule: 'Every non-decorative/non-auxiliary shape must bind to a declared zone and stay inside that zone. Structural rails, connectors, proof bands, decision rails, evidence axes, gate panels, and content text all need layout_zone_id; the zone bounds and safe inset must make the text/card/structure relationship explicit before officecli materializes the plan.',
          },
        },
        design_spec_lock: {
          spec_id: 'native_pptx_spec_lock_v1',
          owner: 'llm_agent',
          required: true,
          source: 'visual_direction_plus_slide_blueprint',
          borrowed_principles: ['ppt_master_style_spec_lock', 'template_layout_grammar', 'template_profile', 'semantic_layout_selection', 'reference_deck_analysis', 'per_page_visual_plan', 'explicit_grid', 'font_floor', 'layout_rhythm', 'rendered_quality_gate'],
          professional_design_brief: {
            design_register: '<professional deck register, e.g. executive operating review>',
            reference_style_family: '<reference-style family or template profile the deck follows>',
            first_glance_hierarchy: '<what the audience should read first, second, and third>',
            template_profile_strategy: '<how semantic master layouts, zones, and placeholders are selected>',
            capacity_strategy: '<how text volume, slots, and font floors fit before coordinates>',
            forbidden_amateur_patterns: ['generic equal-card grid', 'decorative title underline', 'overfilled receipt ledger'],
          },
          canvas_in: { width: 16, height: 9 },
          palette: {
            background: '<hex>',
            ink: '<hex>',
            muted: '<hex>',
            accent: '<hex>',
            panel: '<hex>',
          },
          typography: {
            title_font: '<font>',
            body_font: '<font>',
            title_pt_min: 36,
            body_pt_min: 18,
            point_index_pt_min: 16,
            table_body_pt_min: 11,
          },
          grid: {
            edge_margin_in_min: 0.6,
            inter_block_gap_in_min: 0.32,
          },
          motif: '<one visual motif used without title underlines>',
          layout_archetypes: [
            'executive_status_board',
            'workflow_map',
            'risk_control_matrix',
            'evidence_timeline',
            'route_comparison',
            'decision_dashboard',
          ],
          forbidden_motifs: ['decorative_title_underline', 'empty_four_card_template', 'consecutive_same_composition'],
          qa_gates: ['bounds', 'font_floor', 'text_fit', 'structural_visual', 'slot_fill', 'layout_variety', 'true_render_screenshot'],
        },
        text_fit_rules: {
          unit: 'inches',
          required: true,
          text_bearing_shape_rule: 'Every text-bearing shape, including meta labels, route labels, speaker_identity, evidence badges, boundary notes, and panel headings, must have positive bounds and meet the height floor for its font and text length. Do not treat short labels as exempt unless role is page_number, page_no, cover_meta, meta, footer, or point_index.',
          one_slide_sample_evidence_rule: 'For native_visual_sample one-slide decks, visible evidence_item text is one compact sentence, not an artifact inventory; keep it short enough to fit one proof band and leave detailed PPTX/PDF/PNG/manifest/review/export refs in artifact metadata.',
          defaults: {
            compact_label_min_height_in: 0.64,
            sentence_body_min_height_in: 0.96,
            lead_sentence_min_height_in: 0.95,
          },
          role_min_height_in: {
            speaker_identity: 0.64,
            route_label: 0.64,
            panel_title: 0.68,
            point_text_short: 0.68,
            point_text_sentence: 0.90,
            body_sentence: 0.90,
            boundary_note: 0.90,
            core_sentence: 0.95,
            lead: 0.95,
            intro: 0.95,
            thesis: 0.95,
            takeaway: 0.95,
          },
          hard_fail_examples: [
            '20pt panel_title in 0.42in height',
            '18pt point_text sentence in 0.58in height',
            '20-24pt core_sentence or takeaway in 0.62in height',
          ],
        },
        geometry_rules: {
          unit: 'inches',
          required: true,
          canvas: { width_in: 16, height_in: 9 },
          all_shapes_must_have_positive_bounds: true,
          line_and_connector_min_thickness_in: 0.03,
          line_and_connector_rule: 'A vertical line uses width_in >= 0.03 and positive height_in; a horizontal line uses positive width_in and height_in >= 0.03. Never emit 0 or negative width/height for line or connector shapes.',
          bounds_examples: [
            { kind: 'line', role: 'vertical_gate_ladder', bounds: { left_in: 9.88, top_in: 4.08, width_in: 0.04, height_in: 1.72 } },
            { kind: 'connector', role: 'horizontal_route_connector', bounds: { left_in: 5.34, top_in: 4.78, width_in: 1.72, height_in: 0.04 } },
          ],
        },
        materializable_shape_kind_contract: {
          allowed_kind_values: ['text_box', 'text', 'shape', 'preset_shape', 'rect', 'rectangle', 'rounded_rect', 'panel', 'oval', 'circle', 'line', 'connector', 'picture', 'image', 'group', 'path', 'chart', 'table', 'metric_grid'],
          disallowed_kind_values: ['triangle', 'right_triangle', 'polygon', 'arrow', 'icon', 'freeform', 'svg'],
          unknown_kind_policy: 'fail_fast_before_materialization',
          object_specific_fields: {
            text_box: ['editable_text | paragraphs[]', 'font_size', 'paragraphs[].runs[]', 'paragraphs[].bullet'],
            shape: ['preset', 'fill', 'line'],
            connector: ['connector_shape', 'from_shape_id', 'to_shape_id', 'head_end', 'tail_end'],
            picture: ['source_file | source_data_uri', 'alt', 'crop'],
            group: ['children[]'],
            path: ['path_points[] | path_commands[]', 'closed'],
            chart: ['materialization_intent', 'chart_type', 'categories[]', 'series[] | drawingml_shapes[]'],
            table: ['materialization_intent', 'data[][] | drawingml_shapes[]', 'header_fill', 'header_color', 'header_font', 'header_font_size', 'body_font_size'],
          },
          materialization_intents: ['native_data_object', 'stable_drawingml'],
          stable_drawingml_rule: 'chart/table/metric_grid with stable_drawingml must provide editable drawingml_shapes children and materialize as a real group, never a fallback rectangle',
          native_data_object_rule: 'chart/table with native_data_object must create real PowerPoint data objects and related package parts',
          icon_strategy: 'use a supported preset shape, grouped drawing shapes, picture asset, or structured path; never emit an unsupported kind',
        },
        template_intake_contract: {
          optional_plan_field: 'editable_shape_plan.template_intake',
          required_fields_when_present: ['source_pptx', 'mode'],
          supported_modes: ['replace_slides', 'fill_existing'],
          preserve_parts: ['slide_master', 'slide_layout', 'theme'],
          fill_existing_preserves: ['placeholder', 'editable_source_object'],
          source_canvas_must_be_preserved: true,
          fill_existing_requires_complete_target_coverage: true,
          source_and_output_must_be_distinct: true,
          package_part_hash_readback_required: true,
        },
        presentation_semantics_contract: {
          optional_per_slide_fields: ['speaker_notes', 'transition', 'animation_timeline'],
          transition_fields: ['type', 'direction', 'duration_ms', 'speed', 'advance_time_ms', 'advance_click'],
          animation_fields: ['target_shape_id', 'effect', 'class', 'trigger', 'duration_ms', 'delay_ms'],
          animation_target_policy: {
            stable_drawingml_group_target: 'reject_before_materialization',
            supported_top_level_kinds: ['text_box', 'shape', 'rect', 'rounded_rect', 'oval', 'path'],
            native_data_object_chart: 'supported',
            rejected_targets: ['missing', 'group_child', 'group', 'table', 'metric_grid', 'picture', 'line', 'connector'],
            zero_write_preflight_required: true,
            supported_target_rule: 'animation_timeline targets must materialize as a top-level OfficeCLI shape or native_data_object chart',
          },
          static_slide_must_remain_readable: true,
          package_readback_required: true,
        },
        design_system: {
          borrowed_principles: ['ppt_master_style_spec_lock', 'template_layout_grammar', 'template_profile', 'semantic_layout_selection', 'reference_deck_analysis', 'per_page_visual_plan', 'explicit_grid', 'font_floor', 'layout_rhythm', 'rendered_quality_gate'],
          owner: 'llm_agent',
          spec_lock_required: true,
          professional_design_brief_required: true,
          per_page_visual_qa_required: true,
          mock_fixture_visual_sample_allowed: false,
          test_double_can_claim_visual_quality: false,
          grid: {
            canvas_in: { width: 16, height: 9 },
            edge_margin_in_min: 0.6,
            inter_block_gap_in_min: 0.32,
          },
          typography_floor: {
            title_pt_min: 36,
            body_pt_min: 18,
            point_index_pt_min: 16,
            table_body_pt_min: 11,
          },
          forbidden_motifs: ['decorative_title_underline', 'empty_four_card_template', 'consecutive_same_composition'],
          layout_rhythm: {
            repeated_concrete_composition_limit: 2,
            required_distinct_composition_share: 0.75,
          },
          evidence_required_for_visual_sample: [
            'live_codex_executor_shape_plan',
            'editable_shape_plan.design_spec_lock',
            'per_slide_layout_intent',
            'libreoffice_poppler_render_screenshots',
            'visual_director_review',
            'screenshot_review',
            'export_pptx',
          ],
        },
        slides: [
          {
            slide_id: 'S01',
            title: '<audience-facing title>',
            background: '#FFFFFF',
            layout_family: '<visual layout family label for reporting only>',
            core_sentence: '<audience-facing core sentence>',
            page_core_content: ['<editable text>'],
            layout_intent: {
              rhetorical_role: '<cover | comparison | timeline | gate | system_map | synthesis>',
              composition_signature: '<stable human-readable signature from concrete geometry>',
              visual_weight: '<left_heavy | right_heavy | centered | diagonal | radial | bottom_band>',
              primary_grid: '<2_column | 3_card | timeline_rail | gate_ladder | radial_axes | hero_callout>',
              negative_space_strategy: '<where the breathing space is intentionally left>',
              non_text_visual: '<shape/chart/table/connector/metric grid used as first-glance signal>',
              forbidden_template_reuse_checked: true,
            },
            template_layout_binding: {
              selected_archetype: 'professional_system_map',
              archetype_instance_id: 'S01-system-map-v1',
              rhythm_role: '<opening | proof | contrast | synthesis | close>',
              zone_gap_in_min: 0.32,
              zone_inset_in_min: 0.15,
              zones: [
                {
                  zone_id: 'title_zone',
                  semantic_role: 'title',
                  bounds: { left_in: 0.9, top_in: 0.55, width_in: 11.0, height_in: 1.05 },
                  intended_content: 'audience-facing title',
                  min_font_pt: 36,
                  safe_inset_in: 0.15,
                },
                {
                  zone_id: 'claim_zone',
                  semantic_role: 'core_claim',
                  bounds: { left_in: 0.95, top_in: 1.72, width_in: 11.8, height_in: 0.95 },
                  intended_content: 'one-sentence claim',
                  min_font_pt: 18,
                  safe_inset_in: 0.15,
                },
                {
                  zone_id: 'system_map_zone',
                  semantic_role: 'system_map',
                  bounds: { left_in: 0.95, top_in: 3.05, width_in: 8.2, height_in: 3.05 },
                  intended_content: 'route or workflow diagram with labels off connector lanes',
                  min_font_pt: 18,
                  safe_inset_in: 0.15,
                },
                {
                  zone_id: 'gate_zone',
                  semantic_role: 'delivery_gate',
                  bounds: { left_in: 9.65, top_in: 3.05, width_in: 4.5, height_in: 3.05 },
                  intended_content: 'gate outcome or quality decision',
                  min_font_pt: 18,
                  safe_inset_in: 0.15,
                },
                {
                  zone_id: 'evidence_zone',
                  semantic_role: 'evidence_note',
                  bounds: { left_in: 0.95, top_in: 6.45, width_in: 13.2, height_in: 1.2 },
                  intended_content: 'compact proof note without receipt clutter',
                  min_font_pt: 18,
                  safe_inset_in: 0.15,
                },
              ],
            },
            native_shapes: [
              {
                shape_id: 'S01-title',
                kind: 'text_box',
                role: 'title',
                quality_role: 'content',
                layout_zone_id: 'title_zone',
                editable_text: '<text>',
                bounds: { left_in: 1.0, top_in: 0.6, width_in: 13.8, height_in: 1.1 },
                font_size: 40,
                color: '#171C24',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-core',
                kind: 'text_box',
                role: 'core_sentence',
                quality_role: 'content',
                layout_zone_id: 'claim_zone',
                editable_text: '<one sentence audience-facing claim>',
                bounds: { left_in: 1.0, top_in: 1.85, width_in: 11.8, height_in: 0.98 },
                font_size: 22,
                color: '#5B6570',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-point-1-text',
                kind: 'text_box',
                role: 'point_text',
                quality_role: 'content',
                layout_zone_id: 'system_map_zone',
                editable_text: '<sentence-length point text with evidence>',
                bounds: { left_in: 1.2, top_in: 3.1, width_in: 3.5, height_in: 0.92 },
                font_size: 18,
                color: '#171C24',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-point-1-index',
                kind: 'oval',
                role: 'point_index',
                quality_role: 'content',
                layout_zone_id: 'system_map_zone',
                editable_text: '01',
                bounds: { left_in: 1.0, top_in: 2.1, width_in: 0.52, height_in: 0.52 },
                font_size: 16,
                color: '#171C24',
                fill: '#DBEAFE',
                line: '#2563EB',
              },
            ],
            redcube_svg_ir_intent: {
              root_viewbox: '0 0 1152 648',
              editable_text_required: true,
              required_intents: [
                'text:title',
                'text:point_text',
                'rect:content_panel',
                'group:content_point',
                'layout_intent:composition_signature',
              ],
            },
          },
        ],
      },
    };
  }
