import { pptSafeText as safeText } from './core-helpers.js';

type JsonRecord = Record<string, any>;
type NativePptRoute = 'author_pptx_native' | 'repair_pptx_native';

const REQUIRED_NATIVE_VISUAL_SAMPLE_CHECKS = Object.freeze([
  'live_codex_executor_shape_plan',
  'editable_shape_plan.design_spec_lock',
  'per_slide_layout_intent',
  'shape_manifest.all_slide_issues_empty',
  'shape_manifest.all_native_quality_checks_true',
  'libreoffice_poppler_render_screenshots',
  'visual_director_review',
  'screenshot_review',
  'export_pptx',
]);

const QUALITY_NONREGRESSION_CONTRACT_REF = 'contracts/runtime-program/ppt-native-pptx-quality-nonregression.json';

const ADOPTED_NATIVE_PPT_DESIGN_DISCIPLINES = Object.freeze([
  'spec_lock',
  'template_layout_grammar',
  'template_profile',
  'semantic_layout_selection',
  'reference_deck_analysis',
  'per_page_visual_plan',
  'svg_qa_before_export',
  'rendered_quality_gate',
]);

const REQUIRED_NATIVE_QUALITY_METRIC_REFS = Object.freeze([
  'shape_manifest#/slides/*/metrics/bounds',
  'shape_manifest#/slides/*/metrics/text_char_count',
  'shape_manifest#/slides/*/metrics/primary_points',
  'shape_manifest#/slides/*/metrics/min_body_font_pt',
  'shape_manifest#/slides/*/metrics/body_text_readability_ok',
  'shape_manifest#/slides/*/metrics/typography_hierarchy_ratio',
  'shape_manifest#/slides/*/metrics/typography_hierarchy_ok',
  'shape_manifest#/slides/*/metrics/title_core_overlap_count',
  'shape_manifest#/slides/*/metrics/layout_variant',
  'shape_manifest#/slides/*/metrics/expected_slot_count',
  'shape_manifest#/slides/*/metrics/filled_slot_count',
  'shape_manifest#/slides/*/metrics/slot_fill_ok',
  'shape_manifest#/slides/*/metrics/audience_label_readability_ok',
  'shape_manifest#/slides/*/metrics/content_depth_ok',
  'shape_manifest#/slides/*/metrics/grid_balance_ok',
  'shape_manifest#/slides/*/metrics/visual_structure_present',
  'shape_manifest#/slides/*/metrics/non_text_visual_specific_ok',
  'shape_manifest#/slides/*/metrics/mechanical_card_template_absent',
  'shape_manifest#/slides/*/metrics/composition_signature',
  'shape_manifest#/slides/*/metrics/title_underline_absent_ok',
  'shape_manifest#/slides/*/metrics/occupied_ratio',
  'shape_manifest#/slides/*/metrics/edge_clearance',
  'shape_manifest#/slides/*/metrics/overlap_pairs',
  'shape_manifest#/slides/*/metrics/structural_text_collision_count',
  'shape_manifest#/slides/*/metrics/structural_text_collisions',
  'shape_manifest#/slides/*/metrics/shape_kind_count',
  'shape_manifest#/slides/*/metrics/role_count',
  'shape_manifest#/slides/*/metrics/layout_richness_score',
  'shape_manifest#/slides/*/metrics/chart_metrics',
  'shape_manifest#/slides/*/metrics/table_metrics',
  'shape_manifest#/slides/*/metrics/metric_grid_metrics',
  'shape_manifest#/slides/*/metrics/coordinate_determinism_hash',
  'shape_manifest#/slides/*/preview_screenshot_sha256',
  'shape_manifest#/slides/*/preview_screenshot_dimensions',
]);

const OFFICECLI_MATERIALIZER_POLICY = Object.freeze({
  policy_id: 'ppt_native_officecli_materializer_quality_gate_v1',
  adoption_status: 'qa_materializer_discipline_only',
  rca_main_workflow_owner: 'redcube_stage_review_export',
  skill_authoring_loop_adopted: false,
  materializer_role: 'default_editable_pptx_materializer_and_qa_gate',
  current_pptx_writer: 'officecli_pptx_materializer',
  officecli_writer_adapter_default_enabled: true,
  required_gate_refs: [
    'officecli_save_before_close',
    'officecli_validate',
    'officecli_view_issues',
    'officecli_view_text',
  ],
  save_before_close_required: true,
  validate_required: true,
  view_issues_required: true,
  view_text_required: true,
  true_render_proof_required_after_officecli_gate: true,
  true_render_proof_substitute_allowed: false,
  deterministic_cjk_font_family: 'Noto Sans CJK SC',
  default_visual_route_changed: false,
  default_executor_changed: false,
});

const PROFESSIONAL_DESIGN_PACK_CONTRACT = Object.freeze({
  contract_id: 'rca_native_pptx_professional_design_pack_v1',
  required: true,
  owner: 'redcube_ai',
  creative_owner: 'llm_agent',
  materializer_can_select_layout: false,
  helper_template_layout_allowed: false,
  fail_closed_when_missing: true,
  layout_archetype_taxonomy: [
    {
      archetype_id: 'flow_hub_to_cards_proof_band',
      use_when: 'shared input, route comparison, and proof band need one first-glance causal path',
      required_visual_logic: 'dominant hub -> exactly scoped route cards -> proof band',
    },
    {
      archetype_id: 'decision_split_with_proof_stack',
      use_when: 'one recommendation or decision needs supporting proof beside it',
      required_visual_logic: 'decision rail separates decision area from proof stack',
    },
    {
      archetype_id: 'system_map_with_gate_stack',
      use_when: 'workflow or route mechanics need visible ownership and gates',
      required_visual_logic: 'map lanes stay separate from gate cards and labels',
    },
    {
      archetype_id: 'evidence_timeline_rail',
      use_when: 'sequence, evolution, or route progress needs ordering',
      required_visual_logic: 'timeline rail never crosses readable labels',
    },
    {
      archetype_id: 'risk_control_matrix',
      use_when: 'criteria, blockers, controls, or QA requirements need comparison',
      required_visual_logic: 'filled matrix cells with no empty placeholder slots',
    },
    {
      archetype_id: 'executive_status_board',
      use_when: 'low-density status proof with a small number of major claims',
      required_visual_logic: 'large cards subordinate to one proof or takeaway area',
    },
  ],
  capacity_budgets: {
    title_font_pt_min: 36,
    native_sample_title_font_pt_min: 40,
    body_font_pt_min: 18,
    card_text_max_lines: 2,
    card_text_min_cjk_chars: 12,
    card_text_max_cjk_chars: 22,
    card_width_in_min: 4.0,
    card_height_in_min: 1.35,
    text_safe_inset_in_min: 0.15,
    edge_margin_in_min: 0.6,
    inter_block_gap_in_min: 0.32,
  },
  connector_semantics: {
    real_ppt_connector_required: true,
    route_card_connector_kind: 'connector',
    route_card_connector_direction_required: true,
    vertical_drop_width_in_max: 0.04,
    vertical_drop_height_in_min: 0.66,
    horizontal_bus_for_route_cards_allowed: false,
    connector_text_clearance_in_min: 0.12,
  },
  layout_rhythm: {
    consecutive_same_archetype_max: 2,
    consecutive_same_primary_grid_max: 2,
    distinct_composition_signature_share_min: 0.75,
    empty_placeholder_slots_allowed: false,
  },
  design_reference_discipline: {
    source_projects: [
      'ppt-master',
      'PPTAgent',
      'officecli-pptx',
      'presenton',
      'ppt-agent-skills',
    ],
    borrowed_scope: [
      'spec_lock',
      'template_profile_registry',
      'semantic_layout_selection',
      'placeholder_capacity_budget',
      'per_page_visual_plan',
      'rendered_quality_gate',
    ],
    runtime_dependency_allowed: false,
  },
  required_ai_plan_sections: [
    'design_spec_lock.professional_design_brief',
    'deck_layout_rhythm_plan',
    'template_layout_grammar.reference_discipline',
    'slides[].layout_intent',
    'slides[].template_layout_binding',
    'slides[].native_shapes[].layout_zone_id',
  ],
});

export function buildNativePptQualityNonregressionReadModel({
  route,
  editableShapePlanFile,
  shapeManifestFile,
  renderProof,
  repairEvidence,
  generationRuntime = null,
  testDoubleBoundary = null,
}: {
  route: NativePptRoute;
  editableShapePlanFile: string;
  shapeManifestFile: string;
  renderProof: JsonRecord;
  repairEvidence: JsonRecord;
  generationRuntime?: JsonRecord | null;
  testDoubleBoundary?: JsonRecord | null;
}): JsonRecord {
  const isTestDouble = Boolean(testDoubleBoundary)
    || safeText(generationRuntime?.run_id).startsWith('mock_')
    || safeText(generationRuntime?.owner).includes('mock')
    || safeText(generationRuntime?.adapter_surface).includes('mock');
  return {
    surface_kind: 'ppt_native_pptx_quality_nonregression_read_model',
    owner: 'redcube_ai',
    consumer: 'opl_agent_lab',
    status: 'refs_only_standard_suite_input_ready',
    contract_ref: QUALITY_NONREGRESSION_CONTRACT_REF,
    route,
    refs_only: true,
    read_only: true,
    body_included: false,
    agent_lab_suite_input: {
      suite_kind: 'standard',
      suite_id: 'redcube-ai.ppt-native-pptx-quality-nonregression.standard.v1',
      domain_id: 'redcube-ai',
      input_mode: 'refs_only_handoff',
      refs_only: true,
      read_only: true,
      agent_lab_score_is_rca_visual_verdict: false,
      claims_visual_ready: false,
      claims_exportable: false,
      claims_handoffable: false,
      claims_production_soak_complete: false,
    },
    shape_manifest_ref: {
      file: shapeManifestFile,
      required_metric_refs: [...REQUIRED_NATIVE_QUALITY_METRIC_REFS],
      fail_closed_when_missing: true,
      source_surface_kind: 'native_pptx',
      quality_model: 'shape_manifest_layout_metrics_v1',
    },
    editable_shape_plan_ref: {
      file: editableShapePlanFile,
      contract_kind: 'redcube_ai_first_native_ppt_shape_plan',
      creative_owner: 'llm_agent',
      python_helper_role: 'execute_validate_export_only',
      design_spec_lock_required: true,
      reference_design_profile_required: true,
      template_layout_grammar_required: true,
      semantic_layout_selection_required: true,
      placeholder_capacity_required: true,
      per_slide_layout_binding_required: true,
      materializer_executes_selected_archetype_zones_only: true,
      per_page_visual_plan_required: true,
      ppt_master_style_discipline_adopted: [...ADOPTED_NATIVE_PPT_DESIGN_DISCIPLINES],
      layout_intent_required: true,
      composition_signature_required: true,
      action_title_required: true,
      title_underline_motif_allowed: false,
      concrete_layout_variant_repetition_limit: 2,
      helper_can_replace_ai_creative_owner: false,
      fail_closed_when_missing: true,
    },
    professional_design_pack_ref: {
      contract_ref: `${QUALITY_NONREGRESSION_CONTRACT_REF}#/professional_design_pack_contract`,
      required: PROFESSIONAL_DESIGN_PACK_CONTRACT.required,
      owner: PROFESSIONAL_DESIGN_PACK_CONTRACT.owner,
      creative_owner: PROFESSIONAL_DESIGN_PACK_CONTRACT.creative_owner,
      materializer_can_select_layout: PROFESSIONAL_DESIGN_PACK_CONTRACT.materializer_can_select_layout,
      helper_template_layout_allowed: PROFESSIONAL_DESIGN_PACK_CONTRACT.helper_template_layout_allowed,
      required_design_pack_refs: [
        'layout_archetype_taxonomy',
        'capacity_budgets',
        'connector_semantics',
        'layout_rhythm',
        'design_reference_discipline',
      ],
      fail_closed_when_missing: PROFESSIONAL_DESIGN_PACK_CONTRACT.fail_closed_when_missing,
    },
    visual_sample_claim_boundary: {
      sample_kind: isTestDouble ? 'deterministic_test_double_plumbing_proof' : 'live_codex_executor_native_ppt_sample',
      structured_executor: isTestDouble ? 'mock_codex_test_double' : safeText(generationRuntime?.owner, 'codex_cli'),
      test_double_detected: isTestDouble,
      mock_fixture_visual_sample_allowed: false,
      test_double_can_claim_visual_design_quality: false,
      display_as_native_ppt_visual_sample_allowed: !isTestDouble,
      proves_artifact_export_chain: true,
      proves_visual_design_quality: !isTestDouble,
      required_for_visual_quality_claim: [...REQUIRED_NATIVE_VISUAL_SAMPLE_CHECKS],
    },
    officecli_materializer_policy_ref: {
      policy_id: OFFICECLI_MATERIALIZER_POLICY.policy_id,
      contract_ref: `${QUALITY_NONREGRESSION_CONTRACT_REF}#/officecli_materializer_policy`,
      source_ref: 'native_ppt_bundle.officecli_materializer_policy',
      refs_only: true,
      fail_closed_when_missing_when_adapter_active: true,
    },
    officecli_quality_gate: {
      ...OFFICECLI_MATERIALIZER_POLICY,
      officecli_skill_can_replace_rca_workflow: false,
      officecli_validate_can_replace_true_render_proof: false,
    },
    true_render_proof_ref: {
      source_ref: 'native_ppt_bundle.render_proof',
      renderer_kind: safeText(renderProof.renderer_kind),
      renderer_pipeline: safeText(renderProof.renderer_pipeline),
      runtime: safeText(renderProof.runtime),
      fail_closed_when_missing: true,
      synthetic_preview_allowed: false,
    },
    repair_policy: {
      repair_route: 'repair_pptx_native',
      blocked_page_only: true,
      target_source: 'screenshot_review.blocked_slide_ids',
      repair_evidence_surface: 'native_ppt_repair_evidence_v1',
      repair_evidence_ref: 'native_ppt_repair_log.repair_evidence',
      non_blocking_slide_reuse_ok: repairEvidence.non_blocking_slide_reuse_ok === true,
    },
    export_proof_summary_ref: {
      summary_surface: 'native_export_bundle_operator_proof_summary_v1',
      source_ref: 'workspace-runtime-ref:export_pptx:<run-id>#/operator_proof_summary',
      renderer_proof_ref: 'workspace-runtime-ref:export_pptx:<run-id>#/renderer_proof',
      shape_manifest_summary_ref: 'workspace-runtime-ref:export_pptx:<run-id>#/shape_manifest_summary',
    },
    quality_gate_refs: [
      'agent/quality_gates/screenshot_review.md',
      'agent/quality_gates/review_export_memory.md',
      'officecli_save_before_close',
      'officecli_validate',
      'officecli_view_issues',
      'officecli_view_text',
      'workspace-runtime-ref:screenshot_review:<run-id>',
      'workspace-runtime-ref:export_pptx:<run-id>#/operator_proof_summary',
    ],
    authority_boundary: {
      no_forbidden_write: true,
      opl_agent_lab_can_store_suite_input_refs: true,
      opl_agent_lab_can_compare_quality_refs: true,
      opl_agent_lab_can_score_nonregression_refs: true,
      opl_agent_lab_score_is_rca_visual_verdict: false,
      opl_agent_lab_can_write_rca_visual_truth: false,
      opl_agent_lab_can_write_artifact_blob: false,
      opl_agent_lab_can_write_memory_body: false,
      opl_agent_lab_can_authorize_quality_verdict: false,
      opl_agent_lab_can_authorize_exportable: false,
      opl_agent_lab_can_claim_visual_ready: false,
      python_helper_can_replace_ai_creative_owner: false,
      python_helper_can_write_visual_truth: false,
      python_helper_can_authorize_quality_verdict: false,
      python_helper_can_authorize_exportable: false,
      officecli_skill_can_replace_rca_workflow: false,
      officecli_validate_can_replace_true_render_proof: false,
      officecli_authoring_loop_adopted: false,
      default_executor_changed: false,
      rca_quality_floor_owner: 'redcube_ai',
      rca_export_authority_owner: 'redcube_ai',
    },
  };
}
