export const AI_FIRST_EDITING_CONTRACT = Object.freeze({
  contract_id: 'ppt_native_ai_first_editing_contract_v1',
  creative_owner: 'llm_agent',
  editable_shape_plan_required: true,
  editable_shape_manifest_required: true,
  design_spec_lock_required: true,
  reference_design_profile_required: true,
  template_layout_grammar_required: true,
  semantic_layout_selection_required: true,
  placeholder_capacity_required: true,
  per_slide_layout_binding_required: true,
  shape_quality_role_required: true,
  layout_intent_required: true,
  composition_signature_required: true,
  action_title_required: true,
  structural_visual_required: true,
  adopted_design_disciplines: [
    'spec_lock',
    'template_layout_grammar',
    'template_profile',
    'semantic_layout_selection',
    'reference_deck_analysis',
    'per_page_visual_plan',
    'svg_qa_before_export',
    'rendered_quality_gate',
  ],
  title_underline_motif_allowed: false,
  concrete_layout_variant_repetition_limit: 2,
  python_helper_role: 'execute_validate_export_only',
  template_substitution_allowed: false,
  preserved_gates: ['visual_director_review', 'screenshot_review', 'export_pptx'],
});

export const OFFICECLI_MATERIALIZER_POLICY = Object.freeze({
  policy_id: 'ppt_native_officecli_materializer_quality_gate_v1',
  adoption_status: 'qa_materializer_discipline_only',
  rca_main_workflow_owner: 'redcube_stage_review_export',
  skill_authoring_loop_adopted: false,
  materializer_role: 'default_editable_pptx_materializer_and_qa_gate',
  current_pptx_writer: 'officecli_pptx_materializer',
  officecli_writer_adapter_default_enabled: true,
  required_gate_refs: [
    'officecli_save_before_close',
    'officecli_validate',
    'officecli_view_issues',
    'officecli_view_text',
  ],
  save_before_close_required: true,
  validate_required: true,
  view_issues_required: true,
  view_text_required: true,
  true_render_proof_required_after_officecli_gate: true,
  true_render_proof_substitute_allowed: false,
  deterministic_cjk_font_family: 'Noto Sans CJK SC',
  default_visual_route_changed: false,
  default_executor_changed: false,
});
