type JsonRecord = Record<string, any>;
type NativePptRoute = 'author_pptx_native' | 'repair_pptx_native';

export function buildNativeShapePlanOutputContract({
  aiFirstEditingContract,
  route,
}: {
  aiFirstEditingContract: JsonRecord;
  route: NativePptRoute;
}) {
    return {
      ai_first_editing_contract: aiFirstEditingContract,
      editable_shape_plan: {
        contract_kind: 'redcube_ai_first_native_ppt_shape_plan',
        route,
        scope: route === 'repair_pptx_native' ? 'page_repair' : 'deck_authoring',
        target_slide_ids: ['S02'],
        authoring_ir: {
          kind: 'redcube_svg_ir',
          version: 1,
          required: true,
          strict_svg_preflight_required: true,
          allowed_svg_tags: ['svg', 'g', 'rect', 'text'],
          unsupported_svg_tags: ['image', 'foreignObject', 'script'],
        },
        materializer: {
          kind: 'officecli_pptx_materializer',
          role: 'execute_ai_spatial_plan_only',
          helper_template_layout_allowed: false,
          officecli_gate_required: ['save', 'validate', 'view_issues', 'view_text'],
        },
        design_spec_lock: {
          spec_id: 'native_pptx_spec_lock_v1',
          owner: 'llm_agent',
          required: true,
          source: 'visual_direction_plus_slide_blueprint',
          borrowed_principles: ['ppt_master_style_spec_lock', 'per_page_visual_plan', 'explicit_grid', 'font_floor', 'layout_rhythm', 'rendered_quality_gate'],
          canvas_in: { width: 16, height: 9 },
          palette: {
            background: '<hex>',
            ink: '<hex>',
            muted: '<hex>',
            accent: '<hex>',
            panel: '<hex>',
          },
          typography: {
            title_font: '<font>',
            body_font: '<font>',
            title_pt_min: 36,
            body_pt_min: 18,
            point_index_pt_min: 16,
            table_body_pt_min: 11,
          },
          grid: {
            edge_margin_in_min: 0.6,
            inter_block_gap_in_min: 0.32,
          },
          motif: '<one visual motif used without title underlines>',
          layout_archetypes: [
            'executive_status_board',
            'workflow_map',
            'risk_control_matrix',
            'evidence_timeline',
            'route_comparison',
            'decision_dashboard',
          ],
          forbidden_motifs: ['decorative_title_underline', 'empty_four_card_template', 'consecutive_same_composition'],
          qa_gates: ['bounds', 'font_floor', 'text_fit', 'structural_visual', 'slot_fill', 'layout_variety', 'true_render_screenshot'],
        },
        text_fit_rules: {
          unit: 'inches',
          required: true,
          text_bearing_shape_rule: 'Every text-bearing shape, including meta labels, route labels, speaker_identity, evidence badges, boundary notes, and panel headings, must have positive bounds and meet the height floor for its font and text length. Do not treat short labels as exempt unless role is page_number, page_no, cover_meta, meta, footer, or point_index.',
          defaults: {
            compact_label_min_height_in: 0.64,
            sentence_body_min_height_in: 0.96,
            lead_sentence_min_height_in: 0.95,
          },
          role_min_height_in: {
            speaker_identity: 0.64,
            route_label: 0.64,
            panel_title: 0.68,
            point_text_short: 0.68,
            point_text_sentence: 0.90,
            body_sentence: 0.90,
            boundary_note: 0.90,
            core_sentence: 0.95,
            lead: 0.95,
            intro: 0.95,
            thesis: 0.95,
            takeaway: 0.95,
          },
          hard_fail_examples: [
            '20pt panel_title in 0.42in height',
            '18pt point_text sentence in 0.58in height',
            '20-24pt core_sentence or takeaway in 0.62in height',
          ],
        },
        geometry_rules: {
          unit: 'inches',
          required: true,
          canvas: { width_in: 16, height_in: 9 },
          all_shapes_must_have_positive_bounds: true,
          line_and_connector_min_thickness_in: 0.03,
          line_and_connector_rule: 'A vertical line uses width_in >= 0.03 and positive height_in; a horizontal line uses positive width_in and height_in >= 0.03. Never emit 0 or negative width/height for line or connector shapes.',
          bounds_examples: [
            { kind: 'line', role: 'vertical_gate_ladder', bounds: { left_in: 9.88, top_in: 4.08, width_in: 0.04, height_in: 1.72 } },
            { kind: 'connector', role: 'horizontal_route_connector', bounds: { left_in: 5.34, top_in: 4.78, width_in: 1.72, height_in: 0.04 } },
          ],
        },
        materializable_shape_kind_contract: {
          allowed_kind_values: ['text_box', 'text', 'rect', 'rectangle', 'rounded_rect', 'panel', 'oval', 'circle', 'line', 'connector'],
          disallowed_kind_values: ['triangle', 'right_triangle', 'polygon', 'arrow', 'icon', 'group', 'freeform', 'image', 'svg', 'path'],
          icon_strategy: 'compose simple icons from rect, line, and oval primitives only',
        },
        design_system: {
          borrowed_principles: ['ppt_master_style_spec_lock', 'per_page_visual_plan', 'explicit_grid', 'font_floor', 'layout_rhythm', 'rendered_quality_gate'],
          owner: 'llm_agent',
          spec_lock_required: true,
          per_page_visual_qa_required: true,
          mock_fixture_visual_sample_allowed: false,
          test_double_can_claim_visual_quality: false,
          grid: {
            canvas_in: { width: 16, height: 9 },
            edge_margin_in_min: 0.6,
            inter_block_gap_in_min: 0.32,
          },
          typography_floor: {
            title_pt_min: 36,
            body_pt_min: 18,
            point_index_pt_min: 16,
            table_body_pt_min: 11,
          },
          forbidden_motifs: ['decorative_title_underline', 'empty_four_card_template', 'consecutive_same_composition'],
          layout_rhythm: {
            repeated_concrete_composition_limit: 2,
            required_distinct_composition_share: 0.75,
          },
          evidence_required_for_visual_sample: [
            'live_codex_executor_shape_plan',
            'editable_shape_plan.design_spec_lock',
            'per_slide_layout_intent',
            'libreoffice_poppler_render_screenshots',
            'visual_director_review',
            'screenshot_review',
            'export_pptx',
          ],
        },
        slides: [
          {
            slide_id: 'S01',
            title: '<audience-facing title>',
            background: '#FFFFFF',
            layout_family: '<visual layout family label for reporting only>',
            core_sentence: '<audience-facing core sentence>',
            page_core_content: ['<editable text>'],
            layout_intent: {
              rhetorical_role: '<cover | comparison | timeline | gate | system_map | synthesis>',
              composition_signature: '<stable human-readable signature from concrete geometry>',
              visual_weight: '<left_heavy | right_heavy | centered | diagonal | radial | bottom_band>',
              primary_grid: '<2_column | 3_card | timeline_rail | gate_ladder | radial_axes | hero_callout>',
              negative_space_strategy: '<where the breathing space is intentionally left>',
              non_text_visual: '<shape/chart/table/connector/metric grid used as first-glance signal>',
              forbidden_template_reuse_checked: true,
            },
            native_shapes: [
              {
                shape_id: 'S01-title',
                kind: 'text_box',
                role: 'title',
                quality_role: 'content',
                editable_text: '<text>',
                bounds: { left_in: 1.0, top_in: 0.6, width_in: 13.8, height_in: 1.1 },
                font_size: 40,
                color: '#171C24',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-core',
                kind: 'text_box',
                role: 'core_sentence',
                quality_role: 'content',
                editable_text: '<one sentence audience-facing claim>',
                bounds: { left_in: 1.0, top_in: 1.85, width_in: 11.8, height_in: 0.98 },
                font_size: 22,
                color: '#5B6570',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-point-1-text',
                kind: 'text_box',
                role: 'point_text',
                quality_role: 'content',
                editable_text: '<sentence-length point text with evidence>',
                bounds: { left_in: 1.2, top_in: 3.1, width_in: 3.5, height_in: 0.92 },
                font_size: 18,
                color: '#171C24',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-point-1-index',
                kind: 'oval',
                role: 'point_index',
                quality_role: 'content',
                editable_text: '01',
                bounds: { left_in: 1.0, top_in: 2.1, width_in: 0.52, height_in: 0.52 },
                font_size: 16,
                color: '#171C24',
                fill: '#DBEAFE',
                line: '#2563EB',
              },
            ],
            redcube_svg_ir_intent: {
              root_viewbox: '0 0 1152 648',
              editable_text_required: true,
              required_intents: [
                'text:title',
                'text:point_text',
                'rect:content_panel',
                'group:content_point',
                'layout_intent:composition_signature',
              ],
            },
          },
        ],
      },
    };
  }
