export const REQUIRED_ENGINE_CAPABILITIES = Object.freeze({
  authoring_ir: 'redcube_svg_ir',
  authoring_ir_version: 1,
  pptx_writer: 'officecli_pptx_materializer',
  editable_pptx: true,
  strict_svg_preflight: true,
  true_render_proof_required: true,
  true_render_proof_renderer: 'libreoffice_headless',
  cross_platform_render_required: true,
  screenshot_packaging: false,
});

export const NATIVE_PPT_AGGREGATED_CHECK_KEYS = Object.freeze([
  'overflow_free',
  'occlusion_free',
  'visual_density_ok',
  'speaker_fit_ok',
  'edge_clearance_ok',
  'block_content_fit_ok',
  'title_typography_ok',
  'body_text_readability_ok',
  'typography_hierarchy_ok',
  'title_core_overlap_ok',
  'page_number_consistency_ok',
  'external_audience_language_ok',
  'title_safe_zone_clear',
  'table_legibility_ok',
  'layout_density_ok',
  'slot_fill_ok',
  'audience_label_readability_ok',
  'content_depth_ok',
  'grid_balance_ok',
  'visual_structure_present',
  'non_text_visual_specific_ok',
  'mechanical_card_template_absent',
  'panel_text_safe_area_ok',
  'short_label_wrap_ok',
]);

export const NATIVE_QUALITY_REQUIRED_NUMERIC_METRIC_KEYS = Object.freeze([
  'text_char_count',
  'block_count',
  'overlap_pairs',
  'structural_text_collision_count',
  'clipped_nodes',
  'occupied_ratio',
  'primary_points',
  'title_safe_zone_clearance_ok',
  'min_body_font_pt',
  'typography_hierarchy_ratio',
  'title_core_overlap_count',
  'expected_slot_count',
  'filled_slot_count',
]);

export const NATIVE_QUALITY_REQUIRED_BOOLEAN_METRIC_KEYS = Object.freeze([
  'body_text_readability_ok',
  'typography_hierarchy_ok',
  'slot_fill_ok',
  'audience_label_readability_ok',
  'content_depth_ok',
  'grid_balance_ok',
  'title_underline_absent_ok',
  'visual_structure_present',
  'non_text_visual_specific_ok',
  'mechanical_card_template_absent',
  'panel_text_safe_area_ok',
  'short_label_wrap_ok',
]);

export const NATIVE_QUALITY_REQUIRED_BOOLEAN_CHECK_KEYS = Object.freeze([
  'title_core_overlap_ok',
  'slot_fill_ok',
  'audience_label_readability_ok',
  'content_depth_ok',
  'grid_balance_ok',
  'title_underline_absent_ok',
  'visual_structure_present',
  'non_text_visual_specific_ok',
  'mechanical_card_template_absent',
  'panel_text_safe_area_ok',
  'short_label_wrap_ok',
]);
