type JsonRecord = Record<string, any>;
type NativePptRoute = 'author_pptx_native' | 'repair_pptx_native';

export function buildNativeShapePlanOutputContract({
  aiFirstEditingContract,
  route,
}: {
  aiFirstEditingContract: JsonRecord;
  route: NativePptRoute;
}) {
    return {
      ai_first_editing_contract: aiFirstEditingContract,
      editable_shape_plan: {
        contract_kind: 'redcube_ai_first_native_ppt_shape_plan',
        route,
        scope: route === 'repair_pptx_native' ? 'page_repair' : 'deck_authoring',
        target_slide_ids: ['S02'],
        authoring_ir: {
          kind: 'redcube_svg_ir',
          version: 1,
          required: true,
          strict_svg_preflight_required: true,
          allowed_svg_tags: ['svg', 'g', 'rect', 'text'],
          unsupported_svg_tags: ['image', 'foreignObject', 'script'],
        },
        materializer: {
          kind: 'officecli_pptx_materializer',
          role: 'execute_ai_spatial_plan_only',
          helper_template_layout_allowed: false,
          officecli_gate_required: ['save', 'validate', 'view_issues', 'view_text'],
        },
        deck_layout_rhythm_plan: {
          required: true,
          owner: 'llm_agent',
          purpose: 'Plan the contact-sheet rhythm before individual coordinates so native pages do not collapse into repeated card grids.',
          per_slide_required_fields: ['slide_id', 'rhetorical_role', 'selected_archetype', 'primary_grid', 'composition_signature_budget', 'proof_object'],
          rules: {
            consecutive_same_selected_archetype_max: 2,
            consecutive_same_primary_grid_max: 2,
            distinct_composition_signature_share_min: 0.75,
            min_distinct_archetypes_for_decks_5_slides_or_more: 3,
            every_slide_needs_a_proof_object: true,
            no_empty_placeholder_slots: true,
          },
        },
        template_layout_grammar: {
          grammar_id: 'native_pptx_template_layout_grammar_v1',
          owner: 'llm_agent',
          required: true,
          purpose: 'Choose a professional editable-PPT layout archetype and semantic zones before emitting coordinates.',
          materializer_role: 'execute_selected_archetype_zones_only',
          helper_template_layout_allowed: false,
          source: 'claim_spine_plus_visual_direction_plus_slide_blueprint',
          canvas_in: { width: 16, height: 9 },
          global_rules: {
            edge_margin_in_min: 0.6,
            zone_gap_in_min: 0.32,
            zone_inset_in_min: 0.15,
            selected_archetype_required_before_shapes: true,
            every_content_shape_must_bind_to_layout_zone: true,
            connector_lane_must_be_separate_from_text_zones: true,
            empty_placeholder_slots_allowed: false,
            repeated_concrete_archetype_limit: 2,
            contact_sheet_rhythm_required: true,
          },
          archetype_catalog: [
            {
              archetype_id: 'professional_system_map',
              use_when: 'workflow, route, system, gate, or evidence flow needs to be understood at a glance',
              layout_description: 'Claim and title above an editable system map; route lanes, gate stack, and evidence band occupy distinct semantic zones with connector lanes outside text.',
              required_zones: ['title_zone', 'claim_zone', 'system_map_zone', 'gate_zone', 'evidence_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'system_map_panel', 'route_label', 'gate_card', 'evidence_item'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'structural_visual', 'gate_or_route_label', 'evidence_or_metric_text'],
                min_filled_required_zone_share: 0.8,
                max_audience_text_shapes: 12,
                min_body_font_pt: 18,
              },
              prohibited: ['connector crossing readable text', 'three narrow route cards', 'labels placed on rails'],
            },
            {
              archetype_id: 'executive_status_board',
              use_when: 'one-slide status proof or decision summary',
              layout_description: 'Large status cards or panels in the middle with a separate proof/takeaway band; suitable for a low-density executive slide.',
              required_zones: ['title_zone', 'claim_zone', 'status_zone', 'evidence_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'content_panel', 'point_text', 'evidence_item', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'content_container', 'audience_body_text', 'takeaway_text'],
                min_filled_required_zone_share: 0.8,
                max_audience_text_shapes: 12,
                min_card_width_in: 3.3,
                min_card_height_in: 1.55,
              },
              prohibited: ['receipt label pile', 'empty four-card grid', 'tiny KPI badges'],
            },
            {
              archetype_id: 'evidence_timeline',
              use_when: 'sequence, milestone, or proof evolution',
              layout_description: 'Horizontal or vertical timeline rail with milestone nodes, labels placed off the rail, and proof/takeaway zones separated from the sequence.',
              required_zones: ['title_zone', 'claim_zone', 'timeline_zone', 'evidence_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'timeline_panel', 'point_text', 'evidence_item', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'timeline_marker', 'audience_body_text', 'evidence_or_metric_text'],
                min_filled_required_zone_share: 0.8,
                max_milestone_count: 4,
                min_body_font_pt: 18,
              },
              prohibited: ['timeline rail through labels', 'milestone text below 18pt'],
            },
            {
              archetype_id: 'risk_control_matrix',
              use_when: 'compare risks, controls, gates, or quality criteria',
              layout_description: 'Matrix or comparison field with filled cells, clear row/column grammar, and a separate signal or takeaway area.',
              required_zones: ['title_zone', 'claim_zone', 'matrix_zone', 'signal_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'compare_panel', 'point_text', 'metric', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'matrix_or_compare_container', 'audience_body_text', 'evidence_or_metric_text'],
                min_filled_required_zone_share: 0.8,
                empty_cell_allowed: false,
                min_body_font_pt: 18,
              },
              prohibited: ['unfilled matrix cell', 'four-card template with fewer than four facts'],
            },
            {
              archetype_id: 'decision_dashboard',
              use_when: 'decision, recommendation, operating readout, or proof dashboard',
              layout_description: 'A decision or recommendation zone with supporting proof objects; visual hierarchy starts from the decision, not equal cards.',
              required_zones: ['title_zone', 'claim_zone', 'decision_zone', 'proof_zone', 'takeaway_zone'],
              content_schema: {
                required_shape_roles: ['title', 'core_sentence', 'content_panel', 'point_text', 'metric', 'takeaway'],
                required_shape_role_groups: ['title_text', 'core_claim_text', 'content_container', 'evidence_or_metric_text', 'takeaway_text'],
                min_filled_required_zone_share: 0.8,
                first_glance_hierarchy_required: true,
                min_body_font_pt: 18,
              },
              prohibited: ['all content in equal cards', 'no first-glance hierarchy'],
            },
          ],
          slide_binding_contract: {
            required_fields: ['selected_archetype', 'archetype_instance_id', 'rhythm_role', 'zones'],
            zone_required_fields: ['zone_id', 'semantic_role', 'bounds', 'intended_content', 'min_font_pt', 'safe_inset_in'],
            shape_binding_field: 'layout_zone_id',
            acceptance_rule: 'Every non-decorative audience-facing shape must bind to a declared zone and stay inside that zone; the zone bounds and safe inset must make the text/card relationship explicit before officecli materializes the plan.',
          },
        },
        design_spec_lock: {
          spec_id: 'native_pptx_spec_lock_v1',
          owner: 'llm_agent',
          required: true,
          source: 'visual_direction_plus_slide_blueprint',
          borrowed_principles: ['ppt_master_style_spec_lock', 'template_layout_grammar', 'per_page_visual_plan', 'explicit_grid', 'font_floor', 'layout_rhythm', 'rendered_quality_gate'],
          canvas_in: { width: 16, height: 9 },
          palette: {
            background: '<hex>',
            ink: '<hex>',
            muted: '<hex>',
            accent: '<hex>',
            panel: '<hex>',
          },
          typography: {
            title_font: '<font>',
            body_font: '<font>',
            title_pt_min: 36,
            body_pt_min: 18,
            point_index_pt_min: 16,
            table_body_pt_min: 11,
          },
          grid: {
            edge_margin_in_min: 0.6,
            inter_block_gap_in_min: 0.32,
          },
          motif: '<one visual motif used without title underlines>',
          layout_archetypes: [
            'executive_status_board',
            'workflow_map',
            'risk_control_matrix',
            'evidence_timeline',
            'route_comparison',
            'decision_dashboard',
          ],
          forbidden_motifs: ['decorative_title_underline', 'empty_four_card_template', 'consecutive_same_composition'],
          qa_gates: ['bounds', 'font_floor', 'text_fit', 'structural_visual', 'slot_fill', 'layout_variety', 'true_render_screenshot'],
        },
        text_fit_rules: {
          unit: 'inches',
          required: true,
          text_bearing_shape_rule: 'Every text-bearing shape, including meta labels, route labels, speaker_identity, evidence badges, boundary notes, and panel headings, must have positive bounds and meet the height floor for its font and text length. Do not treat short labels as exempt unless role is page_number, page_no, cover_meta, meta, footer, or point_index.',
          defaults: {
            compact_label_min_height_in: 0.64,
            sentence_body_min_height_in: 0.96,
            lead_sentence_min_height_in: 0.95,
          },
          role_min_height_in: {
            speaker_identity: 0.64,
            route_label: 0.64,
            panel_title: 0.68,
            point_text_short: 0.68,
            point_text_sentence: 0.90,
            body_sentence: 0.90,
            boundary_note: 0.90,
            core_sentence: 0.95,
            lead: 0.95,
            intro: 0.95,
            thesis: 0.95,
            takeaway: 0.95,
          },
          hard_fail_examples: [
            '20pt panel_title in 0.42in height',
            '18pt point_text sentence in 0.58in height',
            '20-24pt core_sentence or takeaway in 0.62in height',
          ],
        },
        geometry_rules: {
          unit: 'inches',
          required: true,
          canvas: { width_in: 16, height_in: 9 },
          all_shapes_must_have_positive_bounds: true,
          line_and_connector_min_thickness_in: 0.03,
          line_and_connector_rule: 'A vertical line uses width_in >= 0.03 and positive height_in; a horizontal line uses positive width_in and height_in >= 0.03. Never emit 0 or negative width/height for line or connector shapes.',
          bounds_examples: [
            { kind: 'line', role: 'vertical_gate_ladder', bounds: { left_in: 9.88, top_in: 4.08, width_in: 0.04, height_in: 1.72 } },
            { kind: 'connector', role: 'horizontal_route_connector', bounds: { left_in: 5.34, top_in: 4.78, width_in: 1.72, height_in: 0.04 } },
          ],
        },
        materializable_shape_kind_contract: {
          allowed_kind_values: ['text_box', 'text', 'rect', 'rectangle', 'rounded_rect', 'panel', 'oval', 'circle', 'line', 'connector'],
          disallowed_kind_values: ['triangle', 'right_triangle', 'polygon', 'arrow', 'icon', 'group', 'freeform', 'image', 'svg', 'path'],
          icon_strategy: 'compose simple icons from rect, line, and oval primitives only',
        },
        design_system: {
          borrowed_principles: ['ppt_master_style_spec_lock', 'template_layout_grammar', 'per_page_visual_plan', 'explicit_grid', 'font_floor', 'layout_rhythm', 'rendered_quality_gate'],
          owner: 'llm_agent',
          spec_lock_required: true,
          per_page_visual_qa_required: true,
          mock_fixture_visual_sample_allowed: false,
          test_double_can_claim_visual_quality: false,
          grid: {
            canvas_in: { width: 16, height: 9 },
            edge_margin_in_min: 0.6,
            inter_block_gap_in_min: 0.32,
          },
          typography_floor: {
            title_pt_min: 36,
            body_pt_min: 18,
            point_index_pt_min: 16,
            table_body_pt_min: 11,
          },
          forbidden_motifs: ['decorative_title_underline', 'empty_four_card_template', 'consecutive_same_composition'],
          layout_rhythm: {
            repeated_concrete_composition_limit: 2,
            required_distinct_composition_share: 0.75,
          },
          evidence_required_for_visual_sample: [
            'live_codex_executor_shape_plan',
            'editable_shape_plan.design_spec_lock',
            'per_slide_layout_intent',
            'libreoffice_poppler_render_screenshots',
            'visual_director_review',
            'screenshot_review',
            'export_pptx',
          ],
        },
        slides: [
          {
            slide_id: 'S01',
            title: '<audience-facing title>',
            background: '#FFFFFF',
            layout_family: '<visual layout family label for reporting only>',
            core_sentence: '<audience-facing core sentence>',
            page_core_content: ['<editable text>'],
            layout_intent: {
              rhetorical_role: '<cover | comparison | timeline | gate | system_map | synthesis>',
              composition_signature: '<stable human-readable signature from concrete geometry>',
              visual_weight: '<left_heavy | right_heavy | centered | diagonal | radial | bottom_band>',
              primary_grid: '<2_column | 3_card | timeline_rail | gate_ladder | radial_axes | hero_callout>',
              negative_space_strategy: '<where the breathing space is intentionally left>',
              non_text_visual: '<shape/chart/table/connector/metric grid used as first-glance signal>',
              forbidden_template_reuse_checked: true,
            },
            template_layout_binding: {
              selected_archetype: 'professional_system_map',
              archetype_instance_id: 'S01-system-map-v1',
              rhythm_role: '<opening | proof | contrast | synthesis | close>',
              zone_gap_in_min: 0.32,
              zone_inset_in_min: 0.15,
              zones: [
                {
                  zone_id: 'title_zone',
                  semantic_role: 'title',
                  bounds: { left_in: 0.9, top_in: 0.55, width_in: 11.0, height_in: 1.05 },
                  intended_content: 'audience-facing title',
                  min_font_pt: 36,
                  safe_inset_in: 0.15,
                },
                {
                  zone_id: 'claim_zone',
                  semantic_role: 'core_claim',
                  bounds: { left_in: 0.95, top_in: 1.72, width_in: 11.8, height_in: 0.95 },
                  intended_content: 'one-sentence claim',
                  min_font_pt: 18,
                  safe_inset_in: 0.15,
                },
                {
                  zone_id: 'system_map_zone',
                  semantic_role: 'system_map',
                  bounds: { left_in: 0.95, top_in: 3.05, width_in: 8.2, height_in: 3.05 },
                  intended_content: 'route or workflow diagram with labels off connector lanes',
                  min_font_pt: 18,
                  safe_inset_in: 0.15,
                },
                {
                  zone_id: 'gate_zone',
                  semantic_role: 'delivery_gate',
                  bounds: { left_in: 9.65, top_in: 3.05, width_in: 4.5, height_in: 3.05 },
                  intended_content: 'gate outcome or quality decision',
                  min_font_pt: 18,
                  safe_inset_in: 0.15,
                },
                {
                  zone_id: 'evidence_zone',
                  semantic_role: 'evidence_note',
                  bounds: { left_in: 0.95, top_in: 6.45, width_in: 13.2, height_in: 1.2 },
                  intended_content: 'compact proof note without receipt clutter',
                  min_font_pt: 18,
                  safe_inset_in: 0.15,
                },
              ],
            },
            native_shapes: [
              {
                shape_id: 'S01-title',
                kind: 'text_box',
                role: 'title',
                quality_role: 'content',
                layout_zone_id: 'title_zone',
                editable_text: '<text>',
                bounds: { left_in: 1.0, top_in: 0.6, width_in: 13.8, height_in: 1.1 },
                font_size: 40,
                color: '#171C24',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-core',
                kind: 'text_box',
                role: 'core_sentence',
                quality_role: 'content',
                layout_zone_id: 'claim_zone',
                editable_text: '<one sentence audience-facing claim>',
                bounds: { left_in: 1.0, top_in: 1.85, width_in: 11.8, height_in: 0.98 },
                font_size: 22,
                color: '#5B6570',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-point-1-text',
                kind: 'text_box',
                role: 'point_text',
                quality_role: 'content',
                layout_zone_id: 'system_map_zone',
                editable_text: '<sentence-length point text with evidence>',
                bounds: { left_in: 1.2, top_in: 3.1, width_in: 3.5, height_in: 0.92 },
                font_size: 18,
                color: '#171C24',
                fill: 'none',
                line: 'none',
              },
              {
                shape_id: 'S01-point-1-index',
                kind: 'oval',
                role: 'point_index',
                quality_role: 'content',
                layout_zone_id: 'system_map_zone',
                editable_text: '01',
                bounds: { left_in: 1.0, top_in: 2.1, width_in: 0.52, height_in: 0.52 },
                font_size: 16,
                color: '#171C24',
                fill: '#DBEAFE',
                line: '#2563EB',
              },
            ],
            redcube_svg_ir_intent: {
              root_viewbox: '0 0 1152 648',
              editable_text_required: true,
              required_intents: [
                'text:title',
                'text:point_text',
                'rect:content_panel',
                'group:content_point',
                'layout_intent:composition_signature',
              ],
            },
          },
        ],
      },
    };
  }
