// @ts-nocheck

import {
  OPL_GENERATED_SURFACE_EXIT_GATE,
} from './visual-pack-compiler-handoff.js';

export const RCA_RETAINED_VISUAL_AUTHORITY = Object.freeze([
  'visual_truth',
  'review_export_verdict',
  'artifact_authority',
  'visual_memory_body',
  'owner_receipt',
  'native_helper_implementation',
  'typed_blocker',
  'safe_action_refs',
]);

export const OPL_OWNED_GENERIC_PRIMITIVES = Object.freeze([
  'standard_domain_agent_scaffold',
  'functional_harness',
  'generic_runtime',
  'generic_scheduler',
  'daemon',
  'typed_queue',
  'stage_attempt_orchestrator',
  'attempt_ledger',
  'typed_closeout_transport',
  'generic_runner',
  'generic_transition_runner',
  'workbench_shell',
  'memory_transport',
  'memory_refs_only_writeback_chain',
  'artifact_lifecycle',
  'review_repair_transport',
  'restart_dead_letter_repair_human_gate_state_chain',
  'native_helper_generic_envelope',
  'generated_cli_mcp_product_entry_sidecar_status_session_workbench_wrapper',
]);

export const OPL_GENERATED_INTERFACE_CONSUMPTION = Object.freeze({
  surface_kind: 'opl_generated_interface_consumption',
  ref: '/opl_generated_interface_consumption',
  owner: 'one-person-lab',
  consumer: 'redcube_ai',
  status: 'opl_generated_surface_consumed_domain_handlers_only',
  projection_mode: 'generated_descriptor_owner_with_domain_handler_targets',
  unified_metadata_owner: 'one-person-lab',
  generated_interface_owner: 'one-person-lab',
  domain_handler_owner: 'redcube_ai',
  generated_descriptor_scope: [
    'cli',
    'mcp',
    'skill',
    'product_entry',
    'product_status',
    'product_session',
    'sidecar',
    'workbench',
  ],
  repo_local_handler_targets: [
    'redcube_cli',
    'redcube_mcp',
    'invokeProductEntry',
    'invokeDomainEntry',
    'product_sidecar',
    'product_entry_session_snapshot_refs_adapter',
  ],
  repo_local_launcher_policy: {
    redcube_cli_role: 'domain_handler_target_or_direct_domain_entry_only',
    redcube_mcp_role: 'domain_handler_target_or_direct_protocol_adapter_only',
    product_sidecar_role: 'domain_action_target_or_refs_only_adapter',
    product_entry_session_snapshot_refs_adapter_role: 'entry_session_domain_snapshot_refs_only_adapter',
    cli_mcp_skill_product_status_workbench_metadata_owner: 'one-person-lab',
    default_generic_dispatch_owner: 'one-person-lab',
    default_supervision_owner: 'one-person-lab',
    legacy_supervision_public_surface: 'retired',
    redcube_cli_is_unified_metadata_owner: false,
    redcube_mcp_is_unified_metadata_owner: false,
    product_entry_session_snapshot_refs_adapter_is_generic_session_owner: false,
  },
  bridge_exit_gate: { ...OPL_GENERATED_SURFACE_EXIT_GATE },
  consumed_from_refs: [
    '/domain_descriptor',
    '/family_action_catalog',
    '/family_stage_control_plane',
    '/visual_pack_compiler_handoff/generated_surface_handoff',
    '/privatized_functional_module_audit',
  ],
  rca_retained_authority: [...RCA_RETAINED_VISUAL_AUTHORITY],
  forbidden_rca_claims: {
    rca_owns_generated_cli_mcp_skill_product_status_workbench_metadata: false,
    rca_owns_default_generic_dispatch: false,
    rca_owns_generic_session_shell: false,
    rca_owns_generic_workbench: false,
  },
});

export const OPL_STABILITY_READ_MODEL_SURFACES = Object.freeze([
  'family_conflict_envelope',
  'control_loop_summary',
  'usage_projection',
  'resource_pressure',
  'observability_export',
  'external_stability_policy',
]);

export const OPL_FUNCTIONAL_HARNESS_COVERAGE = Object.freeze({
  harness_role: 'functional_harness_consumer',
  coverage_status: 'domain_authority_pack_landed',
  pass_claim_scope: 'consumer_contract_coverage_only',
  opl_harness_pass_is_visual_ready: false,
  opl_harness_pass_is_exportable: false,
  opl_harness_pass_is_handoffable: false,
  opl_harness_pass_is_artifact_producing_owner_receipt: false,
  rca_generic_runtime_owner: false,
  covered_chains: [
    'memory_refs_only_writeback_chain',
    'queue_stage_attempt_typed_closeout',
    'generic_transition_runner',
    'restart_dead_letter_repair_human_gate_state_chain',
  ],
  chain_authority: {
    memory_refs_only_writeback_chain: {
      owner: 'opl',
      rca_retains: ['visual_memory_body', 'owner_receipt', 'typed_blocker'],
      rca_exports_only: ['memory_locator_refs', 'writeback_receipt_refs', 'safe_action_refs'],
      memory_body_written_by_opl: false,
    },
    queue_stage_attempt_typed_closeout: {
      owner: 'opl',
      rca_retains: ['visual_truth', 'review_export_verdict', 'artifact_authority', 'owner_receipt'],
      rca_exports_only: ['stage_descriptor_refs', 'attempt_source_refs', 'typed_closeout_receipt_refs'],
      artifact_produced_by_harness_pass: false,
    },
    generic_transition_runner: {
      owner: 'opl',
      rca_retains: ['visual_transition_spec', 'typed_blocker', 'safe_action_refs'],
      rca_exports_only: ['transition_spec_ref', 'transition_result_refs', 'owner_receipt_refs'],
      visual_ready_declared_by_runner: false,
    },
    restart_dead_letter_repair_human_gate_state_chain: {
      owner: 'opl',
      rca_retains: ['typed_blocker', 'safe_action_refs', 'review_export_verdict'],
      rca_exports_only: ['repair_hint_refs', 'human_gate_reason_refs', 'dead_letter_receipt_refs'],
      handoffable_declared_by_state_chain: false,
    },
  },
});

export function buildFamilySchedulerReplacementProjection() {
  return {
    ref: '/family_scheduler_replacement',
    contract_ref: 'opl.family_scheduler_replacement.v1',
    owner: 'opl',
    consumer: 'redcube_ai',
    projection_mode: 'consumer_projection_only',
    rca_generic_scheduler_owner: false,
    rca_generic_daemon_owner: false,
    rca_generic_lifecycle_owner: false,
    rca_generic_queue_owner: false,
    rca_generic_attempt_ledger_owner: false,
    rca_generic_runner_owner: false,
    rca_generic_workbench_owner: false,
    rca_thin_surface_role: 'visual_domain_authority_pack_plus_thin_program_surface',
    projection_scope: 'consumer_projection_and_visual_domain_authority_refs_only',
    opl_owned_generic_surfaces: [
      'family_scheduler',
      'daemon',
      'generic_lifecycle',
      'typed_queue',
      'attempt_ledger',
      'generic_runner',
      'workbench_shell',
    ],
    visual_stage_descriptor_scope: 'opl_stage_execution_plan_route_handler_refs_only',
    rca_retained_authority: [...RCA_RETAINED_VISUAL_AUTHORITY],
  };
}

export function buildOplStabilityReadModelConsumptionProjection() {
  return {
    ref: '/opl_stability_read_model_consumption',
    contract_ref: 'opl.family_operator_stability_read_model.v1',
    owner: 'opl',
    consumer: 'redcube_ai',
    status: 'refs_only_consumer_projection_landed',
    projection_mode: 'consumer_projection_only',
    observability_only: true,
    rca_surface_role: 'visual_domain_authority_pack_plus_thin_program_surface',
    completion_scope: 'stability_read_model_refs_projected_not_live_soak',
    live_soak_claimed: false,
    consumed_read_model_surfaces: [
      {
        surface: 'family_conflict_envelope',
        contract_ref: 'contracts/family-orchestration/family-conflict-envelope.schema.json',
        rca_consumes: 'typed_blocker_or_conflict_refs_only',
      },
      {
        surface: 'control_loop_summary',
        contract_ref: 'contracts/opl-framework/family-product-operator-projection.json#/required_projection_fields/control_loop_summary',
        rca_consumes: 'trigger_decision_route_receipt_blocker_refs_only',
      },
      {
        surface: 'usage_projection',
        contract_ref: 'contracts/opl-framework/family-runtime-attempt-contract.json#/stability_projection_fields/usage_projection',
        rca_consumes: 'observed_usage_refs_only',
      },
      {
        surface: 'resource_pressure',
        contract_ref: 'contracts/opl-framework/family-product-operator-projection.json#/required_projection_fields/resource_pressure',
        rca_consumes: 'observed_retry_budget_pressure_refs_only',
      },
      {
        surface: 'observability_export',
        contract_ref: 'opl runtime observability-export [--format json|openmetrics]',
        rca_consumes: 'read_only_counter_export_refs_only',
      },
      {
        surface: 'external_stability_policy',
        contract_ref: 'contracts/opl-framework/family-product-operator-projection.json#/external_stability_learning_policy',
        rca_consumes: 'policy_boundary_refs_only',
      },
    ],
    rca_does_not_own: [
      'family_conflict_envelope_schema',
      'control_loop_summary_builder',
      'usage_projection_aggregator',
      'resource_pressure_projection',
      'runtime_observability_exporter',
      'external_stability_policy_runtime',
      'generic_fallback_completion',
      'string_rule_retry_execution',
      'generic_event_bus_truth_source',
      'generic_runtime_adapter_success_semantics',
    ],
    rca_retained_authority: [...RCA_RETAINED_VISUAL_AUTHORITY],
    authority_boundary: {
      opl_can_execute_rca_domain_action: false,
      opl_can_write_rca_domain_truth: false,
      opl_can_authorize_visual_ready: false,
      opl_can_authorize_quality_verdict: false,
      opl_can_authorize_exportable: false,
      opl_can_write_artifact_blob: false,
      opl_can_write_visual_memory_body: false,
      provider_completion_is_visual_ready: false,
      generic_fallback_can_mark_success: false,
      string_retry_can_drive_execution: false,
      event_bus_can_be_truth_source: false,
      runtime_adapter_started_is_behavior_equivalent: false,
    },
    forbidden_rca_stability_owner_flags: {
      rca_family_conflict_envelope_owner: false,
      rca_control_loop_summary_owner: false,
      rca_usage_projection_owner: false,
      rca_resource_pressure_owner: false,
      rca_observability_export_owner: false,
      rca_external_stability_policy_owner: false,
      rca_generic_fallback_completion_owner: false,
      rca_string_rule_retry_execution_owner: false,
      rca_generic_event_bus_truth_owner: false,
      rca_runtime_adapter_success_semantics_owner: false,
    },
  };
}

export function buildOplGenericPrimitiveConsumptionProjection() {
  return {
    ref: '/opl_generic_primitive_consumption',
    contract_ref: 'opl.standard_domain_agent_scaffold_and_generic_primitives.v1',
    owner: 'opl',
    consumer: 'redcube_ai',
    status: 'functional_consumer_follow_through_landed',
    projection_mode: 'consumer_projection_only',
    rca_surface_role: 'visual_domain_authority_pack_plus_thin_program_surface',
    completion_scope: 'functional_consumer_follow_through_complete_not_live_soak',
    live_soak_claimed: false,
    rca_does_not_own: [...OPL_OWNED_GENERIC_PRIMITIVES],
    opl_owned_generic_primitives: [...OPL_OWNED_GENERIC_PRIMITIVES],
    rca_retained_authority: [...RCA_RETAINED_VISUAL_AUTHORITY],
    functional_harness_consumer_coverage: OPL_FUNCTIONAL_HARNESS_COVERAGE,
    rca_thin_program_surfaces: [
      'single redcube-ai app skill',
      'service-safe domain entry',
      'product sidecar projection',
      'stage control projection',
      'visual transition spec',
      'artifact locator refs',
      'review/export gate refs',
      'owner receipt refs',
      'native helper implementation refs',
    ],
    consumed_projection_surfaces: [
      {
        primitive: 'standard_domain_agent_scaffold',
        contract_ref: 'contracts/runtime-program/opl-family-contract-adoption.json#/standard_domain_agent_skeleton',
        manifest_ref: '/standard_domain_agent_skeleton',
        sidecar_ref: '/mapped_surfaces/standard_domain_agent_skeleton',
      },
      {
        primitive: 'generic_scheduler',
        contract_ref: 'contracts/runtime-program/opl-family-contract-adoption.json#/family_scheduler_replacement',
        manifest_ref: '/family_scheduler_replacement',
        sidecar_ref: '/runtime_framework/family_scheduler_replacement',
      },
      {
        primitive: 'memory_transport',
        contract_ref: 'contracts/runtime-program/opl-family-contract-adoption.json#/standard_domain_agent_skeleton/domain_memory_descriptor_locator',
        manifest_ref: '/domain_memory_descriptor_locator',
        sidecar_ref: '/mapped_surfaces/visual_pattern_memory_writeback',
      },
      {
        primitive: 'artifact_lifecycle',
        contract_ref: 'contracts/runtime-program/opl-family-contract-adoption.json#/standard_domain_agent_skeleton/lifecycle_guarded_apply_proof',
        manifest_ref: '/lifecycle_guarded_apply_proof',
        sidecar_ref: '/mapped_surfaces/lifecycle_guarded_apply',
      },
      {
        primitive: 'review_repair_transport',
        contract_ref: 'contracts/runtime-program/opl-family-contract-adoption.json#/quality_projection',
        manifest_ref: '/review_state',
        sidecar_ref: '/mapped_surfaces/review_projection',
      },
      {
        primitive: 'native_helper_generic_envelope',
        contract_ref: 'contracts/runtime-program/python-native-helper-catalog.json',
        manifest_ref: '/native_ppt_operator_ux',
        sidecar_ref: '/mapped_surfaces/native_helper_implementation',
      },
      {
        primitive: 'generated_cli_mcp_product_entry_sidecar_status_session_workbench_wrapper',
        contract_ref: 'rca.visual_pack_compiler_handoff.v1',
        manifest_ref: '/visual_pack_compiler_handoff/generated_surface_handoff',
        sidecar_ref: '/mapped_surfaces/visual_pack_compiler_handoff',
        owner: 'one-person-lab',
        consumer: 'redcube_ai',
        current_rca_role: 'domain_handler_target_or_direct_entry_only',
        repo_local_handler_targets: [...OPL_GENERATED_INTERFACE_CONSUMPTION.repo_local_handler_targets],
      },
    ],
    forbidden_rca_generic_owner_flags: {
      rca_generic_scheduler_owner: false,
      rca_generic_runtime_owner: false,
      rca_generic_daemon_owner: false,
      rca_generic_queue_owner: false,
      rca_stage_attempt_orchestrator_owner: false,
      rca_generic_attempt_ledger_owner: false,
      rca_typed_closeout_transport_owner: false,
      rca_generic_runner_owner: false,
      rca_generic_transition_runner_owner: false,
      rca_generic_workbench_owner: false,
      rca_memory_transport_owner: false,
      rca_memory_refs_only_writeback_chain_owner: false,
      rca_artifact_lifecycle_owner: false,
      rca_review_repair_transport_owner: false,
      rca_restart_dead_letter_repair_human_gate_state_chain_owner: false,
      rca_native_helper_generic_envelope_owner: false,
      rca_cli_mcp_product_entry_sidecar_status_session_workbench_wrapper_owner: false,
    },
  };
}

export function buildOplSubstrateAdapterExportProjection() {
  return {
    surface_kind: 'opl_substrate_adapter_export',
    projection_id: 'rca.opl_substrate_adapter_export.v1',
    ref: '/opl_substrate_adapter_export',
    contract_ref: 'rca.opl_substrate_adapter_export.v1',
    owner: 'redcube_ai',
    consumer: 'opl_framework',
    status: 'refs_only_substrate_adapter_export_landed',
    adapter_model: 'domain_owned_opaque_index_only_export',
    export_mode: 'opaque_index_only_refs',
    projection_mode: 'consumer_projection_only',
    read_only: true,
    refs_only: true,
    opaque_refs_only: true,
    index_only: true,
    exports_body_payloads: false,
    export_ref_families: [
      {
        family: 'workspace_refs',
        mode: 'locator_only',
        refs: [
          '/workspace_locator',
          '/runtime_inventory/workspace_binding',
          '/task_lifecycle',
          '/runtime_loop_closure',
          '/workspace_receipt_inventory_projection',
        ],
      },
      {
        family: 'source_refs',
        mode: 'descriptor_index_only',
        refs: [
          '/family_stage_control_plane',
          '/domain_memory_descriptor',
          '/domain_memory_descriptor_locator',
          '/controlled_visual_stage_attempt',
        ],
      },
      {
        family: 'artifact_refs',
        mode: 'locator_hash_index_only',
        refs: [
          '/artifact_locator_contract',
          '/product_sidecar_receipt_refs',
          '/workspace_receipt_inventory_projection',
          '/operator_evidence_readiness_projection',
        ],
      },
      {
        family: 'memory_refs',
        mode: 'locator_receipt_index_only',
        refs: [
          '/domain_memory_descriptor',
          '/domain_memory_descriptor_locator/memory_locator',
          '/domain_memory_descriptor_locator/writeback_receipt_locator',
          '/controlled_memory_apply_proof/runtime_receipt_instances',
        ],
      },
    ],
    lifecycle_projection_refs: [
      '/task_lifecycle',
      '/runtime_inventory',
      '/runtime_loop_closure',
      '/operator_evidence_readiness_projection',
    ],
    authority_boundary: {
      rca_owns_visual_truth: true,
      rca_owns_layout_review_export_verdict: true,
      rca_owns_deliverable_artifact_body: true,
      rca_owns_visual_memory_body: true,
      rca_owns_owner_receipt_authority: true,
      opl_can_index_workspace_refs: true,
      opl_can_index_source_refs: true,
      opl_can_index_artifact_refs: true,
      opl_can_index_memory_refs: true,
      opl_can_read_visual_truth: false,
      opl_can_write_visual_truth: false,
      opl_can_read_layout_review_export_verdict: false,
      opl_can_authorize_layout_review_export_verdict: false,
      opl_can_read_deliverable_artifact_body: false,
      opl_can_store_deliverable_artifact_body: false,
      opl_can_read_visual_memory_body: false,
      opl_can_write_visual_memory_body: false,
      opl_can_accept_or_reject_visual_memory: false,
      opl_can_issue_owner_receipt: false,
      opl_can_mutate_domain_artifacts: false,
      provider_completion_is_visual_ready: false,
      provider_completion_is_exportable: false,
      provider_completion_is_handoffable: false,
    },
    forbidden_export_fields: [
      'visual_truth',
      'layout_verdict',
      'review_verdict',
      'export_verdict',
      'deliverable_artifact_body',
      'canonical_artifact_blob',
      'visual_memory_body',
      'owner_receipt_authority',
    ],
    source_manifest_refs: {
      workspace_locator_ref: '/workspace_locator',
      family_stage_control_plane_ref: '/family_stage_control_plane',
      artifact_locator_contract_ref: '/artifact_locator_contract',
      domain_memory_descriptor_ref: '/domain_memory_descriptor',
      domain_memory_descriptor_locator_ref: '/domain_memory_descriptor_locator',
      workspace_receipt_inventory_projection_ref: '/workspace_receipt_inventory_projection',
      operator_evidence_readiness_projection_ref: '/operator_evidence_readiness_projection',
    },
  };
}
